// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —
// re-run the script if the live page content changes.
// Source: https://www.itsco.com/voip-unified-communications/
// Generated: 2026-05-21T14:32:22.505Z

export const SOURCE_URL = "https://www.itsco.com/voip-unified-communications/"

export const SOURCE_PARAGRAPHS = [
  /* 00 */ "Your business is only as successful as its ability to communicate. Outdated phone systems and disconnected communication platforms can lead to missed opportunities, poor customer experiences, and critical inefficiencies.",
  /* 01 */ "ITSco’s VoIP and Unified Communications services provide secure, scalable, and optimized solutions to enable seamless communication and collaboration across your organization—whether your team is in the office, remote, or hybrid.",
  /* 02 */ "With over 25 years of IT infrastructure expertise, ITSco designs, deploys, and manages VoIP and Unified Communications (UC) solutions that enhance productivity, mobility, and customer engagement.",
  /* 03 */ "We deploy modern, cloud-based or on-premises VoIP solutions that provide high-quality voice communication, advanced call routing, and easy scalability.",
  /* 04 */ "ITSco integrates VoIP with messaging, video conferencing, email, and collaboration tools into a single, easy-to-use platform, streamlining communication across all channels.",
  /* 05 */ "Empower your employees to work from anywhere with secure, cloud-based VoIP solutions, mobile apps, and softphone capabilities that provide the same functionality as an office desk phone.",
  /* 06 */ "ITSco ensures your VoIP system is secure, encrypted, and protected from cyber threats, helping businesses meet HIPAA, PCI DSS, and other industry compliance requirements.",
  /* 07 */ "We assess and optimize your network to ensure crystal-clear call quality, minimal latency, and reliable uptime, even for high-volume call environments.",
  /* 08 */ "ITSco provides 24/7 monitoring, maintenance, and technical support to keep your communication systems running smoothly and securely.",
  /* 09 */ "Without a modern, well-managed VoIP and Unified Communications solution, businesses face costly inefficiencies, communication breakdowns, and security risks:",
  /* 10 */ "Legacy phone systems and unoptimized networks lead to frustrating communication failures.",
  /* 11 */ "Without cloud-based VoIP, remote employees struggle with inconsistent access and functionality.",
  /* 12 */ "On-premises PBX systems require expensive maintenance, hardware upgrades, and service fees.",
  /* 13 */ "Unsecured VoIP systems are targets for hacking, fraud, and compliance violations.",
  /* 14 */ "Traditional systems lack the flexibility to scale with business growth or integrate with modern collaboration tools.",
  /* 15 */ "With 25+ years of IT expertise, ITSco delivers reliable and scalable VoIP & UC solutions tailored to business needs.",
  /* 16 */ "We ensure availability and crystal-clear call quality, optimizing your network for seamless communication.",
  /* 17 */ "ITSco’s VoIP solutions include advanced encryption, fraud prevention, and compliance monitoring.",
  /* 18 */ "We keep your communications running smoothly with expert implementation and 24/7 monitoring.",
  /* 19 */ "Don’t let outdated phone systems or unreliable communication tools hold your business back.",
  /* 20 */ "ITSco’s VoIP & Unified Communications services provide scalable, secure, and cost-effective solutions that enhance productivity, mobility, and collaboration.",
] as const
