// Content for /voip-unified-communications/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'VoIP & Unified Communications Services',
    description:
      'ITSco VoIP and unified communications — secure, scalable business voice and collaboration for office, remote, and hybrid teams. Book a free consultation.',
    canonical: 'https://www.itsco.com/voip-unified-communications',
  },
  serviceName: 'VoIP & Unified Communications',
  parent: { name: 'Managed IT Services', href: '/managed-it-services/' },
  hero: {
    eyebrow: 'Engineering · VoIP & UC',
    headlineLead: 'Business communication',
    headlineAccent: 'that just works.',
    body: S[0],
    utmSuffix: 'voip-unified-communications-hero',
  },
  heroImage: {
    src: '/images/hero/services/pexels-diva-plavalaguna-6937858.jpg',
    alt: 'Team collaborating over a unified communications platform',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Reliable, scalable, effective',
    headlineAccent: 'business communication.',
    paragraphs: [S[1], S[2]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years of IT infrastructure expertise' },
    { value: '24/7', label: 'Communication system monitoring and support' },
  ],
  capabilitiesHeading: {
    eyebrow: 'Our VoIP & UC Services',
    headlineLead: 'A modern communication',
    headlineAccent: 'platform, fully managed.',
  },
  capabilities: [
    {
      slug: 'voip-phone-system',
      title: 'VoIP Phone System Design & Implementation',
      description: S[3],
    },
    { slug: 'voip-uc-integration', title: 'Unified Communications Integration', description: S[4] },
    {
      slug: 'voip-remote-enablement',
      title: 'Remote & Hybrid Workforce Enablement',
      description: S[5],
    },
    { slug: 'voip-security', title: 'VoIP Security & Compliance', description: S[6] },
    {
      slug: 'voip-network-optimization',
      title: 'Network Optimization for Peak Performance',
      description: S[7],
    },
    { slug: 'voip-management-support', title: 'Ongoing Management & Support', description: S[8] },
  ],
  outcomes: {
    eyebrow: 'The Risk',
    headlineLead: 'Inefficient communication systems',
    headlineAccent: 'are costly.',
    paragraphs: [],
    tone: 'risk',
    bullets: [S[10], S[11], S[12], S[13], S[14]],
    image: {
      src: '/images/hero/services/pexels-divinetechygirl-1181745.jpg',
      alt: 'Hybrid team on a unified communications call',
    },
  },
  related: {
    heading: 'Explore more services',
    links: [
      {
        slug: 'network-engineering',
        label: 'Network Engineering',
        href: '/network-engineering/',
        description: 'Modern, secure, high-performance networks — the foundation VoIP runs on.',
      },
      {
        slug: 'microsoft-teams-services',
        label: 'Microsoft Teams Services',
        href: '/microsoft-teams-services/',
        description: 'Teams set up and managed as a real collaboration and calling hub.',
      },
      {
        slug: 'managed-network-services',
        label: 'Managed Network Services',
        href: '/managed-network-services/',
        description: 'Ongoing monitoring, management, and support for your network.',
      },
    ],
  },
  bookingUtm: 'voip-unified-communications-bottom',
}
