// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —
// re-run the script if the live page content changes.
// Source: https://www.itsco.com/managed-it-services-rtp/
// Generated: 2026-05-20T12:49:08.045Z

export const SOURCE_URL = "https://www.itsco.com/managed-it-services-rtp/"

export const SOURCE_PARAGRAPHS = [
  /* 00 */ "At ITSco, we design, deploy, and maintain secure, scalable, and robust IT environments to increase productivity and profitability. Let us be your Managed IT Services partner, located in the heart of Research Triangle Park, North Carolina .",
  /* 01 */ "Why choose ITSco for managed IT services in RTP ?",
  /* 02 */ "Take control of your IT budget with one of the most respected managed services providers in RTP.",
  /* 03 */ "Stay connected and productive with our state-of-the-art IT services in RTP. We remotely monitor and proactively manage your devices, and offer end-to-end network support.",
  /* 04 */ "Protect your systems from malware, ransomware, phishing, and hacks with cutting-edge cyber security services and support .",
  /* 05 */ "Save your in-house IT team from getting bogged down with day-to-day user issues and let our help desk technicians take care of them instead.",
  /* 06 */ "Trust our expertise to help you leverage the power of the cloud. Powerful and practical cloud technology solutions can reduce costs while increasing reliability and scalability.",
  /* 07 */ "Failure to plan is a plan for failure! Our IT service professionals in RTP can help you create and maintain robust business continuity plans that reduce existential risks to your company.",
  /* 08 */ "Protect your data from man-made and natural disasters with regular data backups and advanced Data Loss Prevention (DLP) services.",
  /* 09 */ "Using advanced tools to proactively identify and assess system vulnerabilities, we can address issues before they become serious business risks.",
  /* 10 */ "Reduce errors, effort, and expenses with next-gen automation. We can develop and maintain your automation engine and mentor your team to unleash hidden efficiencies .",
  /* 11 */ "We’ll manage your IT infrastructure projects to ensure they remain on track, and on budget, and meet the highest technical standards.",
  /* 12 */ "Are you getting the return you expect from your IT spending?",
  /* 13 */ "Ensure every IT dollar delivers the ROI you expect with our managed IT services in RTP. We’ll help you make more informed decisions and better IT investments:",
  /* 14 */ "Focus on predictability and ROI with an IT services company that brings 25+ years of experience to the table.",
  /* 15 */ "Of our clients have been with us for 5+ years",
  /* 16 */ "As one of the leading IT companies in RTP",
  /* 17 */ "Of our clients have experienced a severe cyber security breach",
  /* 18 */ "Our dedication to our team. And our team’s dedication to you.",
  /* 19 */ "Our dedication to customer service is evident in our customer retention rate; 60% of our clients have been with us for five or more years, and over a third have been with us for more than 10 years .",
  /* 20 */ "In an industry where 40% of companies who pay for managed IT solutions are looking to switch to other companies , we think our customer retention rate speaks for itself.",
  /* 21 */ "Our team has helped countless businesses in and around the RTP area — including Raleigh, Durham, Chapel Hill , and Cary, North Carolina — for over 25 years!",
  /* 22 */ "We partner with our customers to unlock the potential of Information Technology and help them achieve their business goals.",
  /* 23 */ "Let us help manage your Information Technology Services so that you can focus on growing your business .",
  /* 24 */ "ITSco has been providing businesses like yours with IT services in RTP since the mid-‘90s!",
  /* 25 */ "No matter what business you are in: healthcare, pharmaceuticals, manufacturing, technology – or any business that relies on technology , we can help you make sense out of IT.",
  /* 26 */ "For over 25 years, we have been successfully navigating a constantly changing landscape of technology risks and opportunities to help ensure our clients’ success: whether by supporting a regional healthcare provider to make sure that their IT systems are able to support exponential growth, or by helping a regional bank automate network security tasks or by showing a global oil company how to improve its security posture.",
  /* 27 */ "In every case, we have the experience, the engineering know-how and the project management experience to design and execute successful IT projects on a consistent basis.",
  /* 28 */ "Nobody is perfect. But we’re proud of our record of achievements and proud to be one of the most trusted IT firms in RTP.",
  /* 29 */ "Don’t be an easy target for the bad guys . Trust our managed IT services team in RTP to secure your network and systems with proven solutions designed, delivered, and supported by seasoned professionals.",
  /* 30 */ "We know there are a lot of IT companies in RTP, b ut ITSco sets itself apart by being an experienced, local provider of advanced cyber security solutions, including:",
  /* 31 */ "Improve uptime and reduce risk, while optimizing your IT spending. Partner with a trusted IT Services company in RTP that can provide managed IT solutions and services customized to your business needs.",
  /* 32 */ "Find out how ITSco is different from other IT companies in RTP and why SMBs in RTP have relied on us for over 25 years.",
  /* 33 */ "And sleep better knowing that we are on watch!",
] as const
