// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —
// re-run the script if the live page content changes.
// Source: https://www.itsco.com/managed-it-services-charlotte/
// Generated: 2026-05-20T12:43:53.061Z

export const SOURCE_URL = "https://www.itsco.com/managed-it-services-charlotte"

export const SOURCE_PARAGRAPHS = [
  /* 00 */ "Give your Charlotte business the managed IT services and support it needs to achieve your business goals. Why choose ITSco over other IT companies in Charlotte ?",
  /* 01 */ "Support your growing business in Charlotte with help from one of North Carolina’s premier managed services providers.",
  /* 02 */ "Let our Tar Heel IT services experts monitor and manage your network to ensure that your systems and devices are secured and running efficiently.",
  /* 03 */ "Protect critical business systems with proven security solutions that collect, analyze, and respond to critical security events, ensuring your business is never an easy target for cybercriminals.",
  /* 04 */ "Improve productivity and reduce end-user frustration by letting our well-trained, North Carolina based IT services team resolve IT problems quickly and efficiently.",
  /* 05 */ "From migration to management, our cloud solutions can help maximize your company’s ROI while improving reliability and scalability.",
  /* 06 */ "Depend on quick, attentive, and knowledgeable service governed by a service level agreement customized to the needs of your Charlotte business.",
  /* 07 */ "Protect your Charlotte business from catastrophe and ensure business continuity with secure data backups and customized disaster recovery plans.",
  /* 08 */ "Don’t let potential vulnerabilities put your Tar Heel business at risk. Our vulnerability management processes can identify, remediate and mitigate critical security risks.",
  /* 09 */ "Implement processes that improve the security and efficiency of your IT workflow. Save your team from extra work (and reduce human errors) with advanced IT automation services.",
  /* 10 */ "Our well seasoned technical project managers and senior engineering resources ensure that all of our IT projects in Charlotte deliver the intended results – on time and within budget.",
  /* 11 */ "We’re dedicated to delivering the very best customized IT managed services in Charlotte and doing so in a way that supports your business plans and delivers solid ROI.",
  /* 12 */ "We’ll conduct thorough analyses of your systems, your network, and your security posture to verify that your IT infrastructure can support your growth and minimize your risks.",
  /* 13 */ "Our business technology solutions in Charlotte include:",
  /* 14 */ "Of our clients have been with us for 5+ years",
  /* 15 */ "As one of the leading IT companies in North Carolina",
  /* 16 */ "Of our clients have experienced a serious cybersecurity breach",
  /* 17 */ "Why choose a North Carolina -based IT services company to manage the IT infrastructure of your Charlotte business?",
  /* 18 */ "Our Tar Heel roots and our commitment to our customers and employees ensure that we can attract a qualified and passionate team of IT specialists, from front-line service desk techs to senior engineers and C-level consultants.",
  /* 19 */ "At ITSco, we believe that smart and motivated employees create happy customers – and our dedication to customer service is evident in our customer retention rate: 60% of our clients have been with us for five or more years, and over a third have been with us for more than ten years .",
  /* 20 */ "That’s a record we are proud of – especially when you consider that 40% of companies who pay for managed IT in Charlotte look to switch providers every year!",
  /* 21 */ "We’re proud of our 25-year track record of satisfying the IT needs of companies large and small, in a wide variety of industries.",
  /* 22 */ "ITSco’s clients run the gamut from one of the largest physician-owned medical groups in North Carolina , to a regional bank with more than 2500 employees. From numerous local tech startups, to one of the largest oil companies in the world.",
  /* 23 */ "As a Charlotte business owner , you can rest assured that your IT systems are being managed by some of the best computer engineering, computer support, and customer service talent in North Carolina . Our full range of services and customizable service plans are designed to help our customers get the maximum benefit out of their IT spending.",
  /* 24 */ "Improving your security posture is a process that never ends. Work with our cyber security team to find the right mix of defensive measures for your business. Trust ITSco, as one of the most dependable managed services companies in North Carolina , to help keep your critical infrastructure secure from Cyber Criminals!",
  /* 25 */ "Our advanced IT Security Services in Charlotte, include:",
  /* 26 */ "Don’t settle for being just another nameless client of a colossal, impersonal national IT services firm.",
  /* 27 */ "At ITSco, we will take the time to understand the uniqueness of your business, and to design an IT support plan that will be aligned with your business goals.",
  /* 28 */ "Find out how one of the most technically capable IT companies in North Carolina can help boost the productivity and profitability of your Queen City business.",
] as const
