// Content for /managed-it-services-charlotte/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'Managed IT Services in Charlotte, NC | ITSco',
    description:
      'ITSco delivers managed IT services in Charlotte, NC — network security, help desk, cloud, and IT project management — to reduce risk and boost efficiency. Book a free consultation.',
    canonical: 'https://www.itsco.com/managed-it-services-charlotte/',
  },
  hero: {
    eyebrow: 'Managed IT Services · Charlotte, NC',
    headlineLead: 'Managed IT services in Charlotte that',
    headlineAccent: 'reduce risk and boost efficiency.',
    body: S[0],
    utmSuffix: 'managed-it-charlotte-hero',
  },
  heroImage: {
    src: '/images/hero/local/charlotte nc .jpg',
    alt: 'Downtown Charlotte, North Carolina skyline',
  },
  capabilitiesHeading: {
    eyebrow: 'Comprehensive IT Managed Services',
    headlineLead: 'Full-suite IT solutions for',
    headlineAccent: 'Charlotte businesses.',
  },
  capabilities: [
    { slug: 'remote-monitoring', title: 'Remote Monitoring', description: S[2] },
    { slug: 'network-security-services', title: 'Network Security Services', description: S[3] },
    { slug: 'help-desk-services', title: 'Help Desk Services', description: S[4] },
    { slug: 'cloud-computing', title: 'Cloud Computing Services', description: S[5] },
    { slug: 'custom-slas', title: 'Customized SLAs', description: S[6] },
    { slug: 'disaster-recovery', title: 'Disaster Recovery', description: S[7] },
    { slug: 'vulnerability-management', title: 'Vulnerability Management', description: S[8] },
    { slug: 'it-automation', title: 'IT Automation', description: S[9] },
    { slug: 'it-project-management', title: 'IT Project Management', description: S[10] },
  ],
  positioning: {
    eyebrow: 'Scalable & Customized',
    headlineLead: 'Scalable IT services for',
    headlineAccent: 'Charlotte businesses.',
    paragraphs: [S[1], S[11], S[12], S[22], S[23]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years serving Charlotte & North Carolina' },
    { value: '0%', label: 'Of our clients have experienced a serious security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'An IT company Charlotte',
    headlineAccent: 'business owners trust.',
    paragraphs: [S[17], S[18], S[19], S[20], S[21]],
    image: {
      src: '/images/hero/local/charlotte nc 6.jpg',
      alt: 'Charlotte, North Carolina cityscape',
    },
  },
  security: {
    eyebrow: 'Cybersecurity in Charlotte',
    headlineLead: 'Protect your computer network',
    headlineAccent: 'from cyber criminals.',
    paragraphs: [S[24], S[26], S[27]],
    image: {
      src: '/images/hero/local/charlotte nc 3.jpg',
      alt: 'Charlotte, North Carolina at dusk',
    },
  },
  citySlug: 'charlotte',
  bookingUtm: 'managed-it-charlotte-bottom',
}
