// Content for /it-company-durham/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).
// The live page is narrative-led; capability descriptions use ITSco's
// standard managed-IT service copy since the source has no capability list.

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'IT Company in Durham, NC | ITSco',
    description:
      'ITSco is a trusted IT company in Durham, NC — managed IT, cybersecurity, cloud, and support delivered with an open-book, transparent approach. Book a free consultation.',
    canonical: 'https://www.itsco.com/it-company-durham/',
  },
  hero: {
    eyebrow: 'IT Company · Durham, NC',
    headlineLead: 'An IT company in Durham',
    headlineAccent: 'that generates real value.',
    body: S[7],
    utmSuffix: 'it-company-durham-hero',
  },
  heroImage: {
    src: '/images/hero/local/durham nc.jpg',
    alt: 'Downtown Durham, North Carolina',
  },
  capabilitiesHeading: {
    eyebrow: 'A Full-Service IT Company',
    headlineLead: 'Comprehensive IT solutions',
    headlineAccent: 'for Durham, NC businesses.',
  },
  capabilities: [
    { slug: 'remote-monitoring', title: 'Remote Monitoring', description: 'We remotely monitor and proactively manage your network and devices, resolving issues before they can impact your business.' },
    { slug: 'cyber-security-management', title: 'Cybersecurity', description: 'A multi-layered cybersecurity defense — SIEM and SOC services, firewall management, and endpoint protection.' },
    { slug: 'help-desk-services', title: 'Help Desk Services', description: 'Knowledgeable, courteous help desk support available remotely and on-site for your team.' },
    { slug: 'cloud-computing', title: 'Cloud Services', description: 'Cloud solutions our engineers plan, migrate, secure, and manage for improved reliability and scalability.' },
    { slug: 'custom-slas', title: 'Customized SLAs', description: 'Choose the services you need with guaranteed response times defined in a service level agreement.' },
    { slug: 'disaster-recovery', title: 'Disaster Recovery', description: 'Secure backups and tested disaster recovery plans that protect your data and operations.' },
    { slug: 'vulnerability-management', title: 'Vulnerability Management', description: 'Automated vulnerability scanning and proactive, managed remediation to reduce risk.' },
    { slug: 'it-project-management', title: 'IT Project Management', description: 'Seasoned engineers and project managers deliver your IT projects on time and on budget.' },
  ],
  positioning: {
    eyebrow: 'A Single Source for Technology',
    headlineLead: 'Reimagine IT management',
    headlineAccent: 'with an experienced partner.',
    paragraphs: [S[13], S[14], S[15], S[16]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years serving Durham & North Carolina businesses' },
    { value: '0%', label: 'Of our clients have experienced a significant security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'Integrity, quality, and a',
    headlineAccent: 'commitment to your success.',
    paragraphs: [S[17], S[18], S[19], S[20]],
    image: {
      src: '/images/hero/local/durham nc 7.jpg',
      alt: 'Durham, North Carolina cityscape',
    },
  },
  security: {
    eyebrow: 'An Open-Book Approach',
    headlineLead: 'Complete transparency,',
    headlineAccent: 'nothing to hide.',
    paragraphs: [S[31], S[32], S[33]],
    image: {
      src: '/images/hero/local/durham nc 3.jpg',
      alt: 'Durham, North Carolina at dusk',
    },
  },
  citySlug: 'durham',
  bookingUtm: 'it-company-durham-bottom',
}
