// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —
// re-run the script if the live page content changes.
// Source: https://www.itsco.com/vcio-vcto-vciso-services/
// Generated: 2026-05-21T14:01:44.630Z

export const SOURCE_URL = "https://www.itsco.com/vcio-vcto-vciso-services/"

export const SOURCE_PARAGRAPHS = [
  /* 00 */ "Modern businesses face complex challenges—from cybersecurity threats to IT infrastructure modernization to regulatory compliance. ITSco’s virtual executive services provide the strategic IT leadership you need—without the cost of hiring in-house C-level technology executives.",
  /* 01 */ "Whether you’re planning a digital transformation, enhancing your security posture, or aligning IT investments with business goals, ITSco’s fractional technology leadership brings you expert, tested guidance to drive growth and lead with confidence.",
  /* 02 */ "Align IT with business objectives through strategic leadership:",
  /* 03 */ "Accelerate innovation and improve IT operations with senior-level technical guidance:",
  /* 04 */ "Mitigate cyber risks and ensure compliance with expert cybersecurity leadership:",
  /* 05 */ "Without experienced technology leadership, businesses often face:",
  /* 06 */ "Short-term decisions without long-term alignment cost time and money.",
  /* 07 */ "Inadequate protection exposes critical systems and sensitive data to attack.",
  /* 08 */ "Regulatory requirements go unmet, putting businesses at legal and financial risk.",
  /* 09 */ "Missed opportunities to streamline operations and gain competitive advantage.",
  /* 10 */ "Without proper guidance, businesses overspend or underutilize IT assets.",
  /* 11 */ "Trusted by businesses across industries for strategic IT leadership and results for over 25 years.",
  /* 12 */ "Our vCISO services ensure your IT environment is secure, compliant, and resilient.",
  /* 13 */ "We focus on growth, risk reduction, and ROI for every client.",
  /* 14 */ "From roadmapping to execution, our virtual CIOs, CTOs, and CISOs are there when you need them.",
  /* 15 */ "Trusted by businesses across industries for strategic IT leadership and results for over 25 years.",
  /* 16 */ "Whether you need help driving IT strategy, overseeing technology infrastructure, or an expert to guide security and compliance, ITSco’s proven executive IT services are designed to accelerate your growth and deliver results.",
] as const
