// Content for /it-support-charlotte/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'IT Support in Charlotte, NC | ITSco',
    description:
      'ITSco delivers IT support in Charlotte, NC — 24/7 monitoring, help desk, computer network support, and cybersecurity — with predictable pricing. Book a free consultation.',
    canonical: 'https://www.itsco.com/it-support-charlotte/',
  },
  hero: {
    eyebrow: 'IT Support · Charlotte, NC',
    headlineLead: 'Charlotte IT support that',
    headlineAccent: 'eliminates recurring issues.',
    body: S[0],
    utmSuffix: 'it-support-charlotte-hero',
  },
  heroImage: {
    src: '/images/hero/local/charlotte nc 6.jpg',
    alt: 'Charlotte, North Carolina cityscape',
  },
  capabilitiesHeading: {
    eyebrow: 'Full-Service IT Support',
    headlineLead: 'IT support services',
    headlineAccent: 'for Charlotte, NC businesses.',
  },
  capabilities: [
    { slug: 'custom-slas', title: 'Customized SLA Support', description: S[3] },
    { slug: 'remote-monitoring', title: '24/7 Monitoring', description: S[4] },
    { slug: 'cyber-security-management', title: 'Cybersecurity Support', description: S[5] },
    { slug: 'cloud-computing', title: 'Cloud Services', description: S[6] },
    { slug: 'help-desk-services', title: 'Dedicated Support Specialists', description: S[7] },
    { slug: 'it-project-management', title: 'Technology Procurement', description: S[8] },
    { slug: 'disaster-recovery', title: 'Disaster Recovery', description: S[9] },
    { slug: 'network-security-services', title: 'Computer Network Support', description: S[10] },
  ],
  positioning: {
    eyebrow: 'Small Business IT Support',
    headlineLead: 'The IT support company in Charlotte',
    headlineAccent: 'with 25 years of happy customers.',
    paragraphs: [S[2], S[12]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years supporting Charlotte & North Carolina businesses' },
    { value: '0%', label: 'Of our clients have experienced a serious security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'Computer tech support in Charlotte',
    headlineAccent: 'that supports your growth.',
    paragraphs: [S[16], S[17], S[18], S[19]],
    image: {
      src: '/images/hero/local/charlotte nc 3.jpg',
      alt: 'Charlotte, North Carolina at dusk',
    },
  },
  security: {
    eyebrow: 'Part of Your Community',
    headlineLead: 'Local IT support',
    headlineAccent: 'with a name and a face.',
    paragraphs: [S[25], S[26], S[27]],
    image: {
      src: '/images/hero/local/charlotte nc .jpg',
      alt: 'Downtown Charlotte, North Carolina skyline',
    },
  },
  citySlug: 'charlotte',
  bookingUtm: 'it-support-charlotte-bottom',
}
