// Content for /winston-salem-tech-it-support/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'Tech & IT Support in Winston-Salem, NC',
    description:
      'ITSco delivers tech and IT support in Winston-Salem, NC — 24/7 monitoring, help desk, cybersecurity, and cloud — with flexible, predictable pricing. Book a free consultation.',
    canonical: 'https://www.itsco.com/winston-salem-tech-it-support',
  },
  hero: {
    eyebrow: 'Tech & IT Support · Winston-Salem, NC',
    headlineLead: 'IT support in Winston-Salem that',
    headlineAccent: 'fixes the root cause.',
    body: S[0],
    utmSuffix: 'tech-support-winston-salem-hero',
  },
  heroImage: {
    src: '/images/supporting/services/annie-spratt-MChSQHxGZrQ-unsplash.jpg',
    alt: 'Tech support specialist supporting a Winston-Salem business',
  },
  capabilitiesHeading: {
    eyebrow: 'Full-Service Tech Support',
    headlineLead: 'IT support services',
    headlineAccent: 'for Winston-Salem, NC businesses.',
  },
  capabilities: [
    { slug: 'custom-slas', title: 'Flexible Response Packages', description: S[3] },
    { slug: 'remote-monitoring', title: '24/7 Monitoring & Alerts', description: S[4] },
    { slug: 'cyber-security-management', title: 'Cybersecurity Support', description: S[5] },
    { slug: 'cloud-computing', title: 'Cloud Services', description: S[6] },
    { slug: 'help-desk-services', title: 'IT Support Team', description: S[7] },
    { slug: 'network-security-services', title: 'Network Operations', description: S[8] },
    { slug: 'it-project-management', title: 'Technology Procurement', description: S[9] },
    { slug: 'disaster-recovery', title: 'Disaster Recovery', description: S[10] },
  ],
  positioning: {
    eyebrow: 'A Different Kind of IT Company',
    headlineLead: 'IT support in Winston-Salem',
    headlineAccent: 'that does things differently.',
    paragraphs: [S[2], S[11], S[12], S[13]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years providing Winston-Salem with IT support' },
    { value: '0%', label: 'Of our clients have experienced a major security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: "Don't react to IT problems —",
    headlineAccent: 'prevent them.',
    paragraphs: [S[17], S[18], S[19], S[25], S[26]],
    image: {
      src: '/images/hero/consulting/pexels-karola-g-8546816.jpg',
      alt: 'ITSco tech support team at work',
    },
  },
  security: {
    eyebrow: 'Predictable Pricing',
    headlineLead: 'Take the guesswork out',
    headlineAccent: 'of your IT budget.',
    paragraphs: [S[20], S[21], S[22], S[23]],
    image: {
      src: '/images/supporting/services/pexels-theo-decker-5946207.jpg',
      alt: 'Tech support monitoring for a Winston-Salem business',
    },
  },
  citySlug: 'winston-salem',
  bookingUtm: 'tech-support-winston-salem-bottom',
}
