// Content for /it-support-greensboro/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'IT Support in Greensboro, NC',
    description:
      'ITSco delivers IT support in Greensboro, NC — monitoring, help desk, cybersecurity, and cloud — at fair, predictable prices. Book a free consultation.',
    canonical: 'https://www.itsco.com/it-support-greensboro',
  },
  hero: {
    eyebrow: 'IT Support · Greensboro, NC',
    headlineLead: 'IT support in Greensboro that',
    headlineAccent: 'keeps your business running smoothly.',
    body: S[0],
    utmSuffix: 'it-support-greensboro-hero',
  },
  heroImage: {
    src: '/images/hero/local/greensboro nc 5.jpg',
    alt: 'Greensboro, North Carolina cityscape',
  },
  capabilitiesHeading: {
    eyebrow: 'Full-Service IT Support',
    headlineLead: 'IT support services',
    headlineAccent: 'for Greensboro, NC businesses.',
  },
  capabilities: [
    { slug: 'help-desk-services', title: 'IT Support Technicians', description: S[3] },
    { slug: 'remote-monitoring', title: 'Monitoring & Management', description: S[4] },
    { slug: 'cyber-security-management', title: 'Cybersecurity Support', description: S[5] },
    { slug: 'cloud-computing', title: 'Cloud Services', description: S[6] },
    { slug: 'custom-slas', title: 'IT Service Desk', description: S[7] },
    { slug: 'network-security-services', title: 'Network Support', description: S[8] },
    { slug: 'it-project-management', title: 'Technology Procurement', description: S[9] },
    { slug: 'disaster-recovery', title: 'Business Continuity', description: S[10] },
  ],
  positioning: {
    eyebrow: 'A Trusted IT Support Partner',
    headlineLead: 'A top Greensboro IT support company',
    headlineAccent: 'dedicated to your success.',
    paragraphs: [S[2], S[11], S[12]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years supporting Greensboro & the Triad' },
    { value: '0%', label: 'Of our clients have experienced a serious security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'The most reliable computer',
    headlineAccent: 'tech support in Greensboro.',
    paragraphs: [S[13], S[17], S[18], S[19]],
    image: {
      src: '/images/hero/local/greensboro 3.jpg',
      alt: 'Greensboro, North Carolina at dusk',
    },
  },
  security: {
    eyebrow: 'Cybersecurity Support',
    headlineLead: 'Are your systems vulnerable',
    headlineAccent: 'to cyber attack?',
    paragraphs: [S[20], S[21], S[22]],
    image: {
      src: '/images/hero/local/greensboro nc.jpg',
      alt: 'Downtown Greensboro, North Carolina',
    },
  },
  citySlug: 'greensboro',
  bookingUtm: 'it-support-greensboro-bottom',
}
