// Content for /managed-soc/
//
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).
// Hero framing is composed — the live Elementor page has no standalone hero
// paragraph. Capability descriptions and FAQs are verbatim.

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Managed SOC Services | 24/7 Security Operations Center',
    description:
      'ITSco Managed SOC — a 24/7 security operations center with analysts, SIEM, and rapid response, without the cost of building one in-house. Book a free consultation.',
    canonical: 'https://www.itsco.com/managed-soc',
  },
  serviceName: 'Managed SOC',
  parent: { name: 'Cybersecurity & Compliance', href: '/cybersecurity/' },
  hero: {
    eyebrow: 'Cybersecurity · Managed SOC',
    headlineLead: 'A security operations center',
    headlineAccent: 'watching 24/7.',
    body: "ITSco's Managed SOC gives you a round-the-clock security operations center — analysts, tooling, and rapid response — without the cost of building one in-house.",
    utmSuffix: 'managed-soc-hero',
  },
  heroImage: {
    src: '/images/hero/services/pexels-cookiecutter-17489157.jpg',
    alt: 'Server blades with blue indicator lighting in a data center',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Round-the-clock monitoring,',
    headlineAccent: 'real peace of mind.',
    paragraphs: [S[27], S[28]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years as a trusted IT services provider' },
    { value: '24/7', label: 'Security operations monitoring and response' },
  ],
  capabilitiesHeading: {
    eyebrow: 'Inside the SOC',
    headlineLead: 'Everything watching over',
    headlineAccent: 'your environment.',
  },
  capabilities: [
    { slug: 'soc-detection-response', title: '24/7 Detection and Response', description: S[5] },
    { slug: 'managed-siem', title: 'Managed SIEM', description: S[8] },
    { slug: 'intrusion-detection-system', title: 'Intrusion Detection System', description: S[12] },
    { slug: 'endpoint-detection-response', title: 'Endpoint Detection and Response', description: S[16] },
    { slug: 'vulnerability-scanning', title: 'Vulnerability Scanning', description: S[20] },
    { slug: 'behavioral-monitoring', title: 'Behavioral Monitoring', description: S[23] },
  ],
  outcomes: {
    eyebrow: 'Why ITSco',
    headlineLead: 'Proven SOC expertise,',
    headlineAccent: 'certified professionals.',
    paragraphs: [S[35], S[36], S[37]],
    image: {
      src: '/images/hero/services/pexels-divinetechygirl-1181354.jpg',
      alt: 'Security analyst working beside a monitored server room',
    },
  },
  related: {
    heading: 'Explore more cybersecurity services',
    links: [
      {
        slug: 'mdr-monitoring-and-response',
        label: 'MDR Monitoring & Response',
        href: '/mdr-monitoring-and-response/',
        description: 'Proactive threat hunting and rapid incident response, fully managed.',
      },
      {
        slug: 'siem-services',
        label: 'SIEM Services',
        href: '/siem-services/',
        description: 'Real-time log correlation and alerting across your whole environment.',
      },
      {
        slug: 'fully-managed-cybersecurity',
        label: 'Fully-Managed Cybersecurity',
        href: '/fully-managed-cybersecurity/',
        description: 'End-to-end cybersecurity, monitored and managed by ITSco.',
      },
    ],
  },
  faqHeading: {
    eyebrow: 'FAQ',
    headlineLead: 'Managed SOC,',
    headlineAccent: 'answered.',
  },
  faqs: [
    { question: S[40], answer: [S[41]] },
    { question: S[42], answer: [S[43]] },
    { question: S[44], answer: [S[45]] },
  ],
  bookingUtm: 'managed-soc-bottom',
}
