// Content for /managed-it-services-durham/
//
// Verbatim copy lives in ./_source.ts (auto-generated by
// scripts/sync-content.mjs). This file maps each slot to source indices.

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'Managed IT Services in Durham, NC | ITSco',
    description:
      'ITSco delivers managed IT services in Durham, NC — remote monitoring, cybersecurity, help desk, and cloud — with predictable pricing. Book a free consultation.',
    canonical: 'https://www.itsco.com/managed-it-services-durham/',
  },
  hero: {
    eyebrow: 'Managed IT Services · Durham, NC',
    headlineLead: 'Managed IT services in Durham that',
    headlineAccent: 'control costs and minimize downtime.',
    body: S[0],
    utmSuffix: 'managed-it-durham-hero',
  },
  heroImage: {
    src: '/images/hero/local/durham nc.jpg',
    alt: 'Downtown Durham, North Carolina skyline',
  },
  capabilitiesHeading: {
    eyebrow: 'Full-Suite Business IT Services',
    headlineLead: 'Full-suite managed IT services',
    headlineAccent: 'for Durham, NC businesses.',
  },
  capabilities: [
    { slug: 'remote-monitoring', title: 'Remote Monitoring', description: S[1] },
    { slug: 'cyber-security-management', title: 'Cyber Security Management', description: S[2] },
    { slug: 'help-desk-services', title: 'Help Desk Services', description: S[3] },
    { slug: 'advanced-engineering', title: 'Advanced Engineering Services', description: S[4] },
    { slug: 'custom-slas', title: 'Custom SLAs', description: S[5] },
    { slug: 'preventative-maintenance', title: 'Preventative Maintenance', description: S[6] },
    { slug: 'cloud-computing', title: 'Cloud Computing Services', description: S[7] },
    { slug: 'it-automation', title: 'IT Automation', description: S[8] },
    { slug: 'disaster-recovery', title: 'Disaster Recovery', description: S[9] },
  ],
  positioning: {
    eyebrow: 'Straightforward, Predictable Pricing',
    headlineLead: 'IT services in Durham with',
    headlineAccent: 'pricing you can plan around.',
    paragraphs: [S[10], S[21], S[22]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years serving Durham, RTP & North Carolina' },
    { value: '0%', label: 'Of our clients have experienced a serious security breach' },
  ],
  whyUs: {
    eyebrow: 'Experience the ITSco Difference',
    headlineLead: 'What separates ITSco from',
    headlineAccent: 'other IT companies in Durham.',
    paragraphs: [S[16], S[17], S[18], S[19], S[20]],
    image: {
      src: '/images/hero/local/durham nc 2.jpg',
      alt: 'Durham, North Carolina cityscape',
    },
  },
  security: {
    eyebrow: 'Cybersecurity in Durham',
    headlineLead: 'Durham businesses face',
    headlineAccent: 'an evolving threat landscape.',
    paragraphs: [S[23], S[24]],
    image: {
      src: '/images/hero/local/durham nc 3.jpg',
      alt: 'Durham, North Carolina at dusk',
    },
  },
  related: {
    heading: 'Our other IT services in Durham',
    links: [
      {
        slug: 'remote-it-support',
        label: 'IT Support in Durham',
        href: '/it-support-durham/',
        description: 'Responsive remote and on-site IT support for Durham businesses.',
      },
      {
        slug: 'it-management-consulting',
        label: 'IT Consulting in Durham',
        href: '/durham-it-consulting/',
        description: 'Strategic technology guidance to align IT with your business goals.',
      },
      {
        slug: 'managed-it-services',
        label: 'IT Company in Durham',
        href: '/it-company-durham/',
        description: 'A locally based IT partner committed to Durham for the long run.',
      },
    ],
  },
  faqHeading: {
    eyebrow: 'FAQ',
    headlineLead: 'Durham managed IT services,',
    headlineAccent: 'answered.',
  },
  faqs: [
    {
      question: 'How does managed IT services enhance cybersecurity for my business?',
      answer: [S[26], S[27], S[28]],
    },
    {
      question: "What makes ITSco's approach to IT management unique compared to other providers?",
      answer: [S[29], S[30]],
    },
    {
      question: 'Can managed IT services help in reducing overall IT costs?',
      answer: [S[31], S[32]],
    },
    {
      question: 'How does ITSco ensure quick resolution of IT issues?',
      answer: [S[33], S[34]],
    },
    {
      question: 'In what ways do managed IT services align with my business goals?',
      answer: [S[35], S[36], S[37]],
    },
  ],
  bookingUtm: 'managed-it-durham-bottom',
}
