// Content for /durham-it-consulting/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'IT Consulting in Durham, NC',
    description:
      'ITSco delivers IT consulting in Durham, NC — IT strategy, vCIO/vCTO guidance, cybersecurity, and cloud — that supports your business plans. Book a free consultation.',
    canonical: 'https://www.itsco.com/durham-it-consulting',
  },
  hero: {
    eyebrow: 'IT Consulting · Durham, NC',
    headlineLead: 'IT consulting in Durham that',
    headlineAccent: 'supports your business plans.',
    body: S[0],
    utmSuffix: 'it-consulting-durham-hero',
  },
  heroImage: {
    src: '/images/hero/consulting/creatopy-E3LsanLgkLM-unsplash.jpg',
    alt: 'IT consultants planning strategy for a Durham business',
  },
  capabilitiesHeading: {
    eyebrow: 'Business-Focused IT Consulting',
    headlineLead: 'IT consulting services',
    headlineAccent: 'for Durham, NC businesses.',
  },
  capabilities: [
    { slug: 'it-project-management', title: 'IT Strategy & Roadmaps', description: S[2] },
    { slug: 'strategic-security-consulting', title: 'Strategic Planning', description: S[3] },
    { slug: 'network-security-services', title: 'Network Design Audits', description: S[4] },
    { slug: 'cyber-security-management', title: 'Security Strategy', description: S[5] },
    { slug: 'managed-it-services', title: 'IT Investment Planning', description: S[6] },
    { slug: 'risk-management', title: 'Security Assessments', description: S[7] },
    { slug: 'disaster-recovery', title: 'Compliance & Continuity', description: S[8] },
    { slug: 'it-automation', title: 'IT Automation', description: S[9] },
    { slug: 'cloud-computing', title: 'Cloud Migration', description: S[10] },
  ],
  positioning: {
    eyebrow: 'A One-Stop IT Shop',
    headlineLead: 'IT consulting in Durham',
    headlineAccent: 'that spends smarter.',
    paragraphs: [S[11], S[12], S[28], S[29]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years of IT consulting in Durham & North Carolina' },
    { value: '0%', label: 'Of our clients have experienced a serious cybersecurity breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'Senior-level IT consulting',
    headlineAccent: 'without the big-company price tag.',
    paragraphs: [S[16], S[17], S[18], S[19], S[21]],
    image: {
      src: '/images/hero/consulting/pexels-gustavo-fring-6285127.jpg',
      alt: 'ITSco IT consultants in a working session',
    },
  },
  security: {
    eyebrow: 'Cybersecurity Expertise',
    headlineLead: 'IT consulting backed by a',
    headlineAccent: 'CISSP-certified security team.',
    paragraphs: [S[26], S[27]],
    image: {
      src: '/images/hero/consulting/pexels-ketut-subiyanto-4963438.jpg',
      alt: 'IT security consultant reviewing systems',
    },
  },
  citySlug: 'durham',
  bookingUtm: 'it-consulting-durham-bottom',
}
