// Content for /security-event-remediation-ip-protection/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Security Event Remediation & IP Protection Services | ITSco',
    description:
      'ITSco security event remediation and IP protection — expert-led threat response, vulnerability remediation, and intellectual property security. Book a free consultation.',
    canonical: 'https://www.itsco.com/security-event-remediation-ip-protection/',
  },
  serviceName: 'Security Event Remediation & IP Protection',
  hero: {
    eyebrow: 'Engineering · Security Remediation',
    headlineLead: 'Fast remediation when',
    headlineAccent: 'a threat gets through.',
    body: S[0],
    utmSuffix: 'security-event-remediation-hero',
  },
  heroImage: {
    src: '/images/hero/services/pexels-cookiecutter-17489157.jpg',
    alt: 'Security infrastructure under active remediation',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Comprehensive remediation and',
    headlineAccent: 'IP protection.',
    paragraphs: [S[1], S[2]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years of systems and network security expertise' },
    { value: '24/7', label: 'Threat response and remediation coverage' },
  ],
  capabilitiesHeading: {
    eyebrow: 'What We Deliver',
    headlineLead: 'Contain the threat,',
    headlineAccent: 'protect what matters.',
  },
  capabilities: [
    {
      slug: 'ser-incident-response',
      title: 'Incident Response & Threat Containment',
      description: S[3],
    },
    {
      slug: 'ser-vulnerability-remediation',
      title: 'Vulnerability Identification & Risk Remediation',
      description: S[4],
    },
    { slug: 'ser-malware-recovery', title: 'Malware & Ransomware Recovery', description: S[5] },
    {
      slug: 'ser-ip-protection',
      title: 'IP Protection & Digital Asset Security',
      description: S[6],
    },
    {
      slug: 'ser-hardening',
      title: 'Network & Endpoint Security Hardening',
      description: S[7],
    },
    {
      slug: 'ser-policy-compliance',
      title: 'Security Policy Review & Compliance Alignment',
      description: S[8],
    },
  ],
  outcomes: {
    eyebrow: 'The Risk',
    headlineLead: 'The risks of inadequate',
    headlineAccent: 'security practices.',
    paragraphs: [],
    tone: 'risk',
    bullets: [S[10], S[11], S[12], S[13], S[14]],
    image: {
      src: '/images/hero/blog/claudio-schwarz-08dyHxddcKc-unsplash.jpg',
      alt: 'Security team remediating an incident',
    },
  },
  related: {
    heading: 'Explore more security services',
    links: [
      {
        slug: 'managed-soc',
        label: 'Managed SOC',
        href: '/managed-soc/',
        description: 'A 24/7 security operations center watching your environment.',
      },
      {
        slug: 'mdr-monitoring-and-response',
        label: 'MDR Monitoring & Response',
        href: '/mdr-monitoring-and-response/',
        description: 'Proactive threat hunting and rapid incident response, fully managed.',
      },
      {
        slug: 'fully-managed-cybersecurity',
        label: 'Fully-Managed Cybersecurity',
        href: '/fully-managed-cybersecurity/',
        description: 'End-to-end cybersecurity, monitored and managed by ITSco.',
      },
    ],
  },
  bookingUtm: 'security-event-remediation-bottom',
}
