// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —
// re-run the script if the live page content changes.
// Source: https://www.itsco.com/it-roi-assessment/
// Generated: 2026-05-21T14:01:47.849Z

export const SOURCE_URL = "https://www.itsco.com/it-roi-assessment"

export const SOURCE_PARAGRAPHS = [
  /* 00 */ "Investment in IT should be an enabler of business growth and not simply a drain on resources. Yet, many organizations struggle to understand where their IT budget is going, whether their systems truly serve their goals, or how to improve efficiency—and their bottom line.",
  /* 01 */ "ITSco’s IT ROI assessments are designed to reduce waste, uncover opportunities, and help your technology investments deliver on their promise of greater functionality and efficiency.",
  /* 02 */ "We can provide an experienced, unbiased point-of-view that will help your team cut through the distractions and confusion that often surround IT spending and create a clearer picture of where you are and where you need to be.",
  /* 03 */ "No guesswork. No jargon. Just practical analysis and expert guidance to help you get more value from every IT dollar.",
  /* 04 */ "We examine your current environment—hardware, software, network systems, cloud services, security tools—to understand what’s working, what’s not, and how systems can be optimized.",
  /* 05 */ "By comparing your current state with industry best practices and your business goals, we identify inefficiencies, redundancies, and vulnerabilities that may be draining productivity or creating unnecessary risk.",
  /* 06 */ "We don’t just point out the problems—we provide a prioritized roadmap for improvement, outlining effective ways to modernize systems, improve performance, and reduce downtime.",
  /* 07 */ "Our team evaluates software licensing, service contracts, and vendor relationships to uncover opportunities to consolidate, renegotiate, or eliminate wasteful spending.",
  /* 08 */ "We work with your team to align technology decisions with business priorities—ensuring your future IT investments are proactive, scalable, and financially sound.",
  /* 09 */ "It’s easy for IT costs to spiral out of control—especially when infrastructure grows organically without a strategy. Without a clear view into what’s working (and what’s not), businesses often face:",
  /* 10 */ "Underutilized or outdated technology drains performance and value.",
  /* 11 */ "Overlapping tools and licenses waste money and impede standardization.",
  /* 12 */ "Security or compliance gaps increase business risk and could leave you subject to fines.",
  /* 13 */ "Lack of visibility into what IT really costs—or delivers—hinders future planning and decision-making.",
  /* 14 */ "No certainty on the return your business is seeing from major investments in IT infrastructure.",
  /* 15 */ "We’ve helped organizations of all sizes improve their IT efficiency, performance, and scalability for over 25 years.",
  /* 16 */ "ROI only matters if your systems are secure, so we factor risk & compliance into every recommendation.",
  /* 17 */ "Our assessments focus on value, not just technology—ensuring IT investments support strategic goals.",
  /* 18 */ "We provide objective recommendations, not sales pitches.",
  /* 19 */ "We translate complex infrastructure data into clear insights and prioritized next steps.",
  /* 20 */ "If you’re unsure why your IT systems cost what they do—or how much value they’re delivering— ITSco’s ROI Assessment is the perfect place to start. We’ll provide the insight you need to understand and plan your IT spending on a deeper level.",
] as const
