// Content for /it-roi-assessment/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'IT ROI Assessment Services | ITSco',
    description:
      'ITSco IT ROI assessment — reduce waste, uncover opportunities, and get more value from every IT dollar with an unbiased expert review. Book a free consultation.',
    canonical: 'https://www.itsco.com/it-roi-assessment/',
  },
  serviceName: 'IT ROI Assessment',
  parent: { name: 'IT Strategy & Consulting', href: '/it-management-consulting/' },
  hero: {
    eyebrow: 'Strategy · IT ROI',
    headlineLead: 'Maximize your IT investments',
    headlineAccent: 'with an ROI assessment.',
    body: S[0],
    utmSuffix: 'it-roi-assessment-hero',
  },
  heroImage: {
    src: '/images/hero/consulting/path-digital-tR0jvlsmCuQ-unsplash.jpg',
    alt: 'IT ROI analysis dashboard',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Inform your IT decision-making',
    headlineAccent: 'with ITSco.',
    paragraphs: [S[1], S[2], S[3]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years improving IT efficiency and value' },
    { value: '60%', label: 'Of our clients have stayed with us for 5+ years' },
  ],
  capabilitiesHeading: {
    eyebrow: 'What the Assessment Covers',
    headlineLead: 'A clear picture of',
    headlineAccent: 'your IT spend.',
  },
  capabilities: [
    { slug: 'roi-infrastructure-audit', title: 'IT Infrastructure Audit', description: S[4] },
    { slug: 'roi-gap-analysis', title: 'Gap Analysis & Risk Identification', description: S[5] },
    {
      slug: 'roi-optimization',
      title: 'Technology Optimization Recommendations',
      description: S[6],
    },
    { slug: 'roi-licensing-review', title: 'Licensing & Vendor Cost Review', description: S[7] },
    {
      slug: 'roi-strategy-alignment',
      title: 'IT Investment Strategy Alignment',
      description: S[8],
    },
  ],
  outcomes: {
    eyebrow: 'The Risk',
    headlineLead: 'Why businesses need',
    headlineAccent: 'an IT ROI assessment.',
    paragraphs: [],
    tone: 'risk',
    bullets: [S[10], S[11], S[12], S[13], S[14]],
    image: {
      src: '/images/supporting/consulting/lukas-blazek-mcSDtbWXUZU-unsplash.jpg',
      alt: 'Analyzing IT cost and return data',
    },
  },
  related: {
    heading: 'Explore more strategy & consulting services',
    links: [
      {
        slug: 'it-assessments-strategies',
        label: 'IT Assessments & Strategies',
        href: '/it-assessments-strategies/',
        description: 'In-depth evaluations of infrastructure, security, and compliance.',
      },
      {
        slug: 'maximize-roi-with-managed-it-services',
        label: 'The ROI of Managed IT',
        href: '/maximize-roi-with-managed-it-services/',
        description: 'How ITSco measures and proves the return on managed IT, every quarter.',
      },
      {
        slug: 'it-management-consulting',
        label: 'Strategy & Consulting Overview',
        href: '/it-management-consulting/',
        description: 'The full ITSco strategy program — leadership, roadmaps, and assessments.',
      },
    ],
  },
  bookingUtm: 'it-roi-assessment-bottom',
}
