// Content for /cloud-migration/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).
// Hero framing is composed — the live Elementor page has no standalone hero
// paragraph. Capability descriptions and FAQs are verbatim.

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Cloud Migration Services',
    description:
      'ITSco cloud migration — a planned, secure, low-disruption move to the cloud that lands right the first time. Book a free consultation.',
    canonical: 'https://www.itsco.com/cloud-migration',
  },
  serviceName: 'Cloud Migration',
  parent: { name: 'Cloud Services', href: '/cloud-services/' },
  hero: {
    eyebrow: 'Cloud · Migration',
    headlineLead: 'Cloud migration',
    headlineAccent: 'without the disruption.',
    body: 'Moving to the cloud is high-stakes — done wrong it means downtime, blown budgets, and data risk. ITSco plans and runs your migration so it lands smoothly the first time.',
    utmSuffix: 'cloud-migration-hero',
  },
  heroImage: {
    src: '/images/hero/services/pexels-brett-sayles-5408005.jpg',
    alt: 'Data center infrastructure for a cloud migration',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Seamless digital transformation,',
    headlineAccent: 'no hassles.',
    paragraphs: [S[29], S[30]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years as a trusted IT services provider' },
    { value: '60%', label: 'Of our clients have stayed with us for 5+ years' },
  ],
  capabilitiesHeading: {
    eyebrow: 'Our Cloud Migration Services',
    headlineLead: 'A migration built to',
    headlineAccent: 'land right.',
  },
  capabilities: [
    { slug: 'talent-gap-solutions', title: 'Talent Gap Solutions', description: S[5] },
    { slug: 'error-free-migration', title: 'Error-Free Migration', description: S[9] },
    { slug: 'outcome-driven-strategies', title: 'Outcome-Driven Strategies', description: S[13] },
    { slug: 'application-modernization', title: 'Application Modernization', description: S[17] },
    { slug: 'migration-governance-compliance', title: 'Governance and Compliance', description: S[21] },
    { slug: 'cost-effective-migration', title: 'Cost-Effective Migration', description: S[24] },
  ],
  outcomes: {
    eyebrow: 'Beyond the Migration',
    headlineLead: 'Empower your team with',
    headlineAccent: 'cloud training and support.',
    paragraphs: [S[37], S[38], S[39]],
    image: {
      src: '/images/hero/services/pexels-cookiecutter-17489157.jpg',
      alt: 'Cloud infrastructure ready for migration',
    },
  },
  related: {
    heading: 'Explore more cloud services',
    links: [
      {
        slug: 'managed-cloud-services',
        label: 'Managed Cloud Services',
        href: '/managed-cloud-services/',
        description: 'Ongoing management, monitoring, and optimization of your cloud environment.',
      },
      {
        slug: 'microsoft-azure-services',
        label: 'Microsoft Azure Services',
        href: '/microsoft-azure-services/',
        description: 'Migration, management, and optimization on Microsoft Azure.',
      },
      {
        slug: 'cloud-services',
        label: 'Cloud Services Overview',
        href: '/cloud-services/',
        description: 'The full ITSco cloud program — migration, hosting, management, and more.',
      },
    ],
  },
  faqHeading: {
    eyebrow: 'FAQ',
    headlineLead: 'Cloud migration,',
    headlineAccent: 'answered.',
  },
  faqs: [
    { question: S[42], answer: [S[43]] },
    { question: S[44], answer: [S[45]] },
    { question: S[46], answer: [S[47]] },
    { question: S[48], answer: [S[49]] },
    { question: S[50], answer: [S[51]] },
  ],
  bookingUtm: 'cloud-migration-bottom',
}
