// Content for /email-security/
//
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).
// Capability descriptions and FAQs are verbatim.

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Email Security Services | Anti-Phishing & Malware Protection | ITSco',
    description:
      'ITSco email security blocks phishing, malware, and account takeover before they reach your people. 24/7 monitoring and rapid response. Book a free consultation.',
    canonical: 'https://www.itsco.com/email-security/',
  },
  serviceName: 'Email Security',
  hero: {
    eyebrow: 'Cybersecurity · Email Security',
    headlineLead: 'Email security that stops',
    headlineAccent: 'the attack at the inbox.',
    body: S[37],
    utmSuffix: 'email-security-hero',
  },
  heroImage: {
    src: '/images/hero/blog/claudio-schwarz-08dyHxddcKc-unsplash.jpg',
    alt: 'Close-up of hands at a keyboard, email security concept',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Secure your business',
    headlineAccent: 'from email threats.',
    paragraphs: [S[30]],
  },
  stats: [
    { value: '90%', label: 'Of cyber attacks originate from phishing emails (CISA)' },
    { value: '99%', label: 'Of issues resolved in a single interaction' },
    { value: '24/7', label: 'Email security monitoring and helpdesk support' },
  ],
  capabilitiesHeading: {
    eyebrow: 'Powerful Email Security Features',
    headlineLead: 'Layered protection for',
    headlineAccent: 'your inbox.',
  },
  capabilities: [
    { slug: 'anti-phishing', title: 'Anti-Phishing Protection', description: S[4] },
    { slug: 'malware-blocking', title: 'Malware Blocking', description: S[8] },
    { slug: 'account-takeover-prevention', title: 'Account Takeover Prevention', description: S[12] },
    { slug: 'email-monitoring', title: '24/7 Security Monitoring', description: S[16] },
    { slug: 'email-incident-response', title: 'Incident Response', description: S[21] },
    { slug: 'security-awareness-training', title: 'Security Awareness Training', description: S[25] },
  ],
  outcomes: {
    eyebrow: 'The Payoff',
    headlineLead: 'Stop email threats before',
    headlineAccent: 'they reach your team.',
    paragraphs: [S[31], S[32], S[33]],
    image: {
      src: '/images/hero/blog/pexels-edmond-dantes-8068258.jpg',
      alt: 'Laptop screen showing security software',
    },
  },
  related: {
    heading: 'Explore more cybersecurity services',
    links: [
      {
        slug: 'fully-managed-cybersecurity',
        label: 'Fully-Managed Cybersecurity',
        href: '/fully-managed-cybersecurity/',
        description: 'End-to-end cybersecurity, monitored and managed by ITSco.',
      },
      {
        slug: 'cyber-risk-assessment',
        label: 'Cyber Risk Assessment',
        href: '/cyber-risk-assessment/',
        description: 'Know exactly where your exposure is — and what to fix first.',
      },
      {
        slug: 'managed-soc',
        label: 'Managed SOC',
        href: '/managed-soc/',
        description: 'A 24/7 security operations center watching your environment.',
      },
    ],
  },
  faqHeading: {
    eyebrow: 'FAQ',
    headlineLead: 'Email security,',
    headlineAccent: 'answered.',
  },
  faqs: [
    { question: S[43], answer: [S[44], S[45], S[46]] },
    { question: S[47], answer: [S[48], S[49], S[50]] },
    { question: S[51], answer: [S[52], S[53], S[54]] },
  ],
  bookingUtm: 'email-security-bottom',
}
