// Content for /charlotte-it-consulting/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'IT Consulting Charlotte | IT Consulting in Charlotte, NC',
    description:
      'IT consulting Charlotte business leaders trust — ITSco delivers IT strategy, cloud, cybersecurity, and network solutions that turn business goals into reality. Book a free consultation.',
    canonical: 'https://www.itsco.com/charlotte-it-consulting/',
  },
  hero: {
    eyebrow: 'IT Consulting · Charlotte, NC',
    headlineLead: 'IT consulting in Charlotte that',
    headlineAccent: 'turns goals into reality.',
    body: S[0],
    utmSuffix: 'it-consulting-charlotte-hero',
  },
  heroImage: {
    src: '/images/hero/consulting/linkedin-sales-solutions-hrhjn6ZTgrM-unsplash.jpg',
    alt: 'IT consultants planning strategy for a Charlotte business',
  },
  capabilitiesHeading: {
    eyebrow: 'Business-Focused IT Consulting',
    headlineLead: 'IT consulting services',
    headlineAccent: 'for Charlotte, NC businesses.',
  },
  capabilities: [
    { slug: 'it-project-management', title: 'IT Strategy & Vision', description: S[2] },
    { slug: 'managed-it-services', title: 'Full-Stack IT Consulting', description: S[3] },
    { slug: 'advanced-engineering', title: 'Scalability Planning', description: S[4] },
    { slug: 'cloud-computing', title: 'Cloud & Digital Transformation', description: S[5] },
    { slug: 'cyber-security-management', title: 'Cybersecurity Strategy', description: S[6] },
    { slug: 'disaster-recovery', title: 'Disaster Recovery Planning', description: S[7] },
    { slug: 'network-security-services', title: 'Network Support', description: S[8] },
    { slug: 'strategic-security-consulting', title: 'Strategic Planning', description: S[9] },
    { slug: 'risk-management', title: 'Root-Cause Problem Solving', description: S[10] },
  ],
  positioning: {
    eyebrow: 'A Pioneer in Charlotte IT Consulting',
    headlineLead: 'IT consulting in Charlotte,',
    headlineAccent: 'refined over 25 years.',
    paragraphs: [S[12], S[13], S[14]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years of IT consulting in the Charlotte area' },
    { value: '0%', label: 'Of our clients have experienced a serious data breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'Choose the IT consulting company',
    headlineAccent: 'whose clients stay for the long haul.',
    paragraphs: [S[18], S[19], S[20], S[25], S[26]],
    image: {
      src: '/images/hero/consulting/charlesdeluvio-Lks7vei-eAg-unsplash.jpg',
      alt: 'ITSco IT consultants collaborating',
    },
  },
  security: {
    eyebrow: 'Cybersecurity Strategy',
    headlineLead: 'No company can afford',
    headlineAccent: 'to ignore cyber security.',
    paragraphs: [S[22], S[23], S[24]],
    image: {
      src: '/images/hero/consulting/pexels-karola-g-8546816.jpg',
      alt: 'IT security consultant reviewing systems',
    },
  },
  citySlug: 'charlotte',
  bookingUtm: 'it-consulting-charlotte-bottom',
}
