// Content for /cybersecurity-consulting-services/
//
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).
// /cyber-security-consulting/ 301-redirects here.

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Cybersecurity Consulting Services | vCISO & Strategy | ITSco',
    description:
      'ITSco cybersecurity consulting — strategic guidance, vCISO leadership, and proactive defense to build a resilient security program. Book a free consultation.',
    canonical: 'https://www.itsco.com/cybersecurity-consulting-services/',
  },
  serviceName: 'Cybersecurity Consulting',
  hero: {
    eyebrow: 'Cybersecurity · Consulting',
    headlineLead: 'Cybersecurity consulting',
    headlineAccent: 'that builds real resilience.',
    body: S[0],
    utmSuffix: 'cybersecurity-consulting-hero',
  },
  heroImage: {
    src: '/images/supporting/consulting/mario-gogh-VBLHICVh-lI-unsplash.jpg',
    alt: 'ITSco security advisors planning a cybersecurity strategy',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Strategic, scalable',
    headlineAccent: 'cybersecurity expertise.',
    paragraphs: [S[1], S[2]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years in IT services and security' },
    { value: '60%', label: 'Of our clients have stayed with us for 5+ years' },
  ],
  capabilitiesHeading: {
    eyebrow: 'How We Help',
    headlineLead: 'Strengthen security and',
    headlineAccent: 'reduce risk.',
  },
  capabilities: [
    { slug: 'managed-detection-response', title: 'Managed Detection & Response', description: S[3] },
    { slug: 'vulnerability-management', title: 'Vulnerability Management', description: S[4] },
    { slug: 'firewall-management', title: 'Firewall Management', description: S[5] },
    { slug: 'web-app-testing', title: 'Web Application Testing', description: S[6] },
    { slug: 'awareness-training', title: 'Security Awareness Training', description: S[7] },
    { slug: 'vciso-services', title: 'vCISO Services', description: S[8] },
  ],
  outcomes: {
    eyebrow: 'The Risk',
    headlineLead: 'The risk of',
    headlineAccent: 'going it alone.',
    paragraphs: [S[9]],
    bullets: [S[10], S[11], S[12], S[13], S[14]],
    image: {
      src: '/images/hero/consulting/pexels-divinetechygirl-1181335.jpg',
      alt: 'Security consultant reviewing a client environment',
    },
  },
  related: {
    heading: 'Explore more cybersecurity services',
    links: [
      {
        slug: 'fully-managed-cybersecurity',
        label: 'Fully-Managed Cybersecurity',
        href: '/fully-managed-cybersecurity/',
        description: 'End-to-end cybersecurity, monitored and managed by ITSco.',
      },
      {
        slug: 'security-audits-compliance',
        label: 'Security Audits & Compliance',
        href: '/security-audits-compliance/',
        description: 'In-depth audits and remediation roadmaps that keep you compliant.',
      },
      {
        slug: 'managed-soc',
        label: 'Managed SOC',
        href: '/managed-soc/',
        description: 'A 24/7 security operations center watching your environment.',
      },
    ],
  },
  bookingUtm: 'cybersecurity-consulting-bottom',
}
