// Content for /raleigh-it-helpdesk/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'IT Helpdesk in Raleigh, NC',
    description:
      'ITSco delivers IT helpdesk and service desk support in Raleigh, NC — real-time monitoring, remote and on-site troubleshooting, and sub-hour response. Book a free consultation.',
    canonical: 'https://www.itsco.com/raleigh-it-helpdesk/',
  },
  heroVariant: 'fullbleed',
  officeLocation: 'raleigh',
  hero: {
    eyebrow: 'IT Helpdesk · Raleigh, NC',
    headlineLead: 'IT helpdesk support in Raleigh that',
    headlineAccent: 'resolves issues fast.',
    body: S[0],
    utmSuffix: 'it-helpdesk-raleigh-hero',
  },
  heroImage: {
    src: '/images/supporting/services/pexels-mart-production-7255723.jpg',
    alt: 'IT helpdesk specialist supporting a Raleigh business',
  },
  capabilitiesHeading: {
    eyebrow: 'HelpDesk & Service Desk',
    headlineLead: 'IT helpdesk services',
    headlineAccent: 'for Raleigh, NC businesses.',
  },
  capabilities: [
    { slug: 'remote-monitoring', title: 'Proactive Monitoring', description: S[2] },
    { slug: 'help-desk-services', title: 'Remote Support', description: S[3] },
    { slug: 'advanced-engineering', title: 'Senior Engineer Escalation', description: S[4] },
    { slug: 'cyber-security-management', title: 'Cybersecurity Support', description: S[5] },
    { slug: 'custom-slas', title: 'On-Site Support', description: S[6] },
    { slug: 'it-automation', title: 'Software & License Management', description: S[7] },
    { slug: 'disaster-recovery', title: 'Backup & Disaster Recovery', description: S[8] },
  ],
  positioning: {
    eyebrow: 'Responsive, Expert-Led Support',
    headlineLead: 'IT helpdesk support that keeps',
    headlineAccent: 'your business productive.',
    paragraphs: [S[19], S[20]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years of IT support experience' },
    { value: '0%', label: 'Of our clients have experienced a serious security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'A helpdesk that scales',
    headlineAccent: 'as your business grows.',
    paragraphs: [S[21], S[22], S[23], S[24], S[25]],
    image: {
      src: '/images/hero/local/raleigh.jpg',
      alt: 'Downtown Raleigh, North Carolina skyline',
    },
  },
  security: {
    eyebrow: 'Exceptional Service Quality',
    headlineLead: 'The gold standard in',
    headlineAccent: 'helpdesk support.',
    paragraphs: [S[27], S[28], S[29]],
    image: {
      src: '/images/hero/local/raleigh2.jpg',
      alt: 'Raleigh, North Carolina cityscape',
    },
  },
  citySlug: 'raleigh',
  bookingUtm: 'it-helpdesk-raleigh-bottom',
}
