// Content for /server-admin-and-support-services/
//
// Verbatim copy lives in ./_source.ts (auto-generated by
// scripts/sync-content.mjs). This file maps each slot to source indices.

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Server Administration & Support Services',
    description:
      'ITSco server administration and support — end-to-end server management, 24/7 monitoring, and certified expert support that keeps you running. Book a free consultation.',
    canonical: 'https://www.itsco.com/server-admin-and-support-services',
  },
  serviceName: 'Server Administration & Support',
  parent: { name: 'Managed IT Services', href: '/managed-it-services/' },
  hero: {
    eyebrow: 'Managed IT · Server Services',
    headlineLead: 'Server administration and support,',
    headlineAccent: 'handled by experts.',
    body: `${S[28]} ${S[29]}`,
    utmSuffix: 'server-admin-support-hero',
  },
  heroImage: {
    src: '/images/hero/services/pexels-fauxels-3182801.jpg',
    alt: 'ITSco server administrators collaborating on infrastructure support',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Unlock your server potential with',
    headlineAccent: "ITSco's expert support.",
    paragraphs: [S[30], S[31]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have encountered a substantial security breach' },
    { value: '25+', label: 'Years as a trusted IT services provider' },
    { value: '60%', label: 'Of our clients have stayed with us for over five years' },
  ],
  capabilitiesHeading: {
    eyebrow: 'End-to-End Server Administration',
    headlineLead: 'Complete server support,',
    headlineAccent: 'from setup to security.',
  },
  capabilities: [
    {
      slug: 'hardware-software-support',
      title: 'Complete Hardware and Software Support',
      description: S[8],
    },
    { slug: 'end-user-assistance', title: 'End-User Assistance', description: S[11] },
    { slug: 'server-security', title: 'Server Security', description: S[14] },
    {
      slug: 'continuous-server-monitoring',
      title: '24/7 Monitoring and Support',
      description: S[18],
    },
    { slug: 'server-deployments', title: 'Server Deployments', description: S[21] },
    { slug: 'cloud-support', title: 'Cloud Support', description: S[25] },
  ],
  outcomes: {
    eyebrow: 'Versatile Server Support',
    headlineLead: 'Server support solutions',
    headlineAccent: 'built around your environment.',
    paragraphs: [S[37], S[38], S[39]],
    image: {
      src: '/images/supporting/services/berkeley-communications-WEDDt-u3q3o-unsplash.jpg',
      alt: 'IT engineer reviewing server administration dashboards',
    },
  },
  related: {
    heading: 'Explore more managed IT services',
    links: [
      {
        slug: 'server-monitoring-and-maintenance',
        label: 'Server Monitoring & Maintenance',
        href: '/server-monitoring-and-maintenance/',
        description: '24/7 monitoring, patching, and tuning that keeps critical servers healthy.',
      },
      {
        slug: 'managed-network-services',
        label: 'Managed Network Services',
        href: '/managed-network-services/',
        description: 'Proactive monitoring, design, and support across your entire network.',
      },
      {
        slug: 'backup-disaster-recovery',
        label: 'Backup & Disaster Recovery',
        href: '/backup-disaster-recovery/',
        description: 'Automated backups and tested recovery plans that protect against the worst case.',
      },
    ],
  },
  faqHeading: {
    eyebrow: 'FAQ',
    headlineLead: 'Server admin and support,',
    headlineAccent: 'answered.',
  },
  faqs: [
    { question: S[42], answer: [S[43], S[44], S[45]] },
    { question: S[46], answer: [S[47], S[48], S[49]] },
    { question: S[50], answer: [S[51], S[52]] },
    { question: S[53], answer: [S[54], S[55], S[56]] },
    { question: S[57], answer: [S[58], S[59], S[60]] },
  ],
  bookingUtm: 'server-admin-support-bottom',
}
