// Content for /raleigh-cyber-security-services/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'Cyber Security Services in Raleigh, NC | Computer Security Company',
    description:
      'ITSco is the Raleigh computer security company businesses trust — SIEM, risk management, security architecture, compliance, and cloud security from a team that has never had a client breach. Book a free consultation.',
    canonical: 'https://www.itsco.com/raleigh-cyber-security-services',
  },
  officeLocation: 'raleigh',
  hero: {
    eyebrow: 'Cyber Security Services · Raleigh, NC',
    headlineLead: 'Cyber security services in Raleigh that',
    headlineAccent: 'stop cybercriminals in their tracks.',
    body: S[0],
    utmSuffix: 'cyber-raleigh-hero',
  },
  heroImage: {
    src: '/images/hero/local/raleigh3.jpg',
    alt: 'Raleigh, North Carolina at dusk',
  },
  capabilitiesHeading: {
    eyebrow: 'Organization-Wide Protection',
    headlineLead: 'Cyber security services',
    headlineAccent: 'for Raleigh, NC businesses.',
  },
  capabilities: [
    { slug: 'cyber-threat-solutions', title: 'Turnkey Cyber Threat Solutions', description: S[3] },
    { slug: 'siem-services', title: 'Security Information & Event Management', description: S[4] },
    { slug: 'risk-management', title: 'Risk Management', description: S[5] },
    { slug: 'security-architecture', title: 'Security Architecture Design', description: S[6] },
    { slug: 'security-awareness-training', title: 'Security Awareness Training', description: S[7] },
    { slug: 'security-audits-compliance', title: 'Regulatory Compliance Assessments', description: S[8] },
    { slug: 'cloud-cybersecurity', title: 'Cloud Security Services', description: S[9] },
    { slug: 'strategic-security-consulting', title: 'Strategic Consulting', description: S[10] },
  ],
  positioning: {
    eyebrow: 'A Leader Among Raleigh Cyber Security Companies',
    headlineLead: 'A cybersecurity company',
    headlineAccent: 'Raleigh businesses can rely on.',
    paragraphs: [S[11], S[12], S[13]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years securing North Carolina businesses' },
    { value: '0%', label: 'Of our clients have experienced a serious security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'What separates ITSco from other',
    headlineAccent: 'cyber security firms in Raleigh.',
    paragraphs: [S[17], S[18], S[19], S[20], S[22]],
    image: {
      src: '/images/hero/local/raleigh.jpg',
      alt: 'Downtown Raleigh, North Carolina skyline',
    },
  },
  security: {
    eyebrow: 'Compliance Support',
    headlineLead: 'Cyber security services in Raleigh',
    headlineAccent: 'with compliance built in.',
    paragraphs: [S[23], S[24], S[25]],
    image: {
      src: '/images/hero/local/raleigh2.jpg',
      alt: 'Raleigh, North Carolina cityscape',
    },
  },
  related: {
    heading: 'Our other IT services in Raleigh',
    links: [
      {
        slug: 'managed-it-services',
        label: 'Managed IT Services in Raleigh',
        href: '/managed-it-services-raleigh/',
        description: 'Full-suite managed IT — monitoring, help desk, cloud, and support.',
      },
      {
        slug: 'remote-it-support',
        label: 'IT Support in Raleigh',
        href: '/it-support-raleigh/',
        description: 'Responsive remote and on-site IT support for Raleigh businesses.',
      },
      {
        slug: 'it-staff-augmentation',
        label: 'Outsourced IT in Raleigh',
        href: '/raleigh-it-outsourcing/',
        description: 'Scale your IT capacity with ITSco engineers as an extension of your team.',
      },
    ],
  },
  faqHeading: {
    eyebrow: 'FAQ',
    headlineLead: 'Raleigh cyber security,',
    headlineAccent: 'answered.',
  },
  faqs: [
    {
      question: 'What comprehensive measures does ITSco employ to safeguard our data and applications against cyber threats?',
      answer: [S[26], S[27]],
    },
    {
      question: 'How will your Security Information and Event Management (SIEM) service strengthen our cybersecurity defenses?',
      answer: [S[28], S[29]],
    },
    {
      question: 'Can ITSco provide comprehensive support for meeting stringent regulatory compliance and cybersecurity audits?',
      answer: [S[30], S[31]],
    },
    {
      question: 'What extensive cybersecurity protections do you offer for cloud-based systems and data?',
      answer: [S[32], S[33]],
    },
    {
      question: "How does ITSco's strategic cybersecurity consulting provide long-term benefits to our business?",
      answer: [S[34], S[35]],
    },
  ],
  citySlug: 'raleigh',
  bookingUtm: 'cyber-raleigh-bottom',
}
