// Content for /charlotte-it-helpdesk/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'IT Helpdesk in Charlotte, NC | ITSco',
    description:
      'ITSco delivers IT helpdesk services in Charlotte, NC — 24/7 monitoring, remote and on-site support, and sub-hour response on critical events. Book a free consultation.',
    canonical: 'https://www.itsco.com/charlotte-it-helpdesk/',
  },
  hero: {
    eyebrow: 'IT Helpdesk · Charlotte, NC',
    headlineLead: 'IT helpdesk services in Charlotte that',
    headlineAccent: 'get you back to work.',
    body: S[0],
    utmSuffix: 'it-helpdesk-charlotte-hero',
  },
  heroImage: {
    src: '/images/supporting/services/pexels-shvets-production-8413332.jpg',
    alt: 'IT helpdesk specialist supporting a Charlotte business',
  },
  capabilitiesHeading: {
    eyebrow: 'Outsourced Helpdesk Support',
    headlineLead: 'IT helpdesk services',
    headlineAccent: 'for Charlotte, NC businesses.',
  },
  capabilities: [
    { slug: 'remote-monitoring', title: '24/7 Monitoring & Patching', description: S[3] },
    { slug: 'help-desk-services', title: 'Service Desk Support', description: S[4] },
    { slug: 'advanced-engineering', title: 'Senior Engineer Escalation', description: S[5] },
    { slug: 'cyber-security-management', title: 'Cybersecurity Support', description: S[6] },
    { slug: 'custom-slas', title: 'On-Site Support', description: S[7] },
    { slug: 'it-project-management', title: 'License & Patch Management', description: S[8] },
    { slug: 'it-automation', title: 'IT Automation', description: S[9] },
    { slug: 'disaster-recovery', title: 'Disaster Recovery', description: S[10] },
  ],
  positioning: {
    eyebrow: 'Fast, Friendly IT Helpdesk',
    headlineLead: 'IT helpdesk support refined',
    headlineAccent: 'over 25 years in Charlotte.',
    paragraphs: [S[2], S[11], S[12], S[13]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years of IT helpdesk support in the Charlotte metro' },
    { value: '0%', label: 'Of our clients have experienced a serious security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'Technical support that has',
    headlineAccent: 'seen it all.',
    paragraphs: [S[17], S[18], S[19], S[20], S[21]],
    image: {
      src: '/images/hero/local/charlotte nc .jpg',
      alt: 'Downtown Charlotte, North Carolina skyline',
    },
  },
  security: {
    eyebrow: 'Transparent Pricing',
    headlineLead: 'Make your IT investment',
    headlineAccent: 'work for you.',
    paragraphs: [S[25], S[26], S[27]],
    image: {
      src: '/images/hero/local/charlotte nc 2.jpg',
      alt: 'Charlotte, North Carolina cityscape',
    },
  },
  citySlug: 'charlotte',
  bookingUtm: 'it-helpdesk-charlotte-bottom',
}
