// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —
// re-run the script if the live page content changes.
// Source: https://www.itsco.com/managed-network-services/
// Generated: 2026-05-20T18:03:03.331Z

export const SOURCE_URL = "https://www.itsco.com/managed-network-services/"

export const SOURCE_PARAGRAPHS = [
  /* 00 */ "Optimize your network resources, reduce costs, and enhance scalability and security with ITSco’s comprehensive Managed Network Services.",
  /* 01 */ "Our managed solutions ensure maximum uptime and performance while freeing your IT team to focus on strategic priorities.",
  /* 02 */ "We create tailored network solutions that address your unique operational requirements, ensuring seamless alignment with your business goals.",
  /* 03 */ "Choose to outsource all or part of your network management, including planning, installation, monitoring, maintenance, troubleshooting, and support.",
  /* 04 */ "Our team minimizes downtime with proactive monitoring, health checks, and Service-Level Agreements (SLAs) customized to your business needs.",
  /* 05 */ "Gain access to our experienced network engineering professionals, bringing decades of experience to every engagement.",
  /* 06 */ "From basic monitoring to fully managed network operations, we deliver a complete range of services tailored to your level of need.",
  /* 07 */ "Managing network infrastructure in-house can be an unnecessary distraction to business operations and an impediment to growth, issue include:",
  /* 08 */ "Businesses may struggle to design, manage, and maintain a network that aligns with evolving needs.",
  /* 09 */ "Internal teams may lack access to advanced network engineering knowledge and experience.",
  /* 10 */ "Without proactive monitoring, networks are vulnerable to disruptions and cyber threats.",
  /* 11 */ "Growing businesses often face difficulties adapting their networks to handle increased demands.",
  /* 12 */ "Capital expenditures for hardware and staffing can quickly escalate without a predictable budget.",
  /* 13 */ "Learn more about our extensive network engineering capabilities .",
  /* 14 */ "of experience with a record of 99%+ network uptime.",
  /* 15 */ "through improved security, redundancy, & scalability.",
  /* 16 */ "and services that are tailored for your business needs.",
  /* 17 */ "to customer success & proactive mon i toring and maintenance.",
  /* 18 */ "Empower your business with ITSco’s Managed Network Services. Whether you need basic monitoring or a fully managed solution, our team ensures your network is reliable, secure, and scalable.",
] as const
