// Content for /managed-network-services/
//
// Verbatim copy lives in ./_source.ts (auto-generated by
// scripts/sync-content.mjs). This file maps each slot to source indices.

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Managed Network Services | Network Management & Support | ITSco',
    description:
      'ITSco managed network services — proactive monitoring, design, and support that keep your network reliable, secure, and scalable. Book a free consultation.',
    canonical: 'https://www.itsco.com/managed-network-services/',
  },
  serviceName: 'Managed Network Services',
  hero: {
    eyebrow: 'Managed IT · Network Services',
    headlineLead: 'Managed network services',
    headlineAccent: 'that keep you running.',
    body: S[0],
    utmSuffix: 'managed-network-services-hero',
  },
  heroImage: {
    src: '/images/hero/services/creatopy-mlwrIzr7yNs-unsplash.jpg',
    alt: 'ITSco network engineer managing data center infrastructure',
  },
  intro: {
    eyebrow: 'The Opportunity',
    headlineLead: 'Elevate your network with',
    headlineAccent: "ITSco's managed services.",
    paragraphs: [S[1]],
  },
  stats: [
    { value: '25+', label: 'Years of network engineering experience' },
    { value: '99%+', label: 'Network uptime across managed clients' },
    { value: '24/7', label: 'Proactive monitoring and maintenance' },
  ],
  capabilitiesHeading: {
    eyebrow: 'Comprehensive Managed Network Services',
    headlineLead: 'Everything your network needs,',
    headlineAccent: 'under one program.',
  },
  capabilities: [
    {
      slug: 'network-design-support',
      title: 'Customizable Network Design and Support',
      description: S[2],
    },
    { slug: 'flexible-outsourcing', title: 'Flexible Outsourcing Options', description: S[3] },
    {
      slug: 'proactive-network-monitoring',
      title: 'Proactive Monitoring and Maintenance',
      description: S[4],
    },
    { slug: 'network-expertise', title: 'World-Class Expertise', description: S[5] },
    { slug: 'full-service-network', title: 'Full-Service Capabilities', description: S[6] },
  ],
  outcomes: {
    eyebrow: 'The Challenge',
    headlineLead: 'The challenges of',
    headlineAccent: 'in-house network management.',
    paragraphs: [],
    bullets: [S[8], S[9], S[10], S[11], S[12]],
    image: {
      src: '/images/supporting/services/network-services.jpg',
      alt: 'Network cabling and switching infrastructure in a server room',
    },
  },
  related: {
    heading: 'Explore more managed IT services',
    links: [
      {
        slug: 'server-monitoring-and-maintenance',
        label: 'Server Monitoring & Maintenance',
        href: '/server-monitoring-and-maintenance/',
        description: '24/7 monitoring, patching, and tuning that keeps critical servers healthy.',
      },
      {
        slug: 'backup-disaster-recovery',
        label: 'Backup & Disaster Recovery',
        href: '/backup-disaster-recovery/',
        description: 'Automated backups and tested recovery plans that protect against the worst case.',
      },
      {
        slug: 'managed-it-services',
        label: 'Managed IT Services',
        href: '/managed-it-services/',
        description: 'The full ITSco managed IT program — monitoring, helpdesk, security, and more.',
      },
    ],
  },
  bookingUtm: 'managed-network-services-bottom',
}
