// Content for /managed-it-services-high-point/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'Managed IT Services in High Point, NC',
    description:
      'ITSco delivers managed IT services in High Point, NC — monitoring, cybersecurity, cloud, and automation — to help you meet your business goals. Book a free consultation.',
    canonical: 'https://www.itsco.com/managed-it-services-high-point/',
  },
  hero: {
    eyebrow: 'Managed IT Services · High Point, NC',
    headlineLead: 'Managed IT services in High Point',
    headlineAccent: 'built around your business goals.',
    body: S[0],
    utmSuffix: 'managed-it-high-point-hero',
  },
  heroImage: {
    src: '/images/supporting/services/annie-spratt-sggw4-qDD54-unsplash-1024x702.jpg',
    alt: 'IT professional supporting a High Point business',
  },
  capabilitiesHeading: {
    eyebrow: 'Full-Suite Business IT Services',
    headlineLead: 'Comprehensive managed IT services',
    headlineAccent: 'in High Point, NC.',
  },
  capabilities: [
    { slug: 'remote-monitoring', title: 'Remote Monitoring', description: S[1] },
    { slug: 'cyber-security-management', title: 'Cybersecurity', description: S[2] },
    { slug: 'help-desk-services', title: 'Help Desk Services', description: S[3] },
    { slug: 'cloud-computing', title: 'Cloud Services', description: S[4] },
    { slug: 'custom-slas', title: 'Customized SLAs', description: S[5] },
    { slug: 'disaster-recovery', title: 'Disaster Recovery', description: S[7] },
    { slug: 'vulnerability-management', title: 'Vulnerability Management', description: S[8] },
    { slug: 'it-automation', title: 'IT Automation', description: S[9] },
    { slug: 'it-project-management', title: 'IT Project Management', description: S[10] },
  ],
  positioning: {
    eyebrow: 'Think About IT Strategically',
    headlineLead: 'IT services in High Point that',
    headlineAccent: 'boost business productivity.',
    paragraphs: [S[11], S[12], S[13], S[14]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years serving High Point & the Triad' },
    { value: '0%', label: 'Of our clients have experienced a major security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'A managed services provider',
    headlineAccent: 'High Point businesses trust.',
    paragraphs: [S[18], S[19], S[20], S[28], S[29]],
    image: {
      src: '/images/hero/consulting/pexels-gustavo-fring-6285127.jpg',
      alt: 'ITSco team collaborating with a client',
    },
  },
  security: {
    eyebrow: 'Cybersecurity in High Point',
    headlineLead: 'Security built in,',
    headlineAccent: 'not added on.',
    paragraphs: [S[23], S[24]],
    image: {
      src: '/images/supporting/services/nastuh-abootalebi-eHD8Y1Znfpk-unsplash.jpg',
      alt: 'Cybersecurity monitoring for a High Point business',
    },
  },
  citySlug: 'high-point',
  bookingUtm: 'managed-it-high-point-bottom',
}
