// Content for /managed-it-services-wilmington/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'Managed IT Services in Wilmington, NC | IT Solutions Provider',
    description:
      'ITSco is the Wilmington IT solutions provider businesses trust — managed IT, security, help desk, and cloud aligned with your business goals. Book a free consultation.',
    canonical: 'https://www.itsco.com/managed-it-services-wilmington/',
  },
  hero: {
    eyebrow: 'Managed IT Services · Wilmington, NC',
    headlineLead: 'Managed IT services in Wilmington that',
    headlineAccent: 'align IT spending with your goals.',
    body: S[0],
    utmSuffix: 'managed-it-wilmington-hero',
  },
  heroImage: {
    src: '/images/supporting/services/pexels-mart-production-7255723.jpg',
    alt: 'IT professional reviewing systems for a Wilmington business',
  },
  capabilitiesHeading: {
    eyebrow: 'Features of Our IT Managed Services',
    headlineLead: 'Full-suite managed IT services',
    headlineAccent: 'in Wilmington, NC.',
  },
  capabilities: [
    { slug: 'remote-monitoring', title: 'Remote Monitoring', description: S[1] },
    { slug: 'network-security-services', title: 'IT & Network Security', description: S[2] },
    { slug: 'help-desk-services', title: 'Help Desk Services', description: S[3] },
    { slug: 'cloud-computing', title: 'Cloud Services', description: S[4] },
    { slug: 'custom-slas', title: 'Customized Services & SLAs', description: S[5] },
    { slug: 'disaster-recovery', title: 'Business Continuity Planning', description: S[6] },
    { slug: 'vulnerability-management', title: 'Vulnerability Management', description: S[7] },
    { slug: 'it-automation', title: 'IT Automation', description: S[8] },
    { slug: 'it-project-management', title: 'IT Project Management', description: S[9] },
  ],
  positioning: {
    eyebrow: 'Strong Return on IT Investment',
    headlineLead: 'Improve productivity and ROI with',
    headlineAccent: 'one of Wilmington’s top IT companies.',
    paragraphs: [S[10], S[11], S[24], S[25]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years supporting North Carolina businesses' },
    { value: '30%', label: 'Of our clients have been with us for 10+ years' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'One of the best managed services',
    headlineAccent: 'providers in Wilmington.',
    paragraphs: [S[19], S[20], S[21], S[22], S[23]],
    image: {
      src: '/images/supporting/services/berkeley-communications-WEDDt-u3q3o-unsplash.jpg',
      alt: 'ITSco team collaborating on a client engagement',
    },
  },
  security: {
    eyebrow: 'Cybersecurity in Wilmington',
    headlineLead: 'Defend your business against',
    headlineAccent: 'cybercriminals.',
    paragraphs: [S[15], S[16], S[17]],
    image: {
      src: '/images/supporting/services/pexels-shvets-production-8413332.jpg',
      alt: 'Cybersecurity specialist monitoring systems',
    },
  },
  citySlug: 'wilmington',
  bookingUtm: 'managed-it-wilmington-bottom',
}
