// Content for /managed-it-services-huntersville/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'Managed IT Services in Huntersville, NC | ITSco',
    description:
      'ITSco delivers managed IT services in Huntersville, NC — monitoring, cybersecurity, help desk, and cloud — that save time and money. Book a free consultation.',
    canonical: 'https://www.itsco.com/managed-it-services-huntersville/',
  },
  hero: {
    eyebrow: 'Managed IT Services · Huntersville, NC',
    headlineLead: 'Managed IT services in Huntersville',
    headlineAccent: 'that gets IT done.',
    body: S[0],
    utmSuffix: 'managed-it-huntersville-hero',
  },
  heroImage: {
    src: '/images/supporting/services/beatriz-cattel-JtcJoKiz-m4-unsplash.jpg',
    alt: 'IT professional supporting a Huntersville business',
  },
  capabilitiesHeading: {
    eyebrow: 'Comprehensive Managed IT Services',
    headlineLead: 'Full-suite IT services for',
    headlineAccent: 'Huntersville businesses.',
  },
  capabilities: [
    { slug: 'remote-monitoring', title: 'Remote Monitoring', description: S[1] },
    { slug: 'cyber-security-management', title: 'Cybersecurity Services', description: S[2] },
    { slug: 'help-desk-services', title: 'Help Desk Services', description: S[3] },
    { slug: 'cloud-computing', title: 'Cloud Solutions', description: S[4] },
    { slug: 'disaster-recovery', title: 'Data Loss Prevention', description: S[5] },
    { slug: 'custom-slas', title: 'Business Continuity Planning', description: S[6] },
    { slug: 'vulnerability-management', title: 'Vulnerability Management', description: S[7] },
    { slug: 'it-automation', title: 'IT Automation', description: S[8] },
    { slug: 'it-project-management', title: 'IT Consulting Services', description: S[9] },
  ],
  positioning: {
    eyebrow: 'Cost-Effective IT Managed Services',
    headlineLead: 'IT services in Huntersville that',
    headlineAccent: 'offer the greatest ROI.',
    paragraphs: [S[10], S[11], S[18], S[19]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years serving Huntersville & the Charlotte area' },
    { value: '0%', label: 'Of our clients have experienced a serious security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'A different kind of managed IT',
    headlineAccent: 'services provider in Huntersville.',
    paragraphs: [S[20], S[21], S[22], S[24], S[25]],
    image: {
      src: '/images/hero/consulting/creatopy-E3LsanLgkLM-unsplash.jpg',
      alt: 'ITSco engineers collaborating on a project',
    },
  },
  security: {
    eyebrow: 'Cybersecurity in Huntersville',
    headlineLead: 'Protect your information assets',
    headlineAccent: 'from cyberattacks.',
    paragraphs: [S[15], S[16], S[17]],
    image: {
      src: '/images/supporting/services/windows-AigsWJmvoEo-unsplash.jpg',
      alt: 'Cybersecurity monitoring for a Huntersville business',
    },
  },
  citySlug: 'huntersville',
  bookingUtm: 'managed-it-huntersville-bottom',
}
