// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —
// re-run the script if the live page content changes.
// Source: https://www.itsco.com/services/itad/
// Generated: 2026-05-21T14:32:23.596Z

export const SOURCE_URL = "https://www.itsco.com/services/itad"

export const SOURCE_PARAGRAPHS = [
  /* 00 */ "Retiring old IT assets isn’t just about disposal—it’s about protecting sensitive data, maintaining compliance, and ensuring an efficient, secure process.",
  /* 01 */ "ITSco’s IT Asset Disposition (ITAD) services help businesses securely remove and dispose of IT hardware while minimizing risk, maximizing value recovery, and ensuring full regulatory compliance.",
  /* 02 */ "We employ the highest industry standards for data destruction and IT asset handling.",
  /* 03 */ "Our engineers execute IT asset removals from live environments with precision and care.",
  /* 04 */ "We handle all major IT hardware brands and ensure proper integration with your IT lifecycle strategy.",
  /* 05 */ "We prioritize eco-friendly recycling and responsible e-waste disposal.",
  /* 06 */ "Without a proper IT asset disposition strategy, businesses can face serious challenges, including:",
  /* 07 */ "Improper disposal can leave sensitive company and customer data exposed to breaches.",
  /* 08 */ "Disposing of IT equipment without proper protocols can result in environmental harm and reputational damage.",
  /* 09 */ "Poorly executed asset removal can cause downtime and impact critical systems.",
  /* 10 */ "Ensure your compliance with regulatory standards and industry best practices, including:",
  /* 11 */ "Serving businesses since 1996 with proven IT expertise.",
  /* 12 */ "Customized ITAD strategies to fit your needs.",
  /* 13 */ "Responsive, transparent, and hassle-free execution.",
  /* 14 */ "Access to a full suite of IT, security, and cloud solutions.",
  /* 15 */ "Whether you need to retire aging hardware, decommission a data center, or ensure compliant data destruction, ITSco delivers secure, efficient, and fully managed ITAD solutions that protect your business and your data.",
] as const
