// /lib/iconMap.ts
// Maps page slugs and service slugs to Lucide React icon names.
// Used by DynamicIcon component — never hardcode icon names in page files.
// Fallback icon: 'Cpu' renders if slug not found.

export const iconMap: Record<string, string> = {

  // ── Managed IT ─────────────────────────────────────────────────────────────
  'managed-it-services':                        'Server',
  'managed-network-services':                   'Network',
  'helpdesk':                                   'Headphones',
  'raleigh-it-helpdesk':                        'Headphones',
  'server-monitoring-and-maintenance':          'Activity',
  'backup-disaster-recovery':                   'HardDrive',
  'asset-lifecycle-management':                 'Package',
  'remote-it-support':                          'MonitorSmartphone',
  'it-staff-augmentation':                      'Users',
  'employee-onboarding-offboarding':            'UserPlus',
  'it-procurement':                             'ShoppingCart',

  // ── Cybersecurity ───────────────────────────────────────────────────────────
  'cybersecurity':                              'Shield',
  'fully-managed-cybersecurity':                'ShieldCheck',
  'managed-soc':                                'Eye',
  'siem-services':                              'Radio',
  'mdr-monitoring-and-response':                'ScanEye',
  'network-security':                           'Lock',
  'endpoint-security':                          'Laptop',
  'managed-firewall':                           'Flame',
  'ids-ips':                                    'Radar',
  'email-security':                             'MailWarning',
  'cyber-risk-assessment':                      'TriangleAlert',
  'penetration-testing-services':               'Bug',
  'security-audits-compliance':                 'ClipboardCheck',
  'compliance-management':                      'BadgeCheck',
  'compliance-as-a-service':                    'BadgeCheck',
  'vcaio-leadership':                           'BrainCircuit',
  'caas-framework-alignment':                   'BadgeCheck',
  'caas-continuous-monitoring':                 'Activity',
  'caas-policy-management':                     'FileCheck',
  'caas-control-testing':                       'ClipboardCheck',
  'caas-audit-prep':                            'LifeBuoy',
  'caas-reporting':                             'BarChart3',
  'zero-trust-security':                        'KeyRound',
  'cloud-cybersecurity':                        'CloudLock',
  'security-event-remediation-ip-protection':   'ShieldAlert',
  'it-security-assessment':                     'ScanSearch',

  // ── Cloud ───────────────────────────────────────────────────────────────────
  'cloud-services':                             'Cloud',
  'managed-cloud-services':                     'CloudCog',
  'cloud-migration':                            'CloudUpload',
  'cloud-hosting':                              'Server',
  'public-hybrid-cloud-services':               'Layers',
  'private-cloud-services':                     'Lock',
  'aws-services':                               'Boxes',
  'virtualization-services':                    'Copy',
  'managed-desktop-vdi':                        'Monitor',
  'cloud-consulting-services':                  'CloudSun',

  // ── Strategy & Consulting ───────────────────────────────────────────────────
  'it-management-consulting':                   'BarChart3',
  'vcio-vcto-vciso-services':                   'BarChart3',
  'fractional-cto-services':                    'Compass',
  'it-roadmap-planning':                        'Map',
  'it-assessments-strategies':                  'ClipboardList',
  'it-audits-and-assessments':                  'ClipboardList',
  'tech-due-diligence-for-businesses':          'SearchCheck',
  'it-due-diligence-mergers-acquisitions':      'GitMerge',
  'technical-project-management':               'Kanban',
  'it-roi-assessment':                          'TrendingUp',
  'business-continuity-planning':               'RefreshCw',
  'it-strategy-services':                       'Compass',
  'maximize-roi-with-managed-it-services':      'TrendingUp',

  // ── Microsoft Solutions ─────────────────────────────────────────────────────
  'microsoft-solutions':                        'Layout',
  'services-for-the-microsoft-suite':           'Layout',
  'microsoft-365-services':                     'Grid3X3',
  'microsoft-azure-services':                   'Layers',
  'microsoft-teams-services':                   'MessageSquare',
  'microsoft-exchange-services':                'Mail',
  'microsoft-sharepoint-services':              'FolderOpen',
  'microsoft-copilot':                          'Sparkles',
  'microsoft-copilot-implementation':           'Sparkles',
  'microsoft-sentinel':                         'ScanSearch',

  // ── Engineering ─────────────────────────────────────────────────────────────
  'network-engineering':                        'Cable',
  'systems-engineering':                        'Cpu',
  'voip-unified-communications':                'Phone',
  'itad':                                       'Recycle',
  'services-itad':                              'Recycle',

  // ── AI & Automation ─────────────────────────────────────────────────────────
  'ai-automation':                              'Brain',
  'ai-governance':                              'ShieldCheck',
  'ai-readiness-assessment':                    'Brain',
  'ai-strategy-consulting':                     'Lightbulb',
  'ai-opportunity-mapping':                     'Target',
  'ai-strategy-roadmap':                        'Map',
  'ai-vendor-platform-selection':               'GitCompare',
  'ai-governance-risk':                         'ShieldAlert',
  'ai-pilot-design':                            'FlaskConical',
  'ai-strategic-adoption':                      'TrendingUp',
  'ai-data-readiness':                          'Database',
  'ai-infrastructure-security':                 'ShieldCheck',
  'ai-workforce-enablement':                    'Users',
  'ai-compliance-risk':                         'Gavel',
  'ai-competitive-edge':                        'Trophy',
  'healthcare-ai-services':                     'HeartPulse',
  'process-automation':                         'Workflow',
  'roi-calculator':                             'Calculator',
  'compare-msps':                               'BarChart2',

  // ── Industries — by vertical ────────────────────────────────────────────────
  'healthcare-managed-it-services':             'Stethoscope',
  'custom-it-network-services-healthcare-institutions': 'Stethoscope',
  'pharma-med-tech-it-services':                'FlaskConical',
  'financial-services-it':                      'Landmark',
  'legal-and-law-firm-it-services':             'Scale',
  'accounting-firm-it-services':                'Receipt',
  'manufacturing-it':                           'Factory',
  'education-it-services':                      'GraduationCap',
  'professional-it-services':                   'Briefcase',
  'construction-it-services':                   'HardHat',
  'non-profit-it-services':                     'Heart',
  'transportation-logistics-it-services':       'Truck',
  'real-estate-it-services':                    'Building2',
  'marketing-it-services':                      'Megaphone',
  'government-it-services':                     'Building',
  'government-contractor-it-services':          'Building',
  'private-equity-it-services':                 'TrendingUp',
  'dealership-and-automotive-it-services':      'Car',
  'retail-it-services':                         'Store',

  // ── Industries — by size ────────────────────────────────────────────────────
  'small-business':                             'Store',
  'mid-sized-business':                         'Building',
  'large-business-it-services':                 'Building2',
  'enterprise-managed-it-services':             'Landmark',

  // ── Resources ───────────────────────────────────────────────────────────────
  'resource-center':                            'BookOpen',
  'white-papers':                               'FileText',
  'case-studies':                               'Award',
  'blog':                                       'Rss',

  // ── About ────────────────────────────────────────────────────────────────────
  'about-us':                                   'Users',
  'process':                                    'GitBranch',
  'partners':                                   'Handshake',
  'contact-us':                                 'Phone',
  'request-our-pricing-guide':                  'FileText',
  'value-integrity':                            'Handshake',
  'value-team':                                 'Users',
  'value-results':                              'Trophy',

  // ── City service-page capabilities ───────────────────────────────────────────
  'remote-monitoring':                          'Activity',
  'cyber-security-management':                  'ShieldCheck',
  'help-desk-services':                         'Headphones',
  'advanced-engineering':                       'Cog',
  'custom-slas':                                'FileCheck',
  'preventative-maintenance':                   'Wrench',
  'cloud-computing':                            'Cloud',
  'it-automation':                              'Workflow',
  'disaster-recovery':                          'LifeBuoy',
  'network-security-services':                  'Lock',
  'vulnerability-management':                   'ShieldAlert',
  'it-project-management':                      'ClipboardList',

  // ── City cyber-security-page capabilities ────────────────────────────────────
  'cyber-threat-solutions':                     'ShieldCheck',
  'security-architecture':                      'Network',
  'security-awareness-training':                'GraduationCap',
  'risk-management':                            'TriangleAlert',
  'strategic-security-consulting':              'Compass',

  // ── Managed IT sub-page capabilities ─────────────────────────────────────────
  // Managed Network Services
  'network-design-support':                     'Network',
  'flexible-outsourcing':                       'Shuffle',
  'proactive-network-monitoring':               'Activity',
  'network-expertise':                          'Award',
  'full-service-network':                       'Layers',
  // Server Monitoring & Maintenance
  'server-monitoring-response':                 'Activity',
  'server-maintenance-optimization':            'Wrench',
  'server-security-hardening':                  'ShieldCheck',
  'server-backup-recovery':                     'HardDrive',
  'server-capacity-planning':                   'TrendingUp',
  'server-troubleshooting':                     'Search',
  // Backup & Disaster Recovery
  'automated-backups':                          'DatabaseBackup',
  'fast-disaster-recovery':                     'LifeBuoy',
  'cloud-onprem-backup':                        'CloudCog',
  'ransomware-protection':                      'ShieldAlert',
  'bdr-compliance-support':                     'BadgeCheck',
  // Asset Lifecycle Management
  'site-assessment':                            'ClipboardCheck',
  'hardware-maintenance':                       'Wrench',
  'inventory-auditing':                         'ClipboardList',
  'certified-data-destruction':                 'FileX2',
  'de-installation':                            'Unplug',
  'relocation-services':                        'Truck',
  'ewaste-recycling':                           'Recycle',
  // Server Administration & Support
  'hardware-software-support':                  'Wrench',
  'end-user-assistance':                        'Headphones',
  'server-security':                            'ShieldCheck',
  'continuous-server-monitoring':               'Activity',
  'server-deployments':                         'ServerCog',
  'cloud-support':                              'Cloud',
  // Remote IT Support
  'rapid-remote-resolution':                    'Zap',
  'remote-helpdesk':                            'Headphones',
  'remote-patch-management':                    'RefreshCw',
  'endpoint-management':                        'Laptop',
  'remote-security-monitoring':                 'ShieldCheck',
  'distributed-team-support':                   'Globe',
  // IT Staff Augmentation
  'embedded-engineers':                         'UserCog',
  'project-surge-support':                      'TrendingUp',
  'specialized-skills':                         'Award',
  'flexible-engagement':                        'Shuffle',
  'managed-handoff':                            'GitBranch',
  'scalable-capacity':                          'Scaling',
  // Employee Onboarding & Offboarding
  'account-provisioning':                       'UserPlus',
  'device-setup':                               'Laptop',
  'access-management':                          'KeyRound',
  'secure-offboarding':                         'UserMinus',
  'data-handover':                              'FolderInput',
  'license-recovery':                           'Receipt',
  // Onsite IT Support
  'onsite-dispatch':                            'Truck',
  'hardware-installation':                      'Wrench',
  'network-cabling':                            'Cable',
  'hands-on-troubleshooting':                   'Search',
  'office-moves':                               'Building2',
  'scheduled-onsite-visits':                    'CalendarClock',

  // ── Cybersecurity sub-page capabilities ──────────────────────────────────────
  // Fully-Managed Cybersecurity
  'intrusion-detection-prevention':             'ShieldAlert',
  'network-security-managed':                   'Network',
  'endpoint-security-managed':                  'Laptop',
  'vulnerability-assessments':                  'ScanSearch',
  'email-security-managed':                     'MailWarning',
  'firewall-config-monitoring':                 'Flame',
  // Managed SOC
  'soc-detection-response':                     'Eye',
  'managed-siem':                               'Radio',
  'intrusion-detection-system':                 'Radar',
  'endpoint-detection-response':                'ScanEye',
  'vulnerability-scanning':                     'ScanSearch',
  'behavioral-monitoring':                      'Activity',
  // MDR
  'mdr-threat-detection':                       'ScanEye',
  'threat-hunting':                             'Crosshair',
  'incident-response':                          'Siren',
  'flexible-security-services':                 'Shuffle',
  'security-integration':                       'Boxes',
  // Penetration Testing
  'comprehensive-pen-testing':                  'Bug',
  'physical-security-assessment':               'DoorClosed',
  'social-engineering-assessment':              'UserX',
  'cloud-pen-testing':                          'CloudCog',
  'compliance-checks':                          'ClipboardCheck',
  'transparent-reporting':                      'FileText',
  // Email Security
  'anti-phishing':                              'Fish',
  'malware-blocking':                           'ShieldX',
  'account-takeover-prevention':                'LockKeyhole',
  'email-monitoring':                           'MailCheck',
  'email-incident-response':                    'Siren',
  // Security Audits & Compliance
  'cyber-risk-assessments':                     'TriangleAlert',
  'regulatory-compliance-audits':               'BadgeCheck',
  'pentest-vuln-scanning':                      'Bug',
  'security-policy-review':                     'FileCheck',
  'cloud-security-assessment':                  'CloudLock',
  'incident-response-planning':                 'LifeBuoy',
  // IDS/IPS
  'ai-antimalware':                             'Bot',
  'content-filtering':                          'Filter',
  'secure-web-gateway':                         'Globe',
  'ai-machine-learning':                        'BrainCircuit',
  'realtime-detection-mitigation':              'Zap',
  'reporting-analysis':                         'BarChart3',
  // Cybersecurity Consulting
  'managed-detection-response':                 'ScanEye',
  'firewall-management':                        'Flame',
  'web-app-testing':                            'Code',
  'awareness-training':                         'GraduationCap',
  'vciso-services':                             'UserCog',
  // SIEM Services
  'log-collection-correlation':                 'ScrollText',
  'realtime-threat-detection':                  'Zap',
  'siem-alerting':                              'BellRing',
  'threat-intelligence':                        'Globe',
  'compliance-reporting':                       'FileText',
  'siem-managed-response':                      'Siren',
  // Network Security
  'firewall-protection':                        'Flame',
  'network-segmentation':                       'Network',
  'intrusion-prevention':                       'ShieldAlert',
  'secure-remote-access':                       'KeyRound',
  'wifi-security':                              'Wifi',
  'network-monitoring-security':                'Activity',
  // Endpoint Security
  'edr':                                        'ScanEye',
  'next-gen-antivirus':                         'ShieldCheck',
  'device-encryption':                          'Lock',
  'patch-management-security':                  'RefreshCw',
  'application-control':                        'AppWindow',
  'mobile-device-security':                     'Smartphone',
  // Managed Firewall
  'firewall-configuration':                     'Settings',
  'firewall-monitoring':                        'Activity',
  'rule-management':                            'ListChecks',
  'threat-prevention-firewall':                 'ShieldAlert',
  'firewall-updates':                           'RefreshCw',
  'firewall-reporting':                         'FileText',
  // Cyber Risk Assessment
  'risk-discovery':                             'Search',
  'vulnerability-identification':               'ScanSearch',
  'threat-modeling':                            'Crosshair',
  'compliance-gap-analysis':                    'ClipboardList',
  'risk-prioritization':                        'ListChecks',
  'remediation-roadmap':                        'Map',
  // Cloud Cybersecurity
  'cloud-config-management':                    'CloudCog',
  'cloud-identity-access':                      'KeyRound',
  'cloud-data-protection':                      'CloudLock',
  'cloud-threat-monitoring':                    'ScanEye',
  'cloud-compliance':                           'BadgeCheck',
  'cloud-backup-resilience':                    'DatabaseBackup',
  // Zero Trust Security
  'identity-verification':                      'Fingerprint',
  'mfa':                                        'KeyRound',
  'least-privilege-access':                     'Lock',
  'device-trust':                               'ShieldCheck',
  'microsegmentation':                          'Grid3X3',
  'continuous-verification':                    'RefreshCw',

  // ── Cloud sub-page capabilities ──────────────────────────────────────────────
  // Microsoft Azure Services
  'azure-migration-deployment':                 'CloudUpload',
  'azure-management-optimization':              'CloudCog',
  'azure-security-compliance':                  'CloudLock',
  'azure-infrastructure-integration':           'Network',
  'azure-consulting-strategy':                  'Compass',
  'azure-training-adoption':                    'GraduationCap',
  // Cloud Migration
  'talent-gap-solutions':                       'Users',
  'error-free-migration':                       'CheckCheck',
  'outcome-driven-strategies':                  'Target',
  'application-modernization':                  'Boxes',
  'migration-governance-compliance':            'BadgeCheck',
  'cost-effective-migration':                   'TrendingDown',
  // Public & Hybrid Cloud
  'public-cloud':                               'Cloud',
  'cloud-disaster-recovery':                    'LifeBuoy',
  'hybrid-cloud':                               'Layers',
  'cloud-devops':                               'GitBranch',
  'cloud-big-data':                             'Database',
  'cloud-cost-management':                      'Receipt',
  // Managed Desktop & VDI
  'managed-vdi':                                'Monitor',
  'vdi-monitoring':                             'Activity',
  'vdi-support':                                'Headphones',
  'vdi-cybersecurity':                          'ShieldCheck',
  'vdi-implementation-migration':               'CloudUpload',
  'vdi-user-training':                          'GraduationCap',
  // Managed Cloud Services
  'cloud-monitoring':                           'Activity',
  'cloud-optimization':                         'Gauge',
  'cloud-cost-control':                         'Receipt',
  'cloud-security-mgmt':                        'ShieldCheck',
  'cloud-backup':                               'DatabaseBackup',
  // Cloud Hosting
  'scalable-hosting':                           'Scaling',
  'hosting-uptime':                             'Activity',
  'hosting-performance':                        'Gauge',
  'hosting-security':                           'Lock',
  'hosting-backup':                             'DatabaseBackup',
  'hosting-support':                            'Headphones',
  // Private Cloud Services
  'dedicated-infrastructure':                   'Server',
  'private-cloud-security':                     'ShieldCheck',
  'private-cloud-compliance':                   'BadgeCheck',
  'predictable-performance':                    'Gauge',
  'private-cloud-management':                   'CloudCog',
  'private-cloud-scalability':                  'Scaling',
  // AWS Services
  'aws-migration':                              'CloudUpload',
  'aws-management':                             'CloudCog',
  'aws-security':                               'ShieldCheck',
  'aws-cost':                                   'Receipt',
  'aws-architecture':                           'Network',
  'aws-support':                                'Headphones',
  // Virtualization Services
  'server-virtualization':                      'Server',
  'desktop-virtualization':                     'Monitor',
  'virtualization-design':                      'PenTool',
  'virtualization-migration':                   'CloudUpload',
  'virtualization-resilience':                  'LifeBuoy',
  'virtualization-management':                  'Gauge',
  // Cloud Consulting
  'cloud-assessment':                           'ClipboardCheck',
  'cloud-strategy':                             'Compass',
  'platform-selection':                         'Layers',
  'cloud-cost-modeling':                        'Calculator',
  'cloud-architecture-consulting':              'Network',
  'cloud-governance':                           'BadgeCheck',

  // ── Microsoft sub-page capabilities ──────────────────────────────────────────
  // Microsoft Exchange
  'exchange-deployment-migration':              'CloudUpload',
  'exchange-management-support':                'Settings',
  'exchange-security-compliance':               'ShieldCheck',
  'exchange-integrations':                      'Layers',
  'exchange-training-support':                  'GraduationCap',
  // Microsoft SharePoint
  'sharepoint-deployment-migration':            'CloudUpload',
  'sharepoint-management-support':              'Settings',
  'sharepoint-security-compliance':             'ShieldCheck',
  'sharepoint-integration-customization':       'Layers',
  'sharepoint-training-adoption':               'GraduationCap',
  // Microsoft 365
  'm365-deployment':                            'CloudUpload',
  'm365-management':                            'Settings',
  'm365-security':                              'ShieldCheck',
  'm365-collaboration':                         'Users',
  'm365-licensing':                             'Receipt',
  'm365-support':                               'Headphones',
  // Microsoft Teams
  'teams-deployment':                           'MessageSquare',
  'teams-voice':                                'Phone',
  'teams-governance':                           'ShieldCheck',
  'teams-integration':                          'Layers',
  'teams-meetings':                             'Video',
  'teams-support':                              'Headphones',
  // Microsoft Copilot
  'copilot-readiness':                          'ClipboardCheck',
  'copilot-deployment':                         'Sparkles',
  'copilot-data-governance':                    'ShieldCheck',
  'copilot-integration':                        'Layers',
  'copilot-training':                           'GraduationCap',
  'copilot-optimization':                       'Gauge',
  // Microsoft Sentinel
  'sentinel-deployment':                        'CloudUpload',
  'sentinel-detection':                         'ScanEye',
  'sentinel-monitoring':                        'Eye',
  'sentinel-response':                          'Siren',
  'sentinel-automation':                        'Workflow',
  'sentinel-reporting':                         'FileText',

  // ── Strategy & Consulting sub-page capabilities ──────────────────────────────
  // vCIO / vCTO / vCISO
  'vcio-leadership':                            'BarChart3',
  'vcto-leadership':                            'Compass',
  'vciso-leadership':                           'ShieldCheck',
  // IT Assessments & Strategies
  'technology-audits':                          'ClipboardCheck',
  'cybersecurity-assessments':                  'ScanSearch',
  'bcdr-reviews':                               'LifeBuoy',
  'strategic-review-reporting':                 'FileText',
  // Technology Due Diligence
  'tdd-infrastructure':                         'Server',
  'tdd-cybersecurity':                          'ShieldCheck',
  'tdd-operations':                             'Settings',
  'tdd-risk-opportunities':                     'TriangleAlert',
  'tdd-compliance':                             'BadgeCheck',
  // Technical Project Management
  'tpm-planning':                               'ClipboardList',
  'tpm-oversight':                              'Network',
  'tpm-risk-management':                        'TriangleAlert',
  'tpm-milestone-tracking':                     'Flag',
  'tpm-vendor-management':                      'Handshake',
  'tpm-post-implementation':                    'LifeBuoy',
  // IT ROI Assessment
  'roi-infrastructure-audit':                   'ClipboardCheck',
  'roi-gap-analysis':                           'Search',
  'roi-optimization':                           'Gauge',
  'roi-licensing-review':                       'Receipt',
  'roi-strategy-alignment':                     'Target',
  // IT Roadmap Planning
  'roadmap-current-state':                      'ClipboardCheck',
  'roadmap-business-alignment':                 'Target',
  'roadmap-prioritization':                     'ListChecks',
  'roadmap-budgeting':                          'Receipt',
  'roadmap-risk':                               'TriangleAlert',
  'roadmap-reviews':                            'RefreshCw',
  // Fractional CTO
  'fcto-strategy':                              'Compass',
  'fcto-roadmap':                               'Map',
  'fcto-vendor':                                'Network',
  'fcto-team':                                  'Users',
  'fcto-risk':                                  'ShieldAlert',
  'fcto-board':                                 'Presentation',
  // IT Due Diligence for M&A
  'ma-infrastructure-review':                   'Server',
  'ma-security-review':                         'ShieldCheck',
  'ma-cost-review':                             'Receipt',
  'ma-scalability':                             'Scaling',
  'ma-integration-planning':                    'GitMerge',
  'ma-valuation-input':                         'Calculator',
  // Business Continuity Planning
  'bcp-risk-assessment':                        'TriangleAlert',
  'bcp-continuity-strategy':                    'Compass',
  'bcp-recovery-planning':                      'LifeBuoy',
  'bcp-backup':                                 'DatabaseBackup',
  'bcp-testing':                                'ClipboardCheck',
  'bcp-maintenance':                            'RefreshCw',

  // ── Engineering sub-page capabilities ────────────────────────────────────────
  // Network Engineering
  'ne-design':                                  'PenTool',
  'ne-optimization':                            'Gauge',
  'ne-security':                                'ShieldCheck',
  'ne-vendor-agnostic':                         'Boxes',
  'ne-compliance':                              'BadgeCheck',
  'ne-managed-support':                         'Headphones',
  // VoIP & Unified Communications
  'voip-phone-system':                          'Phone',
  'voip-uc-integration':                        'MessageSquare',
  'voip-remote-enablement':                     'Globe',
  'voip-security':                              'ShieldCheck',
  'voip-network-optimization':                  'Gauge',
  'voip-management-support':                    'Headphones',
  // Security Event Remediation & IP Protection
  'ser-incident-response':                      'Siren',
  'ser-vulnerability-remediation':              'ScanSearch',
  'ser-malware-recovery':                       'ShieldX',
  'ser-ip-protection':                          'Lock',
  'ser-hardening':                              'ShieldCheck',
  'ser-policy-compliance':                      'ClipboardCheck',
  // ITAD
  'itad-data-destruction':                      'FileX2',
  'itad-asset-removal':                         'Unplug',
  'itad-vendor-neutral':                        'Boxes',
  'itad-recycling':                             'Recycle',
  // IT Procurement
  'proc-assessment':                            'ClipboardCheck',
  'proc-implementation':                        'Rocket',
  'proc-support':                               'Headphones',
  'proc-compliance':                            'BadgeCheck',
  'proc-integration':                           'Boxes',
  'proc-lifecycle':                             'RefreshCw',
  // Systems Engineering
  'se-architecture':                            'PenTool',
  'se-server':                                  'Server',
  'se-virtualization':                          'Copy',
  'se-storage':                                 'Database',
  'se-resilience':                              'LifeBuoy',
  'se-integration':                             'GitMerge',

};
