// /lib/iconMap.ts
// Maps page slugs and service slugs to Lucide React icon names.
// Used by DynamicIcon component — never hardcode icon names in page files.
// Fallback icon: 'Cpu' renders if slug not found.

export const iconMap: Record<string, string> = {

  // ── Managed IT ─────────────────────────────────────────────────────────────
  'managed-it-services':                        'Server',
  'managed-network-services':                   'Network',
  'helpdesk':                                   'Headphones',
  'raleigh-it-helpdesk':                        'Headphones',
  'server-monitoring-and-maintenance':          'Activity',
  'backup-disaster-recovery':                   'HardDrive',
  'asset-lifecycle-management':                 'Package',
  'remote-it-support':                          'MonitorSmartphone',
  'it-staff-augmentation':                      'Users',
  'employee-onboarding-offboarding':            'UserPlus',
  'it-procurement':                             'ShoppingCart',

  // ── Cybersecurity ───────────────────────────────────────────────────────────
  'cybersecurity':                              'Shield',
  'fully-managed-cybersecurity':                'ShieldCheck',
  'managed-soc':                                'Eye',
  'siem-services':                              'Radio',
  'mdr-monitoring-and-response':                'ScanEye',
  'network-security':                           'Lock',
  'endpoint-security':                          'Laptop',
  'managed-firewall':                           'Flame',
  'ids-ips':                                    'Radar',
  'email-security':                             'MailWarning',
  'cyber-risk-assessment':                      'TriangleAlert',
  'penetration-testing-services':               'Bug',
  'security-audits-compliance':                 'ClipboardCheck',
  'compliance-management':                      'BadgeCheck',
  'zero-trust-security':                        'KeyRound',
  'cloud-cybersecurity':                        'CloudLock',
  'security-event-remediation-ip-protection':   'ShieldAlert',
  'it-security-assessment':                     'ScanSearch',

  // ── Cloud ───────────────────────────────────────────────────────────────────
  'cloud-services':                             'Cloud',
  'managed-cloud-services':                     'CloudCog',
  'cloud-migration':                            'CloudUpload',
  'cloud-hosting':                              'Server',
  'public-hybrid-cloud-services':               'Layers',
  'private-cloud-services':                     'Lock',
  'aws-services':                               'Boxes',
  'virtualization-services':                    'Copy',
  'managed-desktop-vdi':                        'Monitor',
  'cloud-consulting-services':                  'CloudSun',

  // ── Strategy & Consulting ───────────────────────────────────────────────────
  'it-management-consulting':                   'BarChart3',
  'vcio-vcto-vciso-services':                   'BarChart3',
  'fractional-cto-services':                    'Compass',
  'it-roadmap-planning':                        'Map',
  'it-assessments-strategies':                  'ClipboardList',
  'it-audits-and-assessments':                  'ClipboardList',
  'tech-due-diligence-for-businesses':          'SearchCheck',
  'it-due-diligence-mergers-acquisitions':      'GitMerge',
  'technical-project-management':               'Kanban',
  'it-roi-assessment':                          'TrendingUp',
  'business-continuity-planning':               'RefreshCw',
  'it-strategy-services':                       'Compass',
  'maximize-roi-with-managed-it-services':      'TrendingUp',

  // ── Microsoft Solutions ─────────────────────────────────────────────────────
  'microsoft-solutions':                        'Layout',
  'services-for-the-microsoft-suite':           'Layout',
  'microsoft-365-services':                     'Grid3X3',
  'microsoft-azure-services':                   'Layers',
  'microsoft-teams-services':                   'MessageSquare',
  'microsoft-exchange-services':                'Mail',
  'microsoft-sharepoint-services':              'FolderOpen',
  'microsoft-copilot':                          'Sparkles',
  'microsoft-copilot-implementation':           'Sparkles',
  'microsoft-sentinel':                         'ScanSearch',

  // ── Engineering ─────────────────────────────────────────────────────────────
  'network-engineering':                        'Cable',
  'systems-engineering':                        'Cpu',
  'voip-unified-communications':                'Phone',
  'itad':                                       'Recycle',
  'services-itad':                              'Recycle',

  // ── AI & Automation ─────────────────────────────────────────────────────────
  'ai-automation':                              'Brain',
  'ai-governance':                              'ShieldCheck',
  'ai-readiness-assessment':                    'Brain',
  'ai-strategy-consulting':                     'Lightbulb',
  'healthcare-ai-services':                     'HeartPulse',
  'process-automation':                         'Workflow',
  'roi-calculator':                             'Calculator',
  'compare-msps':                               'BarChart2',

  // ── Industries — by vertical ────────────────────────────────────────────────
  'healthcare-managed-it-services':             'Stethoscope',
  'custom-it-network-services-healthcare-institutions': 'Stethoscope',
  'pharma-med-tech-it-services':                'FlaskConical',
  'banking-and-financial-services-it':          'Landmark',
  'legal-and-law-firm-it-services':             'Scale',
  'accounting-firm-it-services':                'Receipt',
  'manufacturing-it':                           'Factory',
  'education-it-services':                      'GraduationCap',
  'professional-it-services':                   'Briefcase',
  'construction-it-services':                   'HardHat',
  'non-profit-it-services':                     'Heart',
  'transportation-logistics-it-services':       'Truck',
  'real-estate-it-services':                    'Building2',
  'marketing-it-services':                      'Megaphone',
  'government-it-services':                     'Building',
  'government-contractor-it-services':          'Building',
  'private-equity-it-services':                 'TrendingUp',
  'dealership-and-automotive-it-services':      'Car',
  'retail-it-services':                         'Store',

  // ── Industries — by size ────────────────────────────────────────────────────
  'small-business':                             'Store',
  'mid-sized-business':                         'Building',
  'large-business-it-services':                 'Building2',
  'enterprise-managed-it-services':             'Landmark',

  // ── Resources ───────────────────────────────────────────────────────────────
  'resource-center':                            'BookOpen',
  'white-papers':                               'FileText',
  'case-studies':                               'Award',
  'blog':                                       'Rss',

  // ── About ────────────────────────────────────────────────────────────────────
  'about-us':                                   'Users',
  'process':                                    'GitBranch',
  'partners':                                   'Handshake',
  'contact-us':                                 'Phone',
  'request-our-pricing-guide':                  'FileText',
  'value-integrity':                            'Handshake',
  'value-team':                                 'Users',
  'value-results':                              'Trophy',

  // ── City service-page capabilities ───────────────────────────────────────────
  'remote-monitoring':                          'Activity',
  'cyber-security-management':                  'ShieldCheck',
  'help-desk-services':                         'Headphones',
  'advanced-engineering':                       'Cog',
  'custom-slas':                                'FileCheck',
  'preventative-maintenance':                   'Wrench',
  'cloud-computing':                            'Cloud',
  'it-automation':                              'Workflow',
  'disaster-recovery':                          'LifeBuoy',
  'network-security-services':                  'Lock',
  'vulnerability-management':                   'ShieldAlert',
  'it-project-management':                      'ClipboardList',

  // ── City cyber-security-page capabilities ────────────────────────────────────
  'cyber-threat-solutions':                     'ShieldCheck',
  'security-architecture':                      'Network',
  'security-awareness-training':                'GraduationCap',
  'risk-management':                            'TriangleAlert',
  'strategic-security-consulting':              'Compass',

  // ── Managed IT sub-page capabilities ─────────────────────────────────────────
  // Managed Network Services
  'network-design-support':                     'Network',
  'flexible-outsourcing':                       'Shuffle',
  'proactive-network-monitoring':               'Activity',
  'network-expertise':                          'Award',
  'full-service-network':                       'Layers',
  // Server Monitoring & Maintenance
  'server-monitoring-response':                 'Activity',
  'server-maintenance-optimization':            'Wrench',
  'server-security-hardening':                  'ShieldCheck',
  'server-backup-recovery':                     'HardDrive',
  'server-capacity-planning':                   'TrendingUp',
  'server-troubleshooting':                     'Search',
  // Backup & Disaster Recovery
  'automated-backups':                          'DatabaseBackup',
  'fast-disaster-recovery':                     'LifeBuoy',
  'cloud-onprem-backup':                        'CloudCog',
  'ransomware-protection':                      'ShieldAlert',
  'bdr-compliance-support':                     'BadgeCheck',
  // Asset Lifecycle Management
  'site-assessment':                            'ClipboardCheck',
  'hardware-maintenance':                       'Wrench',
  'inventory-auditing':                         'ClipboardList',
  'certified-data-destruction':                 'FileX2',
  'de-installation':                            'Unplug',
  'relocation-services':                        'Truck',
  'ewaste-recycling':                           'Recycle',
  // Server Administration & Support
  'hardware-software-support':                  'Wrench',
  'end-user-assistance':                        'Headphones',
  'server-security':                            'ShieldCheck',
  'continuous-server-monitoring':               'Activity',
  'server-deployments':                         'ServerCog',
  'cloud-support':                              'Cloud',
  // Remote IT Support
  'rapid-remote-resolution':                    'Zap',
  'remote-helpdesk':                            'Headphones',
  'remote-patch-management':                    'RefreshCw',
  'endpoint-management':                        'Laptop',
  'remote-security-monitoring':                 'ShieldCheck',
  'distributed-team-support':                   'Globe',
  // IT Staff Augmentation
  'embedded-engineers':                         'UserCog',
  'project-surge-support':                      'TrendingUp',
  'specialized-skills':                         'Award',
  'flexible-engagement':                        'Shuffle',
  'managed-handoff':                            'GitBranch',
  'scalable-capacity':                          'Scaling',
  // Employee Onboarding & Offboarding
  'account-provisioning':                       'UserPlus',
  'device-setup':                               'Laptop',
  'access-management':                          'KeyRound',
  'secure-offboarding':                         'UserMinus',
  'data-handover':                              'FolderInput',
  'license-recovery':                           'Receipt',
  // Onsite IT Support
  'onsite-dispatch':                            'Truck',
  'hardware-installation':                      'Wrench',
  'network-cabling':                            'Cable',
  'hands-on-troubleshooting':                   'Search',
  'office-moves':                               'Building2',
  'scheduled-onsite-visits':                    'CalendarClock',

  // ── Cybersecurity sub-page capabilities ──────────────────────────────────────
  // Fully-Managed Cybersecurity
  'intrusion-detection-prevention':             'ShieldAlert',
  'network-security-managed':                   'Network',
  'endpoint-security-managed':                  'Laptop',
  'vulnerability-assessments':                  'ScanSearch',
  'email-security-managed':                     'MailWarning',
  'firewall-config-monitoring':                 'Flame',
  // Managed SOC
  'soc-detection-response':                     'Eye',
  'managed-siem':                               'Radio',
  'intrusion-detection-system':                 'Radar',
  'endpoint-detection-response':                'ScanEye',
  'vulnerability-scanning':                     'ScanSearch',
  'behavioral-monitoring':                      'Activity',
  // MDR
  'mdr-threat-detection':                       'ScanEye',
  'threat-hunting':                             'Crosshair',
  'incident-response':                          'Siren',
  'flexible-security-services':                 'Shuffle',
  'security-integration':                       'Boxes',
  // Penetration Testing
  'comprehensive-pen-testing':                  'Bug',
  'physical-security-assessment':               'DoorClosed',
  'social-engineering-assessment':              'UserX',
  'cloud-pen-testing':                          'CloudCog',
  'compliance-checks':                          'ClipboardCheck',
  'transparent-reporting':                      'FileText',
  // Email Security
  'anti-phishing':                              'Fish',
  'malware-blocking':                           'ShieldX',
  'account-takeover-prevention':                'LockKeyhole',
  'email-monitoring':                           'MailCheck',
  'email-incident-response':                    'Siren',
  // Security Audits & Compliance
  'cyber-risk-assessments':                     'TriangleAlert',
  'regulatory-compliance-audits':               'BadgeCheck',
  'pentest-vuln-scanning':                      'Bug',
  'security-policy-review':                     'FileCheck',
  'cloud-security-assessment':                  'CloudLock',
  'incident-response-planning':                 'LifeBuoy',
  // IDS/IPS
  'ai-antimalware':                             'Bot',
  'content-filtering':                          'Filter',
  'secure-web-gateway':                         'Globe',
  'ai-machine-learning':                        'BrainCircuit',
  'realtime-detection-mitigation':              'Zap',
  'reporting-analysis':                         'BarChart3',
  // Cybersecurity Consulting
  'managed-detection-response':                 'ScanEye',
  'firewall-management':                        'Flame',
  'web-app-testing':                            'Code',
  'awareness-training':                         'GraduationCap',
  'vciso-services':                             'UserCog',
  // SIEM Services
  'log-collection-correlation':                 'ScrollText',
  'realtime-threat-detection':                  'Zap',
  'siem-alerting':                              'BellRing',
  'threat-intelligence':                        'Globe',
  'compliance-reporting':                       'FileText',
  'siem-managed-response':                      'Siren',
  // Network Security
  'firewall-protection':                        'Flame',
  'network-segmentation':                       'Network',
  'intrusion-prevention':                       'ShieldAlert',
  'secure-remote-access':                       'KeyRound',
  'wifi-security':                              'Wifi',
  'network-monitoring-security':                'Activity',
  // Endpoint Security
  'edr':                                        'ScanEye',
  'next-gen-antivirus':                         'ShieldCheck',
  'device-encryption':                          'Lock',
  'patch-management-security':                  'RefreshCw',
  'application-control':                        'AppWindow',
  'mobile-device-security':                     'Smartphone',
  // Managed Firewall
  'firewall-configuration':                     'Settings',
  'firewall-monitoring':                        'Activity',
  'rule-management':                            'ListChecks',
  'threat-prevention-firewall':                 'ShieldAlert',
  'firewall-updates':                           'RefreshCw',
  'firewall-reporting':                         'FileText',
  // Cyber Risk Assessment
  'risk-discovery':                             'Search',
  'vulnerability-identification':               'ScanSearch',
  'threat-modeling':                            'Crosshair',
  'compliance-gap-analysis':                    'ClipboardList',
  'risk-prioritization':                        'ListChecks',
  'remediation-roadmap':                        'Map',
  // Cloud Cybersecurity
  'cloud-config-management':                    'CloudCog',
  'cloud-identity-access':                      'KeyRound',
  'cloud-data-protection':                      'CloudLock',
  'cloud-threat-monitoring':                    'ScanEye',
  'cloud-compliance':                           'BadgeCheck',
  'cloud-backup-resilience':                    'DatabaseBackup',
  // Zero Trust Security
  'identity-verification':                      'Fingerprint',
  'mfa':                                        'KeyRound',
  'least-privilege-access':                     'Lock',
  'device-trust':                               'ShieldCheck',
  'microsegmentation':                          'Grid3X3',
  'continuous-verification':                    'RefreshCw',

};
