// Local-SEO (city / location) pages — every route that renders through
// CityServicePage. These aren't in the main nav (they're geo landing pages),
// so anything that needs the full set of city pages — like deciding where the
// calculator banner shows — reads it here. Paths are leading-slash, no
// trailing slash; normalize both sides before comparing.
//
// Keep in sync with the app/*/page.tsx files that import CityServicePage.
export const CITY_PATHS: readonly string[] = [
  '/apex-cyber-security-services',
  '/burlington-cyber-security-services',
  '/cary-cyber-security-services',
  '/chapel-hill-cyber-security-services',
  '/charlotte-cyber-security-services',
  '/charlotte-it-consulting',
  '/charlotte-it-helpdesk',
  '/charlotte-it-network-support',
  '/charlotte-it-outsourcing',
  '/durham-cyber-security-services',
  '/durham-it-consulting',
  '/fayetteville-cyber-security-services',
  '/garner-cyber-security-services',
  '/greensboro-it-consulting',
  '/hillsborough-cyber-security-services',
  '/it-company-durham',
  '/it-company-in-knightdale',
  '/it-company-raleigh',
  '/it-support-charlotte',
  '/it-support-durham',
  '/it-support-garner',
  '/it-support-greensboro',
  '/it-support-raleigh',
  '/it-support-rocky-mount',
  '/managed-it-services-apex',
  '/managed-it-services-burlington',
  '/managed-it-services-cary',
  '/managed-it-services-chapel-hill',
  '/managed-it-services-charlotte',
  '/managed-it-services-concord',
  '/managed-it-services-durham',
  '/managed-it-services-fayetteville',
  '/managed-it-services-gastonia',
  '/managed-it-services-greensboro',
  '/managed-it-services-high-point',
  '/managed-it-services-hillsborough',
  '/managed-it-services-huntersville',
  '/managed-it-services-raleigh',
  '/managed-it-services-rocky-mount',
  '/managed-it-services-rtp',
  '/managed-it-services-wilmington',
  '/managed-it-services-winston-salem',
  '/raleigh-cyber-security-services',
  '/raleigh-it-consulting',
  '/raleigh-it-helpdesk',
  '/raleigh-it-network-support',
  '/raleigh-it-outsourcing',
  '/rocky-mount-cyber-security-services',
  '/winston-salem-it-consulting',
  '/winston-salem-tech-it-support',
]
