// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —
// re-run the script if the live page content changes.
// Source: https://www.itsco.com/microsoft-sharepoint-services/
// Generated: 2026-05-21T13:37:02.267Z

export const SOURCE_URL = "https://www.itsco.com/microsoft-sharepoint-services"

export const SOURCE_PARAGRAPHS = [
  /* 00 */ "Microsoft SharePoint is a powerful platform for document management, collaboration, and workflow automation, but without expert guidance, businesses often face security risks, performance issues, and user adoption challenges.",
  /* 01 */ "ITSco’s Microsoft SharePoint support and services help businesses streamline operations, enhance security, and maximize productivity by ensuring a well-managed and fully optimized SharePoint environment.",
  /* 02 */ "Whether you need SharePoint Online support or on-premises management in the Raleigh, NC area, our team ensures seamless collaboration, uninterrupted access, and data security so your business can operate efficiently.",
  /* 03 */ "Seamlessly transition to SharePoint Online, hybrid, or on-premises environments with expert migration services that prevent data loss and reduce downtime.",
  /* 04 */ "ITSco provides 24/7 monitoring, proactive troubleshooting, and performance optimization to keep your SharePoint environment running smoothly.",
  /* 05 */ "Secure your SharePoint data with user access controls, permissions management, encryption, and regulation compliance support.",
  /* 06 */ "Enhance SharePoint functionality with seamless integration into Microsoft 365, Teams, Power Automate, and other third-party applications to optimize workflows.",
  /* 07 */ "Empower your employees with hands-on training, SharePoint best practices, and customized adoption strategies to maximize productivity.",
  /* 08 */ "Without proper SharePoint management and support, businesses face serious operational and security risks, including:",
  /* 09 */ "Weak access control policies can expose sensitive business data to unauthorized access and cyber threats.",
  /* 10 */ "Employees may find SharePoint difficult to use, leading to low engagement and inefficiencies.",
  /* 11 */ "SharePoint outages can disrupt daily operations without proactive monitoring.",
  /* 12 */ "A disorganized SharePoint structure can make it difficult for teams to find, share, and manage important files.",
  /* 13 */ "Poorly configured environments lead to lagging document retrieval and inefficient workflows.",
  /* 14 */ "A sloppy SharePoint setup can create an almost unusable environment, costing you money in the process.",
  /* 15 */ "With 25+ years of IT expertise, ITSco provides proactive SharePoint support and management.",
  /* 16 */ "Our solutions optimize workflows, enhance document collaboration, and improve business efficiency.",
  /* 17 */ "We help businesses reduce IT costs, improve SharePoint licensing, and eliminate inefficiencies.",
  /* 18 */ "ITSco’s experts provide around-the-clock assistance to prevent downtime and SharePoint disruptions.",
  /* 19 */ "Whether you need SharePoint migration, security enhancements, compliance management, or ongoing support, ITSco’s expert IT team ensures seamless integration, enhanced collaboration, and maximum productivity.",
] as const
