// Content for /microsoft-sharepoint-services/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Microsoft SharePoint Services & Support | ITSco',
    description:
      'ITSco Microsoft SharePoint services — deployment, migration, management, and security for a SharePoint environment that actually drives collaboration. Book a free consultation.',
    canonical: 'https://www.itsco.com/microsoft-sharepoint-services/',
  },
  serviceName: 'Microsoft SharePoint Services',
  hero: {
    eyebrow: 'Microsoft · SharePoint',
    headlineLead: 'Microsoft SharePoint,',
    headlineAccent: 'built to collaborate.',
    body: S[0],
    utmSuffix: 'microsoft-sharepoint-services-hero',
  },
  heroImage: {
    src: '/images/hero/services/pexels-divinetechygirl-1181745.jpg',
    alt: 'Team collaborating in a Microsoft SharePoint environment',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Accelerate collaboration, optimize',
    headlineAccent: 'your SharePoint environment.',
    paragraphs: [S[1], S[2]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years of IT and Microsoft expertise' },
    { value: '60%', label: 'Of our clients have stayed with us for 5+ years' },
  ],
  capabilitiesHeading: {
    eyebrow: 'Our SharePoint Services',
    headlineLead: 'SharePoint that works,',
    headlineAccent: 'end to end.',
  },
  capabilities: [
    {
      slug: 'sharepoint-deployment-migration',
      title: 'SharePoint Deployment & Migration',
      description: S[3],
    },
    { slug: 'sharepoint-management-support', title: 'Management & Support', description: S[4] },
    { slug: 'sharepoint-security-compliance', title: 'SharePoint Security & Compliance', description: S[5] },
    { slug: 'sharepoint-integration-customization', title: 'Integration & Customization', description: S[6] },
    { slug: 'sharepoint-training-adoption', title: 'User Training & Adoption Support', description: S[7] },
  ],
  outcomes: {
    tone: 'risk',
    eyebrow: 'The Risk',
    headlineLead: 'The cost of inexperienced',
    headlineAccent: 'SharePoint support.',
    paragraphs: [],
    bullets: [S[9], S[10], S[11], S[12], S[13], S[14]],
    image: {
      src: '/images/supporting/services/windows-AigsWJmvoEo-unsplash.jpg',
      alt: 'Microsoft collaboration and productivity environment',
    },
  },
  related: {
    heading: 'Explore more Microsoft services',
    links: [
      {
        slug: 'microsoft-365-services',
        label: 'Microsoft 365 Services',
        href: '/microsoft-365-services/',
        description: 'Deployment, management, and security across the full Microsoft 365 suite.',
      },
      {
        slug: 'microsoft-teams-services',
        label: 'Microsoft Teams Services',
        href: '/microsoft-teams-services/',
        description: 'Teams set up and managed as a real collaboration and communication hub.',
      },
      {
        slug: 'microsoft-solutions',
        label: 'Microsoft Solutions Overview',
        href: '/microsoft-solutions/',
        description: 'The full ITSco Microsoft program — 365, Azure, Teams, and more.',
      },
    ],
  },
  bookingUtm: 'microsoft-sharepoint-services-bottom',
}
