// Content for /raleigh-it-outsourcing/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'IT Outsourcing in Raleigh, NC | ITSco',
    description:
      'ITSco delivers IT outsourcing in Raleigh, NC — executive consulting, cloud, security, network engineering, and compliance that maximize your IT ROI. Book a free consultation.',
    canonical: 'https://www.itsco.com/raleigh-it-outsourcing/',
  },
  officeLocation: 'raleigh',
  hero: {
    eyebrow: 'IT Outsourcing · Raleigh, NC',
    headlineLead: 'IT outsourcing in Raleigh that',
    headlineAccent: 'empowers your team to achieve more.',
    body: S[0],
    utmSuffix: 'it-outsourcing-raleigh-hero',
  },
  heroImage: {
    src: '/images/supporting/services/group-people-working-out-business-plan-office.jpg',
    alt: 'IT outsourcing team supporting a Raleigh business',
  },
  capabilitiesHeading: {
    eyebrow: 'Comprehensive IT Outsourcing',
    headlineLead: 'IT outsourcing services',
    headlineAccent: 'for Raleigh, NC businesses.',
  },
  capabilities: [
    { slug: 'strategic-security-consulting', title: 'Executive Consulting', description: S[5] },
    { slug: 'cloud-computing', title: 'Cloud Services', description: S[6] },
    { slug: 'cyber-security-management', title: 'Security Assessments', description: S[7] },
    { slug: 'network-security-services', title: 'Network Engineering', description: S[8] },
    { slug: 'help-desk-services', title: 'Service Desk Support', description: S[9] },
    { slug: 'advanced-engineering', title: 'Systems Architecture', description: S[10] },
    { slug: 'risk-management', title: 'Risk & Disaster Recovery', description: S[11] },
    { slug: 'it-automation', title: 'IT Automation', description: S[12] },
    { slug: 'custom-slas', title: 'Compliance Support', description: S[13] },
  ],
  positioning: {
    eyebrow: 'Real Value for Your Business',
    headlineLead: 'IT outsourcing built on',
    headlineAccent: 'three generations of expertise.',
    paragraphs: [S[14], S[15], S[16]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years serving businesses across Raleigh & RTP' },
    { value: '0%', label: 'Of our clients have experienced a serious security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'A trusted IT outsourcing firm',
    headlineAccent: 'Raleigh businesses rely on.',
    paragraphs: [S[21], S[22], S[25], S[26], S[27]],
    image: {
      src: '/images/hero/local/raleigh2.jpg',
      alt: 'Raleigh, North Carolina cityscape',
    },
  },
  security: {
    eyebrow: 'Data Protection',
    headlineLead: 'Unwavering protection',
    headlineAccent: 'against data breaches.',
    paragraphs: [S[20], S[38], S[39]],
    image: {
      src: '/images/hero/local/raleigh3.jpg',
      alt: 'Raleigh, North Carolina at dusk',
    },
  },
  bookingUtm: 'it-outsourcing-raleigh-bottom',
}
