// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —
// re-run the script if the live page content changes.
// Source: https://www.itsco.com/process/
// Generated: 2026-05-15T18:40:51.279Z

export const SOURCE_URL = "https://www.itsco.com/process"

export const SOURCE_PARAGRAPHS = [
  /* 00 */ "We listen. We plan. We communicate. We deliver.",
  /* 01 */ "ITSco’s Professional Services combine the best engineers with the most appropriate technologies and a proven process for successful delivery. While we are never rigid or inflexible, we have learned that consistency requires some structure. Our roadmap for successful projects includes:",
  /* 02 */ "Ensure maximum security and uptime for your business by partnering with ITSco to build a proactive organization that relies on 24×7 monitoring coupled with an aggressive preventative maintenance program to manage devices, networks, users, desktops and data.",
  /* 03 */ "We start our Managed Services engagements (both MSP and MSSP) with a thorough assessment in order to understand your technical infrastructure and your business objectives. From there, we will:",
  /* 04 */ "With the information provided by our management tools and processes, our experts can continuously analyze and optimize your systems for performance and security, providing a strategic approach to Information Technology and Information Security – all managed by a true IT partner.",
] as const
