// Content for /process/
//
// Verbatim copy lives in ./_source.ts (auto-generated by
// scripts/sync-content.mjs). Step bullets are sourced from the live
// page's structured lists; group structure mirrors how the steps
// flow on itsco.com/process/.

import { SOURCE_PARAGRAPHS } from './_source'

export const META = {
  title: 'Our Process | ITSco — Delivering IT Without Pretense or Drama',
  description: 'ITSco’s proven process for delivering Professional Services and Proactive Managed Services. We listen, plan, communicate, and deliver — every engagement.',
  canonical: 'https://www.itsco.com/process/',
}

export const HERO = {
  eyebrow: 'Our Process',
  headlineLead: 'Delivering advanced IT services',
  headlineAccent: 'without pretense or drama.',
  body: SOURCE_PARAGRAPHS[0],
  utmSuffix: 'process-hero',
  stat: '25+',
  statLabel: 'Years of refining our process',
}

export const PROFESSIONAL_SERVICES = {
  eyebrow: 'Professional Services',
  headlineLead: 'A proven roadmap for',
  headlineAccent: 'successful delivery.',
  intro: SOURCE_PARAGRAPHS[1],
  steps: [
    {
      title: 'Discovery & Requirements',
      bullets: [
        'Document technical requirements and understand business objectives',
        'Perform discovery and analysis',
        'Create high-level project plans and define deliverables',
        'Define criteria of success',
      ],
    },
    {
      title: 'Detailed Planning',
      bullets: [
        'Creation of detailed Project Plan including dates, milestones & deliverables',
        'Creation of detailed Engineering Plan including specs and costs',
        'Review, iterate and win approval',
      ],
    },
    {
      title: 'Implementation',
      bullets: [
        'Careful implementation per Project Plan',
        'Constant, clear and concise communications',
      ],
    },
    {
      title: 'Validation & Handoff',
      bullets: [
        'Validation of functional and operational success per specs',
        'Presentation of thorough documentation per requirements',
      ],
    },
    {
      title: 'Review',
      bullets: [
        'Review project process and results',
        'Review and evaluate measures of success',
      ],
    },
  ],
}

export const MANAGED_SERVICES = {
  eyebrow: 'Proactive Managed Services',
  headlineLead: '24×7 monitoring and an aggressive',
  headlineAccent: 'preventative maintenance program.',
  intro: SOURCE_PARAGRAPHS[2],
  approach: SOURCE_PARAGRAPHS[3],
  capabilities: [
    'A sophisticated remote monitoring and management (RMM) system that our engineers use to monitor systems and address problems proactively.',
    'Patch Management and preventative maintenance',
    'A Helpdesk team that is available to assist with all your support needs',
    'Continuous (24×7) collection and analysis of logs from virtually any device',
    'Threat Intelligence (TI) integrated from multiple trusted sources',
    'Monitoring provided by SOC 2 Type II certified security operations center',
  ],
  closing: SOURCE_PARAGRAPHS[4],
}

