// Content for /microsoft-exchange-services/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).
// The "Email Security & Compliance" capability description is a verbatim
// literal — the sync extractor missed that card; copy supplied from the live page.

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Microsoft Exchange Services | Email Migration & Management | ITSco',
    description:
      'ITSco Microsoft Exchange services — secure deployment, migration, management, and optimization of your business email environment. Book a free consultation.',
    canonical: 'https://www.itsco.com/microsoft-exchange-services/',
  },
  serviceName: 'Microsoft Exchange Services',
  hero: {
    eyebrow: 'Microsoft · Exchange',
    headlineLead: 'Microsoft Exchange,',
    headlineAccent: 'expertly managed.',
    body: S[0],
    utmSuffix: 'microsoft-exchange-services-hero',
  },
  heroImage: {
    src: '/images/hero/services/ed-hardie-xG02JzIBf7o-unsplash.jpg',
    alt: 'Microsoft Exchange business email environment',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Secure, reliable business email,',
    headlineAccent: 'without the IT burden.',
    paragraphs: [S[1], S[2]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years of IT and Microsoft expertise' },
    { value: '60%', label: 'Of our clients have stayed with us for 5+ years' },
  ],
  capabilitiesHeading: {
    eyebrow: 'Our Exchange Services',
    headlineLead: 'Email infrastructure,',
    headlineAccent: 'handled end to end.',
  },
  capabilities: [
    {
      slug: 'exchange-deployment-migration',
      title: 'Exchange Deployment & Migration',
      description: S[3],
    },
    { slug: 'exchange-management-support', title: 'Exchange Management & Support', description: S[4] },
    {
      slug: 'exchange-security-compliance',
      title: 'Email Security & Compliance',
      description:
        'Protect business communications with advanced threat protection, anti-spam filtering, multi-factor authentication, encryption, and regulatory compliance support (HIPAA, NIST, GDPR).',
    },
    { slug: 'exchange-integrations', title: 'Microsoft Integrations', description: S[5] },
    { slug: 'exchange-training-support', title: 'User Training & Support', description: S[6] },
  ],
  outcomes: {
    tone: 'risk',
    eyebrow: 'The Risk',
    headlineLead: 'The challenges of managing Exchange',
    headlineAccent: 'without expert support.',
    paragraphs: [],
    bullets: [S[8], S[9], S[10], S[11], S[12]],
    image: {
      src: '/images/supporting/services/windows-AigsWJmvoEo-unsplash.jpg',
      alt: 'Microsoft email and productivity environment',
    },
  },
  related: {
    heading: 'Explore more Microsoft services',
    links: [
      {
        slug: 'microsoft-365-services',
        label: 'Microsoft 365 Services',
        href: '/microsoft-365-services/',
        description: 'Deployment, management, and security across the full Microsoft 365 suite.',
      },
      {
        slug: 'microsoft-sharepoint-services',
        label: 'Microsoft SharePoint Services',
        href: '/microsoft-sharepoint-services/',
        description: 'Document management and collaboration, optimized and secured.',
      },
      {
        slug: 'microsoft-solutions',
        label: 'Microsoft Solutions Overview',
        href: '/microsoft-solutions/',
        description: 'The full ITSco Microsoft program — 365, Azure, Teams, and more.',
      },
    ],
  },
  bookingUtm: 'microsoft-exchange-services-bottom',
}
