// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —
// re-run the script if the live page content changes.
// Source: https://www.itsco.com/network-engineering/
// Generated: 2026-05-21T14:32:22.118Z

export const SOURCE_URL = "https://www.itsco.com/network-engineering/"

export const SOURCE_PARAGRAPHS = [
  /* 00 */ "Drive business growth with a modern, secure, high-performance network designed and implemented by ITSco’s expert engineering team.",
  /* 01 */ "Our network engineering solutions combine decades of experience with the latest security practices to deliver networks that grow with your business.",
  /* 02 */ "With decades of experience and a commitment to excellence, ITSco delivers customized network engineering solutions designed to meet your specific goals.",
  /* 03 */ "We analyze your needs and design scalable network solutions, from wired and wireless access to cloud and hybrid architectures.",
  /* 04 */ "Optimize your network’s performance with advanced tuning and capacity planning, ensuring minimal downtime and seamless scalability.",
  /* 05 */ "Our engineers implement multi-tiered security strategies, integrating advanced tools like SASE and SD-WAN to protect critical systems and data.",
  /* 06 */ "We work with all major networking equipment vendors, providing best-of-breed solutions and seamlessly integrating multi-vendor environments.",
  /* 07 */ "Our team assists with audits and ensures your network meets applicable regulatory requirements, reducing business risks and safeguarding your reputation.",
  /* 08 */ "Our network engineering team can work hand-in-glove with our in-house service desk to offer ongoing managed network support services .",
  /* 09 */ "Businesses rely on robust network infrastructures to power their operations, but many face significant challenges:",
  /* 10 */ "Aging network architectures can reduce productivity and complicate IT management.",
  /* 11 */ "Inadequate defenses leave networks and data exposed to cyber threats.",
  /* 12 */ "Networks not designed for growth struggle to meet increasing demands.",
  /* 13 */ "Insufficient capacity and poor optimization lead to downtime and slow system performance.",
  /* 14 */ "designing and implementing robust networks.",
  /* 15 */ "custom-designed to meet your business needs.",
  /* 16 */ "and experienced across all major platforms.",
  /* 17 */ "approach that incorporates cutting-edge best practices.",
  /* 18 */ "Empower your business with ITSco’s Network Engineering Services. From designing scalable networks to securing your infrastructure, our expert team delivers solutions that drive growth, innovation, and resilience.",
] as const
