// Content for /network-engineering/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Network Engineering Services',
    description:
      'ITSco network engineering — modern, secure, high-performance networks designed and implemented by an expert engineering team. Book a free consultation.',
    canonical: 'https://www.itsco.com/network-engineering/',
  },
  serviceName: 'Network Engineering',
  parent: { name: 'Managed IT Services', href: '/managed-it-services/' },
  hero: {
    eyebrow: 'Engineering · Network Engineering',
    headlineLead: 'Networks engineered',
    headlineAccent: 'to drive growth.',
    body: S[0],
    utmSuffix: 'network-engineering-hero',
  },
  heroImage: {
    src: '/images/hero/services/pexels-field-engineer-147254-442150.jpg',
    alt: 'ITSco network engineer building network infrastructure',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Transform your infrastructure with',
    headlineAccent: 'expert network engineering.',
    paragraphs: [S[1], S[2]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years designing and implementing networks' },
    { value: '60%', label: 'Of our clients have stayed with us for 5+ years' },
  ],
  capabilitiesHeading: {
    eyebrow: 'Comprehensive Network Engineering',
    headlineLead: 'Networks built for',
    headlineAccent: 'performance and growth.',
  },
  capabilities: [
    {
      slug: 'ne-design',
      title: 'Tailored Network Design and Implementation',
      description: S[3],
    },
    {
      slug: 'ne-optimization',
      title: 'Performance Optimization and Capacity Planning',
      description: S[4],
    },
    { slug: 'ne-security', title: 'Comprehensive Security Solutions', description: S[5] },
    { slug: 'ne-vendor-agnostic', title: 'Vendor-Agnostic Expertise', description: S[6] },
    { slug: 'ne-compliance', title: 'Regulatory Compliance Support', description: S[7] },
    {
      slug: 'ne-managed-support',
      title: 'Flexible Managed Support Options',
      description: S[8],
    },
  ],
  outcomes: {
    eyebrow: 'The Risk',
    headlineLead: 'Outdated networks',
    headlineAccent: 'holding you back?',
    paragraphs: [],
    tone: 'risk',
    bullets: [S[10], S[11], S[12], S[13]],
    image: {
      src: '/images/hero/services/pexels-cookiecutter-19166565.jpg',
      alt: 'Structured network cabling infrastructure',
    },
  },
  related: {
    heading: 'Explore more engineering services',
    links: [
      {
        slug: 'systems-engineering',
        label: 'Systems Engineering',
        href: '/systems-engineering/',
        description: 'Server and systems architecture engineered for reliability and scale.',
      },
      {
        slug: 'voip-unified-communications',
        label: 'VoIP & Unified Communications',
        href: '/voip-unified-communications/',
        description: 'Secure, scalable business voice and collaboration solutions.',
      },
      {
        slug: 'managed-network-services',
        label: 'Managed Network Services',
        href: '/managed-network-services/',
        description: 'Ongoing monitoring, management, and support for your network.',
      },
    ],
  },
  bookingUtm: 'network-engineering-bottom',
}
