// Content for /fully-managed-cybersecurity/
//
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).
// Hero/intro framing is composed — the live Elementor page has no standalone
// hero paragraph. Capability descriptions and FAQs are verbatim.

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Fully-Managed Cybersecurity Services | MSSP',
    description:
      'ITSco fully-managed cybersecurity — 24/7 monitoring, threat detection, and response across your entire environment. Book a free consultation.',
    canonical: 'https://www.itsco.com/fully-managed-cybersecurity',
  },
  serviceName: 'Fully-Managed Cybersecurity',
  parent: { name: 'Cybersecurity & Compliance', href: '/cybersecurity/' },
  hero: {
    eyebrow: 'Cybersecurity · Fully Managed',
    headlineLead: 'Fully-managed cybersecurity,',
    headlineAccent: 'done right.',
    body: 'Round-the-clock monitoring, threat detection, and response across your entire IT environment — so your team can focus on the business while ITSco keeps it secure.',
    utmSuffix: 'fully-managed-cybersecurity-hero',
  },
  heroImage: {
    src: '/images/hero/services/pexels-divinetechygirl-1181320.jpg',
    alt: 'ITSco security specialist working beside a monitored server room',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Comprehensive cybersecurity,',
    headlineAccent: 'managed end to end.',
    paragraphs: [S[38]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years as a trusted IT services provider' },
    { value: '60%', label: 'Of our clients have stayed with us for 5+ years' },
  ],
  capabilitiesHeading: {
    eyebrow: 'End-to-End Cybersecurity Services',
    headlineLead: 'Every layer of your defense,',
    headlineAccent: 'under one program.',
  },
  capabilities: [
    { slug: 'intrusion-detection-prevention', title: 'Intrusion Detection & Prevention', description: S[5] },
    { slug: 'network-security-managed', title: 'Network Security', description: S[8] },
    { slug: 'endpoint-security-managed', title: 'Endpoint Security', description: S[12] },
    { slug: 'vulnerability-assessments', title: 'Vulnerability Assessments', description: S[16] },
    { slug: 'email-security-managed', title: 'Email Security', description: S[20] },
    { slug: 'firewall-config-monitoring', title: 'Firewall Configuration & Monitoring', description: S[24] },
  ],
  outcomes: {
    eyebrow: 'Resilience',
    headlineLead: 'Build attack-resistant',
    headlineAccent: 'business resilience.',
    paragraphs: [S[32], S[33], S[34]],
    image: {
      src: '/images/hero/services/pexels-divinetechygirl-1181341.jpg',
      alt: 'Security specialist with a tablet beside a managed server room',
    },
  },
  related: {
    heading: 'Explore more cybersecurity services',
    links: [
      {
        slug: 'managed-soc',
        label: 'Managed SOC',
        href: '/managed-soc/',
        description: 'A 24/7 security operations center watching your environment around the clock.',
      },
      {
        slug: 'mdr-monitoring-and-response',
        label: 'MDR Monitoring & Response',
        href: '/mdr-monitoring-and-response/',
        description: 'Proactive threat hunting and rapid incident response, fully managed.',
      },
      {
        slug: 'cybersecurity',
        label: 'Cybersecurity Overview',
        href: '/cybersecurity/',
        description: 'The full ITSco MSSP program — every service, one trusted partner.',
      },
    ],
  },
  faqHeading: {
    eyebrow: 'FAQ',
    headlineLead: 'Fully-managed cybersecurity,',
    headlineAccent: 'answered.',
  },
  faqs: [
    { question: S[42], answer: [S[43]] },
    { question: S[44], answer: [S[45]] },
    { question: S[46], answer: [S[47]] },
    { question: S[48], answer: [S[49]] },
    { question: S[50], answer: [S[51]] },
  ],
  bookingUtm: 'fully-managed-cybersecurity-bottom',
}
