// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —
// re-run the script if the live page content changes.
// Source: https://www.itsco.com/about-us/
// Generated: 2026-05-15T18:40:46.805Z

export const SOURCE_URL = "https://www.itsco.com/about-us"

export const SOURCE_PARAGRAPHS = [
  /* 00 */ "Join the growing list of businesses that have found the answer to that challenge by partnering with the ITSco team.",
  /* 01 */ "ITSco is proud to have an IT services team that includes some of the most creative, dedicated, and experienced engineers in the business.",
  /* 02 */ "And we are equally proud to live by a business model that is founded on trust. Trust amongst our team members – and trust between each of us and our customers.",
  /* 03 */ "ITSco has flourished as a provider of IT Services for over 25 years. Our reputation is built upon honesty, engineering excellence, and a dedication to customer service. And our success depends on repeat business, long-term relationships, and the referrals of satisfied customers.",
] as const
