// Content for /public-hybrid-cloud-services/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).
// Hero framing is composed — the live Elementor page has no standalone hero
// paragraph. Capability descriptions and FAQs are verbatim.

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Public & Hybrid Cloud Services',
    description:
      'ITSco public and hybrid cloud services — the scalability of public cloud and the control of private, designed and managed around your workloads. Book a free consultation.',
    canonical: 'https://www.itsco.com/public-hybrid-cloud-services',
  },
  serviceName: 'Public & Hybrid Cloud Services',
  parent: { name: 'Cloud Services', href: '/cloud-services/' },
  hero: {
    eyebrow: 'Cloud · Public & Hybrid',
    headlineLead: 'Public and hybrid cloud,',
    headlineAccent: 'built around your business.',
    body: 'Get the scalability of public cloud and the control of private — combined. ITSco designs, deploys, and manages a public/hybrid cloud that fits your workloads and your budget.',
    utmSuffix: 'public-hybrid-cloud-hero',
  },
  heroImage: {
    src: '/images/hero/services/pexels-ipsita-premnath-132130033-10285889.jpg',
    alt: 'Modern towers representing scalable public and hybrid cloud',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Boost business agility with',
    headlineAccent: 'cloud solutions.',
    paragraphs: [S[28], S[29], S[30]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years as a trusted IT services provider' },
    { value: '60%', label: 'Of our clients have stayed with us for 5+ years' },
  ],
  capabilitiesHeading: {
    eyebrow: 'Our Public & Hybrid Cloud Solutions',
    headlineLead: 'The right cloud model for',
    headlineAccent: 'every workload.',
  },
  capabilities: [
    { slug: 'public-cloud', title: 'Public Cloud', description: S[5] },
    { slug: 'cloud-disaster-recovery', title: 'Disaster Recovery', description: S[9] },
    { slug: 'hybrid-cloud', title: 'Hybrid Cloud', description: S[13] },
    { slug: 'cloud-devops', title: 'Cloud for DevOps', description: S[17] },
    { slug: 'cloud-big-data', title: 'Cloud for Big Data', description: S[21] },
    { slug: 'cloud-cost-management', title: 'Cloud Cost Management', description: S[24] },
  ],
  outcomes: {
    eyebrow: 'Why ITSco',
    headlineLead: 'Flexible, scalable solutions for',
    headlineAccent: 'unleashed potential.',
    paragraphs: [S[36], S[37], S[38], S[39]],
    image: {
      src: '/images/hero/services/pexels-cookiecutter-17489157.jpg',
      alt: 'Cloud server infrastructure',
    },
  },
  related: {
    heading: 'Explore more cloud services',
    links: [
      {
        slug: 'cloud-hosting',
        label: 'Cloud Hosting',
        href: '/cloud-hosting/',
        description: 'Reliable, scalable hosting for your applications and infrastructure.',
      },
      {
        slug: 'private-cloud-services',
        label: 'Private Cloud Services',
        href: '/private-cloud-services/',
        description: 'Dedicated, single-tenant cloud for sensitive workloads and tight control.',
      },
      {
        slug: 'cloud-services',
        label: 'Cloud Services Overview',
        href: '/cloud-services/',
        description: 'The full ITSco cloud program — migration, hosting, management, and more.',
      },
    ],
  },
  faqHeading: {
    eyebrow: 'FAQ',
    headlineLead: 'Public & hybrid cloud,',
    headlineAccent: 'answered.',
  },
  faqs: [
    { question: S[42], answer: [S[43], S[44], S[45]] },
    { question: S[46], answer: [S[47], S[48]] },
    { question: S[49], answer: [S[50], S[51], S[52]] },
    { question: S[53], answer: [S[54], S[55], S[56]] },
    { question: S[57], answer: [S[58], S[59], S[60]] },
  ],
  bookingUtm: 'public-hybrid-cloud-bottom',
}
