#!/usr/bin/env node
/**
 * Fetches verbatim paragraph copy from a live ITSco URL and writes it to a
 * sidecar `_source.ts` next to a page's `content.ts`. The page's `content.ts`
 * then imports `SOURCE_PARAGRAPHS` and references entries by index for hero
 * body, pillar paragraphs, and FAQ answers.
 *
 * Usage:
 *   node scripts/sync-content.mjs \
 *     --url  https://www.itsco.com/transportation-logistics-it-services/ \
 *     --out  app/transportation-logistics-it-services/_source.ts
 *
 * Re-run any time the live page content changes to refresh the sidecar.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname } from 'node:path'

const args = parseArgs(process.argv.slice(2))
if (!args.url || !args.out) {
  console.error('Usage: node scripts/sync-content.mjs --url <live-url> --out <_source.ts path>')
  process.exit(1)
}

console.log(`Fetching: ${args.url}`)
const res = await fetch(args.url, { headers: { 'user-agent': 'Mozilla/5.0 (compatible; ITSco content sync)' } })
if (!res.ok) {
  console.error(`Fetch failed: ${res.status} ${res.statusText}`)
  process.exit(1)
}
const html = await res.text()

const paragraphs = extractParagraphs(html)
console.log(`Extracted ${paragraphs.length} substantive paragraphs`)

const tsLines = [
  '// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —',
  '// re-run the script if the live page content changes.',
  `// Source: ${args.url}`,
  `// Generated: ${new Date().toISOString()}`,
  '',
  'export const SOURCE_URL = ' + JSON.stringify(args.url),
  '',
  'export const SOURCE_PARAGRAPHS = [',
  ...paragraphs.map((p, i) => `  /* ${i.toString().padStart(2, '0')} */ ${JSON.stringify(p)},`),
  '] as const',
  '',
]
await mkdir(dirname(args.out), { recursive: true })
await writeFile(args.out, tsLines.join('\n'))
console.log(`Wrote:    ${args.out}`)

// ──────────────────────────────────────────────────────────────────────────

function parseArgs(arr) {
  const out = {}
  for (let i = 0; i < arr.length; i++) {
    if (arr[i].startsWith('--')) {
      out[arr[i].slice(2)] = arr[i + 1]
      i++
    }
  }
  return out
}

function extractParagraphs(html) {
  const clean = html
    .replace(/<script[^>]*>[\s\S]*?<\/script>/g, '')
    .replace(/<style[^>]*>[\s\S]*?<\/style>/g, '')

  const re = /<p[^>]*>([\s\S]*?)<\/p>/g
  const out = []
  let m
  while ((m = re.exec(clean)) !== null) {
    let text = m[1].replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim()
    text = decodeEntities(text)
    if (text.length >= 30 && !isBoilerplate(text)) {
      out.push(text)
    }
  }
  return out
}

function decodeEntities(s) {
  return s
    .replace(/&#8217;/g, '’')
    .replace(/&#8216;/g, '‘')
    .replace(/&#8211;/g, '–')
    .replace(/&#8212;/g, '—')
    .replace(/&amp;/g, '&')
    .replace(/&#038;/g, '&')
    .replace(/&nbsp;/g, ' ')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
}

function isBoilerplate(text) {
  const lower = text.toLowerCase()
  // Skip footer, navigation, and recurring CTA scaffolding on every page
  if (/cookie|consent|gdpr/.test(lower)) return true
  if (/4601 creekstone|durham, nc 27703/.test(lower)) return true
  if (/sales inquiry|customer support|business office/.test(lower)) return true
  if (/useful links|our process|white papers/.test(lower)) return true
  if (/©|all rights reserved/.test(lower)) return true
  if (/on-site managed services|remote.{0,5}services/.test(lower)) return true
  return false
}
