#!/usr/bin/env node
/**
 * Blog article extractor. Fetches a live ITSco blog URL and writes a
 * structured article body (ordered h2/h3/p/ul blocks) to _source.ts.
 *
 * Usage:
 *   node scripts/sync-blog.mjs --url <live-url> --out app/blog/<slug>/_source.ts
 *
 * Output: export const ARTICLE = [...] as const  (typed blocks)
 *         export const PAGE_TITLE / SOURCE_URL
 */

import { writeFile, mkdir } from 'node:fs/promises'
import { dirname } from 'node:path'

const args = parseArgs(process.argv.slice(2))
if (!args.url || !args.out) {
  console.error('Usage: node scripts/sync-blog.mjs --url <url> --out <path>')
  process.exit(1)
}

const html = await (await fetch(args.url)).text()

// Article body lives in the Elementor post-content widget. Bound the region
// from there to the newsletter/footer so we skip nav, related posts, and CTAs.
const startMarker = 'theme-post-content'
const startIdx = html.indexOf(startMarker)
const region =
  startIdx === -1
    ? html
    : html.slice(
        startIdx,
        (() => {
          for (const m of ['Sign-up for our e-Newsletter', 'elementor-location-footer', '<footer']) {
            const i = html.indexOf(m, startIdx)
            if (i !== -1) return i
          }
          return html.length
        })(),
      )

// Pull h2 / h3 / p / li elements in document order.
const raw = []
const re = /<(h2|h3|p|li)\b[^>]*>([\s\S]*?)<\/\1>/gi
let match
const JUNK = /^(featured\s+)?image credit\b|^photo by\b|^image:\s/i
while ((match = re.exec(region)) !== null) {
  const tag = match[1].toLowerCase()
  const text = clean(match[2])
  if (text.length > 1 && !JUNK.test(text)) raw.push({ tag, text })
}

// Collapse consecutive <li> into a single list block.
const blocks = []
for (const item of raw) {
  if (item.tag === 'li') {
    const last = blocks[blocks.length - 1]
    if (last && last.type === 'ul') last.items.push(item.text)
    else blocks.push({ type: 'ul', items: [item.text] })
  } else if (item.tag === 'p') {
    blocks.push({ type: 'p', text: item.text })
  } else {
    blocks.push({ type: item.tag, text: item.text })
  }
}

const titleMatch = html.match(/<title>([\s\S]*?)<\/title>/i)
const pageTitle = titleMatch ? clean(titleMatch[1]) : ''

const body =
  `// AUTO-GENERATED by scripts/sync-blog.mjs. Do not edit by hand.\n` +
  `// Source: ${args.url}\n` +
  `// Generated: ${new Date().toISOString()}\n\n` +
  `export const SOURCE_URL = ${JSON.stringify(args.url)}\n` +
  `export const PAGE_TITLE = ${JSON.stringify(pageTitle)}\n\n` +
  `export const ARTICLE = ${JSON.stringify(blocks, null, 2)} as const\n`

await mkdir(dirname(args.out), { recursive: true })
await writeFile(args.out, body)
console.log(`Extracted ${blocks.length} blocks (${blocks.filter((b) => b.type === 'h2').length} h2)`)
console.log(`Wrote:    ${args.out}`)

function clean(s) {
  return decode(s.replace(/<[^>]+>/g, '')).replace(/\s+/g, ' ').trim()
}
function decode(s) {
  return s
    .replace(/&#8217;|&#039;|&#39;|&rsquo;/g, '’')
    .replace(/&#8216;|&lsquo;/g, '‘')
    .replace(/&#8220;|&ldquo;/g, '“')
    .replace(/&#8221;|&rdquo;/g, '”')
    .replace(/&#8211;|&ndash;/g, '–')
    .replace(/&#8212;|&mdash;/g, '—')
    .replace(/&#8230;|&hellip;/g, '…')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&nbsp;/g, ' ')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
}
function parseArgs(arr) {
  const out = {}
  for (let i = 0; i < arr.length; i++) {
    if (arr[i].startsWith('--')) {
      const k = arr[i].slice(2)
      const n = arr[i + 1]
      if (n === undefined || n.startsWith('--')) out[k] = true
      else {
        out[k] = n
        i++
      }
    }
  }
  return out
}
