// Content for /burlington-cyber-security-services/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).
// FAQ question labels are reconstructed to match the verbatim answers — the
// live page keeps them in an accordion widget the extractor cannot read.

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'Cyber Security Services in Burlington, NC',
    description:
      'ITSco delivers cyber security services in Burlington, NC — proactive threat management, risk assessments, encryption, training, and rapid response. Book a free consultation.',
    canonical: 'https://www.itsco.com/burlington-cyber-security-services',
  },
  hero: {
    eyebrow: 'Cyber Security Services · Burlington, NC',
    headlineLead: 'Cyber security services in Burlington',
    headlineAccent: 'that stay a step ahead.',
    body: S[2],
    utmSuffix: 'cyber-burlington-hero',
  },
  heroImage: {
    src: '/images/supporting/services/pexels-theo-decker-5946207.jpg',
    alt: 'Cybersecurity specialist monitoring systems for a Burlington business',
  },
  capabilitiesHeading: {
    eyebrow: 'Cutting-Edge Cybersecurity Solutions',
    headlineLead: 'Cutting-edge cybersecurity',
    headlineAccent: 'for Burlington businesses.',
  },
  capabilities: [
    { slug: 'managed-soc', title: 'Proactive Threat Management', description: S[3] },
    { slug: 'risk-management', title: 'Insightful Risk Assessments', description: S[5] },
    { slug: 'cloud-cybersecurity', title: 'End-to-End Encryption', description: S[8] },
    { slug: 'security-awareness-training', title: 'Security Awareness Training', description: S[11] },
    { slug: 'mdr-monitoring-and-response', title: 'Rapid Response & Recovery', description: S[14] },
  ],
  positioning: {
    eyebrow: 'One Partner, Complete Protection',
    headlineLead: 'Streamlined Burlington',
    headlineAccent: 'cyber security solutions.',
    paragraphs: [S[16], S[17], S[18]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years securing North Carolina businesses' },
    { value: '0%', label: 'Of our clients have experienced a serious security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'Fortify your defenses with',
    headlineAccent: "Burlington's cybersecurity experts.",
    paragraphs: [S[19], S[20], S[21]],
    image: {
      src: '/images/hero/consulting/path-digital-tR0jvlsmCuQ-unsplash.jpg',
      alt: 'ITSco cybersecurity team at work',
    },
  },
  security: {
    eyebrow: 'Compliance Support',
    headlineLead: 'Simplify compliance with a',
    headlineAccent: 'top Burlington cybersecurity company.',
    paragraphs: [S[22], S[23]],
    image: {
      src: '/images/supporting/services/network-services.jpg',
      alt: 'Network security operations',
    },
  },
  faqHeading: {
    eyebrow: 'FAQ',
    headlineLead: 'Burlington cybersecurity,',
    headlineAccent: 'answered.',
  },
  faqs: [
    { question: 'How can I ensure strong password security?', answer: [S[24]] },
    { question: 'How can I protect my company from phishing scams?', answer: [S[25]] },
    { question: 'How do I keep my data safe on public Wi-Fi?', answer: [S[26]] },
    { question: 'Why are regular software updates important for security?', answer: [S[27]] },
    { question: 'How can employees strengthen our cybersecurity?', answer: [S[28]] },
  ],
  citySlug: 'burlington',
  bookingUtm: 'cyber-burlington-bottom',
}
