// Content for /charlotte-it-network-support/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'IT Network Support in Charlotte, NC | ITSco',
    description:
      'ITSco delivers IT and computer network support in Charlotte, NC — monitoring, security, cloud networking, and compliance that reduce IT expenses. Book a free consultation.',
    canonical: 'https://www.itsco.com/charlotte-it-network-support/',
  },
  hero: {
    eyebrow: 'IT Network Support · Charlotte, NC',
    headlineLead: 'IT network support in Charlotte that',
    headlineAccent: 'reduces IT expenses.',
    body: S[0],
    utmSuffix: 'network-support-charlotte-hero',
  },
  heroImage: {
    src: '/images/hero/local/charlotte nc 3.jpg',
    alt: 'Charlotte, North Carolina at dusk',
  },
  capabilitiesHeading: {
    eyebrow: 'Complete Network Support',
    headlineLead: 'Computer network support',
    headlineAccent: 'for Charlotte, NC businesses.',
  },
  capabilities: [
    { slug: 'help-desk-services', title: 'Help Desk & Monitoring', description: S[3] },
    { slug: 'custom-slas', title: 'On-Site Technical Support', description: S[4] },
    { slug: 'advanced-engineering', title: 'Network Architecture', description: S[5] },
    { slug: 'cloud-computing', title: 'Cloud Services', description: S[6] },
    { slug: 'cyber-security-management', title: 'Security Monitoring', description: S[7] },
    { slug: 'it-automation', title: 'IT Automation', description: S[8] },
    { slug: 'network-security-services', title: 'Compliance Support', description: S[9] },
    { slug: 'risk-management', title: 'Network Audits & Maintenance', description: S[10] },
  ],
  positioning: {
    eyebrow: 'A Trusted Local Network Team',
    headlineLead: 'Network support in Charlotte',
    headlineAccent: 'from a local team.',
    paragraphs: [S[11], S[12], S[13]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years supporting Charlotte business networks' },
    { value: '0%', label: 'Of our clients have experienced a serious security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'Network support specialists',
    headlineAccent: 'who troubleshoot any problem.',
    paragraphs: [S[17], S[18], S[19], S[20]],
    image: {
      src: '/images/supporting/services/windows-AigsWJmvoEo-unsplash.jpg',
      alt: 'Network operations monitoring',
    },
  },
  security: {
    eyebrow: 'Network Security',
    headlineLead: 'Cybercriminals never stop —',
    headlineAccent: 'neither do we.',
    paragraphs: [S[21], S[22], S[23]],
    image: {
      src: '/images/hero/local/charlotte nc 6.jpg',
      alt: 'Charlotte, North Carolina cityscape',
    },
  },
  citySlug: 'charlotte',
  bookingUtm: 'network-support-charlotte-bottom',
}
