// Content for /marketing-it-services/
//
// Long-form verbatim copy lives in ./_source.ts (auto-generated by
// scripts/sync-content.mjs). This file maps each slot — hero body, pillar
// paragraphs, FAQ answers — to indices in SOURCE_PARAGRAPHS. Re-run the
// script to refresh _source.ts when the live page changes.

import { SOURCE_PARAGRAPHS } from './_source'

export const META = {
  title: 'IT Services for Marketing Companies | ITSco',
  description: 'Tailored IT services for marketing agencies — managed IT, cybersecurity, 24/7 support, and data-driven consulting built on 30+ years of expertise.',
  canonical: 'https://www.itsco.com/marketing-it-services/',
}

export const HERO = {
  eyebrow: 'Marketing IT',
  headlineLead: 'IT services for',
  headlineAccent: 'marketing companies.',
  body: 'Delivering on our promise of exceptional service excellence. Managed IT, cybersecurity, and 24/7 support tailored to the unique demands of marketing agencies.',
  utmSuffix: 'marketing-it-hero',
}

export const HERO_IMAGE = {
  src: '/images/hero/services/creatopy-mlwrIzr7yNs-unsplash.jpg',
  alt: 'Creative team designing marketing assets with integrated tooling',
}

export const CAPABILITIES_HEADING = {
  eyebrow: 'Solving Your Marketing IT Needs',
  headlineLead: 'Comprehensive IT solutions for',
  headlineAccent: 'marketing companies.',
}

export const CAPABILITIES = [
  {
    slug: 'security-audits-compliance',
    title: 'Compliance',
    description: 'Effortlessly Comply with IT Regulations Using Our Marketing-Focused Expertise.',
  },
  {
    slug: 'managed-it-services',
    title: 'Managed IT Services',
    description: 'Unlock Productivity: Let Our Experts Manage Your Complex IT Landscape, So You Can Focus on Your Business Goals.',
  },
  {
    slug: 'helpdesk',
    title: '24/7 Helpdesk',
    description: '24/7 IT Support: Resolve Issues Promptly and Keep Your Operations Running Smoothly.',
  },
  {
    slug: 'it-assessments-strategies',
    title: 'Performance Audits',
    description: 'Boost Productivity and Streamline Operations with Comprehensive IT Performance Audits.',
  },
  {
    slug: 'managed-network-services',
    title: '24/7 Network Support',
    description: '24/7 Network Support: Ensure a Seamless Network with Expert Assistance, Minimizing Maintenance Burdens.',
  },
  {
    slug: 'it-roadmap-planning',
    title: 'IT Optimization',
    description: 'Optimize Your IT: Tap into 30+ Years of Marketing-Centric Expertise to Align IT Resources with Business Growth.',
  },
  {
    slug: 'cybersecurity',
    title: 'Cybersecurity',
    description: 'Safeguard Sensitive Data: Ensure Privacy and Security with Comprehensive Network Surveillance, Encryption, and Robust Firewalls.',
  },
  {
    slug: 'it-management-consulting',
    title: 'IT Consulting',
    description: 'Elevate Your Competitive Edge: Empower Strategic Decisions with Our Data-Driven IT Consulting Services.',
  },
  {
    slug: 'backup-disaster-recovery',
    title: 'Backup & Disaster Recovery',
    description: 'Ensure Data Safety and Availability: Rely on our Dependable Backup and Disaster Recovery Strategies.',
  },
]

export const PILLARS = [
  {
    eyebrow: 'Years of Expert Marketing IT Experience',
    headlineLead: 'Three decades of',
    headlineAccent: 'marketing-focused expertise.',
    paragraphs: [SOURCE_PARAGRAPHS[14], SOURCE_PARAGRAPHS[15], SOURCE_PARAGRAPHS[16]],
    image: '/images/hero/industries/agencia-innn-V16ESPxKrOU-unsplash.jpg',
    imageAlt: 'Marketing team collaborating in a modern creative office',
    imageSide: 'right' as const,
  },
  {
    eyebrow: 'Enhance Productivity with Data-Driven Decision Making',
    headlineLead: 'Unleash the power of',
    headlineAccent: 'data-driven decisions.',
    paragraphs: [SOURCE_PARAGRAPHS[18], SOURCE_PARAGRAPHS[19], SOURCE_PARAGRAPHS[20]],
    image: '/images/supporting/industries/austin-distel-DS1hZ4xzD7M-unsplash.jpg',
    imageAlt: 'Marketing analyst reviewing campaign performance data on a laptop',
    imageSide: 'left' as const,
  },
  {
    eyebrow: 'Dependable IT Services for MarTech Excellence',
    headlineLead: 'An IT framework that',
    headlineAccent: 'amplifies your marketing.',
    paragraphs: [SOURCE_PARAGRAPHS[22], SOURCE_PARAGRAPHS[23], SOURCE_PARAGRAPHS[24]],
    image: '/images/supporting/industries/brooke-cagle-g1Kr4Ozfoac-unsplash.jpg',
    imageAlt: 'Marketing creative working on storyboards and SEO strategy',
    imageSide: 'right' as const,
  },
  {
    eyebrow: 'Creative Technology Solutions for Your Vision',
    headlineLead: 'Merge your creativity',
    headlineAccent: 'with IT excellence.',
    paragraphs: [SOURCE_PARAGRAPHS[26], SOURCE_PARAGRAPHS[27], SOURCE_PARAGRAPHS[28]],
    image: '/images/hero/services/aleksei-zhivilov-A6M3aowKR6I-unsplash.jpg',
    imageAlt: 'Marketing professional integrating creative tools into daily workflow',
    imageSide: 'left' as const,
  },
]

export const MID_CTA = {
  eyebrow: 'Reclaim Your Productivity: Say Goodbye to Persistent IT Issues',
  headline: 'Boost productivity. Eliminate issues with our understanding team.',
  utmSuffix: 'marketing-it-mid',
}

export const FAQ_HEADING = {
  eyebrow: 'FAQs',
  headlineLead: 'IT services for',
  headlineAccent: 'marketing companies, answered.',
}

export const FAQ_CALENDLY =
  'https://calendly.com/msavino-itsco/30-minute-free-consultation-with-itsco?utm_source=website&utm_medium=cta&utm_campaign=marketing-it-faq'

export const FAQS = [
  {
    question: 'What is the quality of support ITSco provides?',
    answer: [SOURCE_PARAGRAPHS[33]],
  },
  {
    question: "What can I expect to pay for ITSco's marketing IT services?",
    answer: [SOURCE_PARAGRAPHS[35]],
  },
  {
    question: 'Why choose ITSco for marketing IT services?',
    answer: [SOURCE_PARAGRAPHS[37]],
  },
  {
    question: "Does ITSco's IT service have the capability to manage the diverse software used in our marketing operations?",
    answer: [SOURCE_PARAGRAPHS[39]],
  },
  {
    question: "In the event of a data breach, what immediate steps does ITSco's team take to mitigate the issue?",
    answer: [SOURCE_PARAGRAPHS[41], SOURCE_PARAGRAPHS[42], SOURCE_PARAGRAPHS[43]],
  },
]
// Index of the FAQ that gets the inline Calendly link (the pricing question).
export const FAQ_INLINE_CTA_INDEX = 1
export const FAQ_INLINE_CTA_LABEL = 'Book a free consultation'
