// Content for /security-audits-compliance/
//
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Security Audits & Compliance Services | ITSco',
    description:
      'ITSco security audits and compliance — risk assessments, regulatory audits, and remediation roadmaps that keep your business secure and compliant. Book a free consultation.',
    canonical: 'https://www.itsco.com/security-audits-compliance/',
  },
  serviceName: 'Security Audits & Compliance',
  hero: {
    eyebrow: 'Cybersecurity · Audits & Compliance',
    headlineLead: 'Security audits and compliance',
    headlineAccent: 'that keep you covered.',
    body: S[0],
    utmSuffix: 'security-audits-compliance-hero',
  },
  heroImage: {
    src: '/images/hero/services/pexels-cookiecutter-19166565.jpg',
    alt: 'Structured network patch panel representing systematic security review',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Detect threats. Reduce vulnerabilities.',
    headlineAccent: 'Maintain compliance.',
    paragraphs: [S[1]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years of cybersecurity and compliance expertise' },
    { value: '60%', label: 'Of our clients have stayed with us for 5+ years' },
  ],
  capabilitiesHeading: {
    eyebrow: 'What We Assess',
    headlineLead: 'A clear picture of',
    headlineAccent: 'your security posture.',
  },
  capabilities: [
    { slug: 'cyber-risk-assessments', title: 'Cybersecurity Risk Assessments', description: S[2] },
    { slug: 'regulatory-compliance-audits', title: 'Regulatory Compliance Audits', description: S[3] },
    { slug: 'pentest-vuln-scanning', title: 'Penetration Testing & Vulnerability Scanning', description: S[4] },
    { slug: 'security-policy-review', title: 'Security Policy & Governance Reviews', description: S[5] },
    { slug: 'cloud-security-assessment', title: 'Cloud Security & Data Protection Assessments', description: S[6] },
    { slug: 'incident-response-planning', title: 'Incident Response & Business Continuity Planning', description: S[7] },
  ],
  outcomes: {
    eyebrow: 'The Risk',
    headlineLead: 'Ignoring security audits',
    headlineAccent: 'can be costly.',
    paragraphs: [],
    tone: 'risk',
    bullets: [S[9], S[10], S[11], S[12]],
    image: {
      src: '/images/supporting/industries/scott-graham-5fNmWej4tAA-unsplash.jpg',
      alt: 'Reviewing a compliance audit report',
    },
  },
  related: {
    heading: 'Explore more cybersecurity services',
    links: [
      {
        slug: 'cyber-risk-assessment',
        label: 'Cyber Risk Assessment',
        href: '/cyber-risk-assessment/',
        description: 'A focused look at your exposure and a prioritized plan to fix it.',
      },
      {
        slug: 'penetration-testing-services',
        label: 'Penetration Testing',
        href: '/penetration-testing-services/',
        description: 'Real-world attack simulations that surface weaknesses before attackers do.',
      },
      {
        slug: 'fully-managed-cybersecurity',
        label: 'Fully-Managed Cybersecurity',
        href: '/fully-managed-cybersecurity/',
        description: 'End-to-end cybersecurity, monitored and managed by ITSco.',
      },
    ],
  },
  bookingUtm: 'security-audits-compliance-bottom',
}
