// Content for /charlotte-cyber-security-services/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'Cyber Security Services in Charlotte, NC',
    description:
      'ITSco delivers cyber security in Charlotte, NC — network security, audits, cloud security, intrusion detection, and penetration testing — to fortify your defenses. Book a free consultation.',
    canonical: 'https://www.itsco.com/charlotte-cyber-security-services',
  },
  hero: {
    eyebrow: 'Cyber Security Services · Charlotte, NC',
    headlineLead: 'Cyber security in Charlotte that',
    headlineAccent: 'fortifies your defenses.',
    body: S[0],
    utmSuffix: 'cyber-charlotte-hero',
  },
  heroImage: {
    src: '/images/hero/local/charlotte nc 3.jpg',
    alt: 'Charlotte, North Carolina at dusk',
  },
  capabilitiesHeading: {
    eyebrow: 'Robust Organization-Wide Protection',
    headlineLead: 'Comprehensive cyber security',
    headlineAccent: 'for Charlotte businesses.',
  },
  capabilities: [
    { slug: 'network-security', title: 'Network Security', description: S[3] },
    { slug: 'security-audits-compliance', title: 'Security Audits', description: S[4] },
    { slug: 'cloud-cybersecurity', title: 'Cloud Security', description: S[5] },
    { slug: 'security-architecture', title: 'Security Architecture Design', description: S[6] },
    { slug: 'security-awareness-training', title: 'Cybersecurity Awareness Training', description: S[7] },
    { slug: 'fully-managed-cybersecurity', title: 'Managed Security Solutions', description: S[8] },
    { slug: 'ids-ips', title: 'Intrusion Detection', description: S[9] },
    { slug: 'penetration-testing-services', title: 'Penetration Testing', description: S[10] },
  ],
  positioning: {
    eyebrow: 'A Top Choice in Charlotte',
    headlineLead: 'A top choice among',
    headlineAccent: 'cyber security firms in Charlotte.',
    paragraphs: [S[2], S[11], S[12]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years securing North Carolina businesses' },
    { value: '0%', label: 'Of our clients have experienced a serious security breach' },
  ],
  whyUs: {
    eyebrow: 'Complete Assessment & Support',
    headlineLead: 'Complete protection from one',
    headlineAccent: 'Charlotte IT security company.',
    paragraphs: [S[16], S[17], S[18], S[19]],
    image: {
      src: '/images/hero/local/charlotte nc .jpg',
      alt: 'Downtown Charlotte, North Carolina skyline',
    },
  },
  security: {
    eyebrow: 'Tailored to Your Business',
    headlineLead: 'Cyber security in Charlotte',
    headlineAccent: 'tailored to your business.',
    paragraphs: [S[20], S[24], S[25]],
    image: {
      src: '/images/hero/local/charlotte nc 6.jpg',
      alt: 'Charlotte, North Carolina cityscape',
    },
  },
  citySlug: 'charlotte',
  bookingUtm: 'cyber-charlotte-bottom',
}
