// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —
// re-run the script if the live page content changes.
// Source: https://www.itsco.com/managed-it-services-cary/
// Generated: 2026-05-20T12:43:58.903Z

export const SOURCE_URL = "https://www.itsco.com/managed-it-services-cary/"

export const SOURCE_PARAGRAPHS = [
  /* 00 */ "Reduce risk and improve service with the leaders in managed IT services in Cary. Why choose ITSco for managed IT services in Cary?",
  /* 01 */ "Our IT services team in Cary provides monitoring and proactive maintenance of your systems so that many issues can be addressed before they can escalate into outages.",
  /* 02 */ "Mitigate security risks with a robust, multi-layered cybersecurity defense program that includes a robust Security Operations Center (SOC) and advanced Security Incident Event Management (SIEM) system.",
  /* 03 */ "As part of our managed IT services in Cary, our talented, courteous and locally based IT support technicians are available both remotely and on-site to address a wide variety of user-issues.",
  /* 04 */ "Plan for the future by leveraging the full potential of cloud computing. Our IT services experts in Cary will securely migrate, monitor, and manage your cloud solutions.",
  /* 05 */ "Streamline your IT services and pay only for the services you need. We’ll work together to design a suite of services and an SLA that supports the unique requirements of your business.",
  /* 06 */ "Prevent disruptions to operations and mitigate the risk of data loss with secure data backup and effective disaster recovery planning.",
  /* 07 */ "Detect security vulnerabilities and reduce risks to your IT infrastructure with automated vulnerability scanning and managed remediation services.",
  /* 08 */ "Your firewalls are a critical component of your cybersecurity defenses. Our experienced network engineers will ensure that yours are configured, monitored, and maintained properly.",
  /* 09 */ "We can help you navigate the complexities of regulatory compliance (HIPAA, SOC, ISO, etc.) and ensure that your IT infrastructure, processes and procedures comply with any standards that may be required or recommended for your business.",
  /* 10 */ "Optimize your IT infrastructure, reduce technical debt, and improve productivity with a proven managed service provider in Cary.",
  /* 11 */ "ITSco’s services are designed to make a positive impact on your business by transforming IT from a simple “cost center” into an engine of growth and innovation.",
  /* 12 */ "As one of one of the leading IT companies in Cary, we provide:",
  /* 13 */ "as one of the most trusted IT service companies in Cary",
  /* 14 */ "of our managed service clients has experienced a major security breach",
  /* 15 */ "of our clients have been with us for five or more years",
  /* 16 */ "A poorly monitored and managed IT infrastructure can leave your company vulnerable to devastating attacks – and even existential threats – from cybercriminals.",
  /* 17 */ "To make sure that your systems are never an easy target for attackers, ITSco offers a wide variety of security services to its customers in Cary:",
  /* 18 */ "World-Class IT Services at Fair Prices",
  /* 19 */ "For over 25 years, ITSco’s wide range of IT services have helped some of the area’s most successful businesses achieve their goals.",
  /* 20 */ "Our broad range of clients include one of the area’s largest physician-owned medical groups (with multiple locations across North Carolina), some of the largest technology companies in the world, and numerous local tech startups.",
  /* 21 */ "Our customers are varied and their IT needs are always changing, but they all have this in common: the need for a trusted partner who can provide a full range of IT services delivered with the highest standards of engineering excellence and business integrity.",
  /* 22 */ "We are proud to have built our reputation on these principles.",
  /* 23 */ "Above all, ITSco is an organization committed to service – and our business model is based on our long-term commitment to our customers and our people.",
  /* 24 */ "60% of our clients have been with us for over five years, and over a third have been with us for more than 10.",
  /* 25 */ "That’s saying something in an industry in which, every year, about 40% of medium/small business owners look to change their MSP/ technology service provider.",
  /* 26 */ "And our commitment to our customers goes hand-in-hand with our commitment to our service team, as our success depends on attracting and retaining some of the top engineers, customer service reps, and computer support technicians in the market.",
  /* 27 */ "We are proud to say that for over 25 years, these twin-commitments have helped make us one of the most trusted names among IT Services Companies in Cary and across the Triangle and North Carolina.",
  /* 28 */ "Improve functionality and productivity with quality IT services in Cary.",
  /* 29 */ "Unlike many other managed services providers, we will take the time to understand the needs of your Cary business and customize our IT services so they are aligned with your business goals and plans.",
  /* 30 */ "Contact us today and find out how trustworthy and capable a managed IT services company can be.",
] as const
