// Content for /managed-it-services-cary/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'Managed IT Services in Cary, NC',
    description:
      'ITSco delivers managed IT services in Cary, NC — monitoring, cybersecurity, help desk, cloud, and compliance — to reduce risk and improve service. Book a free consultation.',
    canonical: 'https://www.itsco.com/managed-it-services-cary/',
  },
  hero: {
    eyebrow: 'Managed IT Services · Cary, NC',
    headlineLead: 'Managed IT services in Cary that',
    headlineAccent: 'reduce risk and improve service.',
    body: S[0],
    utmSuffix: 'managed-it-cary-hero',
  },
  heroImage: {
    src: '/images/supporting/services/pexels-mart-production-7088498.jpg',
    alt: 'IT professional supporting a Cary business',
  },
  capabilitiesHeading: {
    eyebrow: 'End-to-End Managed IT Services',
    headlineLead: 'Full-suite IT services for',
    headlineAccent: 'Cary, NC businesses.',
  },
  capabilities: [
    { slug: 'remote-monitoring', title: 'Remote Monitoring', description: S[1] },
    { slug: 'cyber-security-management', title: 'Cyber Security Services', description: S[2] },
    { slug: 'help-desk-services', title: 'Help Desk Services', description: S[3] },
    { slug: 'cloud-computing', title: 'Cloud Technology Solutions', description: S[4] },
    { slug: 'custom-slas', title: 'Customized Services & SLAs', description: S[5] },
    { slug: 'disaster-recovery', title: 'Disaster Recovery', description: S[6] },
    { slug: 'vulnerability-management', title: 'Vulnerability Management', description: S[7] },
    { slug: 'network-security-services', title: 'Managed Firewall Services', description: S[8] },
    { slug: 'custom-slas', title: 'Regulatory Compliance', description: S[9] },
  ],
  positioning: {
    eyebrow: 'IT as an Engine of Growth',
    headlineLead: 'IT services in Cary that',
    headlineAccent: 'improve efficiency and ROI.',
    paragraphs: [S[10], S[11], S[12]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years serving Cary, the Triangle & North Carolina' },
    { value: '0%', label: 'Of our clients have experienced a major security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'A managed services provider',
    headlineAccent: 'in Cary committed to your success.',
    paragraphs: [S[19], S[20], S[21], S[23], S[24]],
    image: {
      src: '/images/hero/consulting/pexels-vlada-karpovich-7433919.jpg',
      alt: 'ITSco team collaborating with a client',
    },
  },
  security: {
    eyebrow: 'Cybersecurity in Cary',
    headlineLead: 'Cybersecurity solutions',
    headlineAccent: 'that provide peace of mind.',
    paragraphs: [S[16], S[17]],
    image: {
      src: '/images/supporting/services/pexels-thirdman-5582868.jpg',
      alt: 'Cybersecurity monitoring for a Cary business',
    },
  },
  citySlug: 'cary',
  bookingUtm: 'managed-it-cary-bottom',
}
