// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —
// re-run the script if the live page content changes.
// Source: https://www.itsco.com/managed-it-services-chapel-hill/
// Generated: 2026-05-20T12:43:53.479Z

export const SOURCE_URL = "https://www.itsco.com/managed-it-services-chapel-hill"

export const SOURCE_PARAGRAPHS = [
  /* 00 */ "Reduce overhead and improve returns on IT investments with ITSco’s managed IT services in Chapel Hill.",
  /* 01 */ "Why choose ITSco for managed IT services in Chapel Hill ?",
  /* 02 */ "Put Your IT Infrastructure in the Hands of a Trusted Managed Services Provider in Chapel Hill",
  /* 03 */ "Our team of North-Carolina based IT services techs closely monitor your Chapel Hill computers and networks to detect and remediate IT issues before they can impact your business.",
  /* 04 */ "Reduce security risks with advanced cybersecurity tools, including: vulnerability scanning, security incident event management (SIEM), and security awareness training.",
  /* 05 */ "Our knowledgeable, local technology support specialists can resolve issues quickly and efficiently. Avoid end-user frustration with courteous and prompt remote and on-site support .",
  /* 06 */ "Improve the efficiency of daily operations by letting our experts show you how to leverage the reliability and scalability of well designed and well managed cloud computing solutions.",
  /* 07 */ "Get the service your Chapel Hill business needs with a customized service level agreement (SLA) from a reliable managed services provider.",
  /* 08 */ "Avoid business disruption and possible data loss by implementing comprehensive disaster recovery procedures and developing robust business continuity plans.",
  /* 09 */ "Automated vulnerability scanning enables our technology services team to identify, prioritize, and remediate critical security gaps before they become serious business problems.",
  /* 10 */ "Simplify operations, reduce human error and improve the security of your IT infrastructure through the deployment of advanced automation tools.",
  /* 11 */ "Solid technical project management is critical to realizing your business vision. Let our seasoned managed services team in Chapel Hill show you how it’s done.",
  /* 12 */ "Don’t think of Information Technology as a cost-center problem to be solved – but an exciting opportunity to be exploited. Given the right planning, implementation and management, IT services can become an engine of productivity for your Chapel Hill business!",
  /* 13 */ "At ITSco, our innovative computer support services include the development of IT roadmaps to support accurate budgeting and forecasting and to assure that technology initiatives are aligned with business goals.",
  /* 14 */ "And our experienced TarHeel-based team of IT engineers and project managers will deliver and support your critical IT projects in a consistently reliable and cost effective manner.",
  /* 15 */ "As one of the leading IT services companies serving Chapel Hill=",
  /* 16 */ "Of our clients have trusted us for over 5 years.",
  /* 17 */ "Of our managed services clients have experienced a serious security breach",
  /* 18 */ "Are you among the 40% of SME owners who are unsatisfied with your current managed IT service provider?",
  /* 19 */ "At ITSco, the quality of our services is evidenced by our incredibly low customer turnover rate. Nearly a third of our customers have been with us for over 10 years, and some for much longer than that.",
  /* 20 */ "The secret to that success is our ability to attract and retain some of the smartest and most dedicated IT talent in the Triangle. And the secret to that is our long-term commitment to job satisfaction and customer satisfaction.",
  /* 21 */ "It turns out that good people enjoy working for a company that wants to do good things for its clients. And that is what has helped make ITSco one of the most trusted IT firms in Chapel Hill, the Triangle, and across North Carolina.",
  /* 22 */ "Trust ITSco – a managed IT services company with over two and a half decades of success in the Triangle – to service all of your information technology needs.",
  /* 23 */ "With cybercrime up more than 600% since the start of the COVID-19 pandemic, your company is more likely than ever to be exposed to the threat of a serious cyber attack.",
  /* 24 */ "Improving your cybersecurity defenses must be a continuous business priority for you and your IT service provider . Keep up your guard with ITSco’s cybersecurity services.",
  /* 25 */ "Our managed security solutions include:",
  /* 26 */ "If you are choosing between IT companies in Chapel Hill, choose a firm you can count on. One with a 25+ year track record of success and a long list of satisfied customers in the Triangle and across North Carolina .",
  /* 27 */ "Our end-to-end IT Services in Chapel Hill include a complete suite of IT services – from well trained, North Carolina based help desk personnel that provide a frustration-free experience for your users – to seasoned engineers and project managers that can deliver the strategic IT planning and implementation services your business needs to be successful for the long run.",
] as const
