// Content for /managed-it-services-chapel-hill/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'Managed IT Services in Chapel Hill, NC',
    description:
      'ITSco delivers managed IT services in Chapel Hill, NC — monitoring, cybersecurity, help desk, and cloud — to reduce overhead and improve IT ROI. Book a free consultation.',
    canonical: 'https://www.itsco.com/managed-it-services-chapel-hill/',
  },
  hero: {
    eyebrow: 'Managed IT Services · Chapel Hill, NC',
    headlineLead: 'Managed IT services in Chapel Hill that',
    headlineAccent: 'reduce overhead and improve returns.',
    body: S[0],
    utmSuffix: 'managed-it-chapel-hill-hero',
  },
  heroImage: {
    src: '/images/hero/consulting/path-digital-tR0jvlsmCuQ-unsplash.jpg',
    alt: 'IT professional supporting a Chapel Hill business',
  },
  capabilitiesHeading: {
    eyebrow: 'Comprehensive Managed IT Services',
    headlineLead: 'Full-suite IT services for',
    headlineAccent: 'Chapel Hill businesses.',
  },
  capabilities: [
    { slug: 'remote-monitoring', title: 'Remote Monitoring', description: S[3] },
    { slug: 'cyber-security-management', title: 'Cybersecurity', description: S[4] },
    { slug: 'help-desk-services', title: 'Help Desk Services', description: S[5] },
    { slug: 'cloud-computing', title: 'Cloud Computing Services', description: S[6] },
    { slug: 'custom-slas', title: 'Customized SLAs', description: S[7] },
    { slug: 'disaster-recovery', title: 'Disaster Recovery', description: S[8] },
    { slug: 'vulnerability-management', title: 'Vulnerability Management', description: S[9] },
    { slug: 'it-automation', title: 'IT Automation', description: S[10] },
    { slug: 'it-project-management', title: 'IT Project Management', description: S[11] },
  ],
  positioning: {
    eyebrow: 'IT as a Driver of Growth',
    headlineLead: 'Scalable IT services that support',
    headlineAccent: 'Chapel Hill business growth.',
    paragraphs: [S[12], S[13], S[14]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have trusted us for 5+ years' },
    { value: '25+', label: 'Years serving Chapel Hill & the Triangle' },
    { value: '0%', label: 'Of our clients have experienced a serious security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'One of Chapel Hill’s',
    headlineAccent: 'best IT companies.',
    paragraphs: [S[18], S[19], S[20], S[21], S[22]],
    image: {
      src: '/images/hero/consulting/charlesdeluvio-Lks7vei-eAg-unsplash.jpg',
      alt: 'ITSco engineers collaborating in the office',
    },
  },
  security: {
    eyebrow: 'Cybersecurity in Chapel Hill',
    headlineLead: 'A Chapel Hill IT provider that',
    headlineAccent: 'focuses on security.',
    paragraphs: [S[23], S[24]],
    image: {
      src: '/images/supporting/services/pexels-theo-decker-5946207.jpg',
      alt: 'Cybersecurity monitoring in progress',
    },
  },
  citySlug: 'chapel-hill',
  bookingUtm: 'managed-it-chapel-hill-bottom',
}
