// Content for /it-procurement/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).
// Hero framing is composed — the live Elementor page has no standalone hero
// paragraph. Capability descriptions and FAQs are verbatim.

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'IT Procurement Services',
    description:
      'ITSco IT procurement — the right technology sourced at the right price, with vendor-agnostic guidance and end-to-end lifecycle support. Book a free consultation.',
    canonical: 'https://www.itsco.com/it-procurement',
  },
  serviceName: 'IT Procurement',
  parent: { name: 'Managed IT Services', href: '/managed-it-services/' },
  hero: {
    eyebrow: 'Engineering · IT Procurement',
    headlineLead: 'IT procurement,',
    headlineAccent: 'handled end to end.',
    body: 'The right technology, sourced at the right price and rolled out without the headaches — ITSco manages IT procurement from assessment through lifecycle, with vendor-agnostic guidance at every step.',
    utmSuffix: 'it-procurement-hero',
  },
  heroImage: {
    src: '/images/hero/services/pexels-field-engineer-147254-442151.jpg',
    alt: 'IT hardware being procured and deployed',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'A strategic partner for',
    headlineAccent: 'every technology investment.',
    paragraphs: [S[30], S[31], S[32]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years as a trusted IT services provider' },
    { value: '60%', label: 'Of our clients have stayed with us for 5+ years' },
  ],
  capabilitiesHeading: {
    eyebrow: 'End-to-End Procurement Support',
    headlineLead: 'Every stage of the',
    headlineAccent: 'procurement process.',
  },
  capabilities: [
    { slug: 'proc-assessment', title: 'Technology Assessment', description: S[6] },
    { slug: 'proc-implementation', title: 'Implementation & Rollout', description: S[10] },
    { slug: 'proc-support', title: 'Remote & On-Site Support', description: S[14] },
    { slug: 'proc-compliance', title: 'Compliance Support', description: S[18] },
    { slug: 'proc-integration', title: 'Integration & Configuration', description: S[22] },
    { slug: 'proc-lifecycle', title: 'Lifecycle Management', description: S[26] },
  ],
  outcomes: {
    eyebrow: 'The Payoff',
    headlineLead: 'Maximize returns with streamlined',
    headlineAccent: 'IT procurement.',
    paragraphs: [S[38], S[39], S[40], S[41]],
    image: {
      src: '/images/hero/services/pexels-brett-sayles-4657256.jpg',
      alt: 'IT hardware and infrastructure investment',
    },
  },
  related: {
    heading: 'Explore related services',
    links: [
      {
        slug: 'network-engineering',
        label: 'Network Engineering',
        href: '/network-engineering/',
        description: 'Modern, secure, high-performance networks designed for your business.',
      },
      {
        slug: 'asset-lifecycle-management',
        label: 'Asset Lifecycle Management',
        href: '/asset-lifecycle-management/',
        description: 'Hardware tracking, refresh planning, and end-of-life disposition.',
      },
      {
        slug: 'managed-it-services',
        label: 'Managed IT Services',
        href: '/managed-it-services/',
        description: 'The full ITSco managed IT program — monitoring, helpdesk, security, and more.',
      },
    ],
  },
  faqHeading: {
    eyebrow: 'FAQ',
    headlineLead: 'IT procurement,',
    headlineAccent: 'answered.',
  },
  faqs: [
    { question: S[44], answer: [S[45]] },
    { question: S[47], answer: [S[48]] },
    { question: S[49], answer: [S[50]] },
    { question: S[51], answer: [S[52]] },
  ],
  bookingUtm: 'it-procurement-bottom',
}
