// Content for /tech-due-diligence-for-businesses/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Technology Due Diligence for Businesses | ITSco',
    description:
      'ITSco technology due diligence — a clear, actionable assessment of a target company’s IT infrastructure, security, and risk for investors and acquirers. Book a free consultation.',
    canonical: 'https://www.itsco.com/tech-due-diligence-for-businesses/',
  },
  serviceName: 'Technology Due Diligence',
  hero: {
    eyebrow: 'Strategy · Due Diligence',
    headlineLead: 'Technology due diligence',
    headlineAccent: 'that protects your investment.',
    body: S[0],
    utmSuffix: 'tech-due-diligence-hero',
  },
  heroImage: {
    src: '/images/hero/consulting/pexels-gustavo-fring-6285127.jpg',
    alt: 'Investors reviewing a technology due diligence report',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'What is',
    headlineAccent: 'technology due diligence?',
    paragraphs: [S[1], S[2]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years in IT assessment and infrastructure strategy' },
    { value: '60%', label: 'Of our clients have stayed with us for 5+ years' },
  ],
  capabilitiesHeading: {
    eyebrow: 'Our Assessment Process',
    headlineLead: 'Every angle of the target',
    headlineAccent: "company's IT.",
  },
  capabilities: [
    { slug: 'tdd-infrastructure', title: 'IT Infrastructure & Systems', description: S[4] },
    { slug: 'tdd-cybersecurity', title: 'Cybersecurity & IT Security', description: S[5] },
    { slug: 'tdd-operations', title: 'Operations & Support', description: S[6] },
    {
      slug: 'tdd-risk-opportunities',
      title: 'Risk Identification & Opportunities',
      description: S[7],
    },
    { slug: 'tdd-compliance', title: 'Compliance & Contractual Issues', description: S[8] },
  ],
  outcomes: {
    eyebrow: 'The Payoff',
    headlineLead: 'Technology due diligence',
    headlineAccent: 'pays off.',
    paragraphs: [],
    bullets: [S[10], S[11], S[12], S[13]],
    image: {
      src: '/images/supporting/consulting/ant-rozetsky-HXOllTSwrpM-unsplash.jpg',
      alt: 'Reviewing acquisition technology findings',
    },
  },
  related: {
    heading: 'Explore more strategy & consulting services',
    links: [
      {
        slug: 'it-due-diligence-mergers-acquisitions',
        label: 'IT Due Diligence for M&A',
        href: '/it-due-diligence-mergers-acquisitions/',
        description: 'Dedicated IT due diligence for mergers and acquisitions.',
      },
      {
        slug: 'it-assessments-strategies',
        label: 'IT Assessments & Strategies',
        href: '/it-assessments-strategies/',
        description: 'In-depth evaluations of infrastructure, security, and compliance.',
      },
      {
        slug: 'it-management-consulting',
        label: 'Strategy & Consulting Overview',
        href: '/it-management-consulting/',
        description: 'The full ITSco strategy program — leadership, roadmaps, and assessments.',
      },
    ],
  },
  bookingUtm: 'tech-due-diligence-bottom',
}
