// Content for /mdr-monitoring-and-response/
//
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).
// Hero framing is composed — the live Elementor page has no standalone hero
// paragraph. Capability descriptions and FAQs are verbatim.

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'MDR Services | Managed Detection & Response | ITSco',
    description:
      'ITSco MDR — always-on monitoring, proactive threat hunting, and rapid incident response that catches threats early and shuts them down fast. Book a free consultation.',
    canonical: 'https://www.itsco.com/mdr-monitoring-and-response/',
  },
  serviceName: 'Managed Detection & Response (MDR)',
  hero: {
    eyebrow: 'Cybersecurity · MDR',
    headlineLead: 'Managed detection and response',
    headlineAccent: 'that never sleeps.',
    body: "ITSco's MDR service pairs always-on monitoring with proactive threat hunting and rapid incident response — catching threats early and shutting them down fast.",
    utmSuffix: 'mdr-hero',
  },
  heroImage: {
    src: '/images/hero/services/pexels-mikhail-nilov-8108674.jpg',
    alt: 'Server hardware with blue indicator lighting',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Proactive monitoring and',
    headlineAccent: 'rapid response.',
    paragraphs: [S[35], S[36]],
  },
  stats: [
    { value: '0%', label: 'Of our clients have suffered a serious security breach' },
    { value: '25+', label: 'Years as a trusted IT services provider' },
    { value: '24/7', label: 'Threat monitoring, detection, and response' },
  ],
  capabilitiesHeading: {
    eyebrow: 'What MDR Delivers',
    headlineLead: 'Detection and response,',
    headlineAccent: 'fully managed.',
  },
  capabilities: [
    { slug: 'mdr-threat-detection', title: '24/7 Threat Detection & Response', description: S[8] },
    { slug: 'threat-hunting', title: 'Threat Hunting', description: S[11] },
    { slug: 'incident-response', title: 'Incident Response', description: S[16] },
    { slug: 'flexible-security-services', title: 'Flexible Services', description: S[19] },
    { slug: 'security-integration', title: 'Security Integration', description: S[23] },
  ],
  outcomes: {
    eyebrow: 'The Payoff',
    headlineLead: 'Rapid response,',
    headlineAccent: 'maximum protection.',
    paragraphs: [S[26], S[27], S[28]],
    image: {
      src: '/images/hero/blog/compagnons-psXNymQI7Pk-unsplash.jpg',
      alt: 'Security engineers analyzing threat data',
    },
  },
  related: {
    heading: 'Explore more cybersecurity services',
    links: [
      {
        slug: 'managed-soc',
        label: 'Managed SOC',
        href: '/managed-soc/',
        description: 'A 24/7 security operations center watching your environment around the clock.',
      },
      {
        slug: 'cyber-risk-assessment',
        label: 'Cyber Risk Assessment',
        href: '/cyber-risk-assessment/',
        description: 'Know exactly where your exposure is — and what to fix first.',
      },
      {
        slug: 'fully-managed-cybersecurity',
        label: 'Fully-Managed Cybersecurity',
        href: '/fully-managed-cybersecurity/',
        description: 'End-to-end cybersecurity, monitored and managed by ITSco.',
      },
    ],
  },
  faqHeading: {
    eyebrow: 'FAQ',
    headlineLead: 'MDR services,',
    headlineAccent: 'answered.',
  },
  faqs: [
    { question: S[43], answer: [S[44]] },
    { question: S[45], answer: [S[46]] },
    { question: S[47], answer: [S[48]] },
  ],
  bookingUtm: 'mdr-bottom',
}
