// Content for /raleigh-it-network-support/
// Verbatim copy lives in ./_source.ts (auto-generated by sync-content.mjs).

import type { CityServiceContent } from '@/components/CityServicePage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: CityServiceContent = {
  meta: {
    title: 'IT Network Support in Raleigh, NC | ITSco',
    description:
      'ITSco delivers IT network support in Raleigh, NC — network design, monitoring, security, and cloud networking that maximize uptime and reduce risk. Book a free consultation.',
    canonical: 'https://www.itsco.com/raleigh-it-network-support/',
  },
  hero: {
    eyebrow: 'IT Network Support · Raleigh, NC',
    headlineLead: 'IT network support in Raleigh that',
    headlineAccent: 'maximizes uptime and security.',
    body: S[0],
    utmSuffix: 'network-support-raleigh-hero',
  },
  heroImage: {
    src: '/images/supporting/services/network-services.jpg',
    alt: 'Network operations supporting a Raleigh business',
  },
  capabilitiesHeading: {
    eyebrow: 'Complete Network Support',
    headlineLead: 'Network support services',
    headlineAccent: 'for Raleigh, NC businesses.',
  },
  capabilities: [
    { slug: 'network-security-services', title: 'Network Support & Management', description: S[2] },
    { slug: 'custom-slas', title: 'Compliance & Continuity', description: S[3] },
    { slug: 'cyber-security-management', title: 'Security Monitoring', description: S[4] },
    { slug: 'it-automation', title: 'IT Automation', description: S[5] },
    { slug: 'advanced-engineering', title: 'Network Architecture & Design', description: S[6] },
    { slug: 'risk-management', title: 'Network Audits & Assessments', description: S[7] },
    { slug: 'help-desk-services', title: 'Help Desk & Monitoring', description: S[8] },
    { slug: 'cloud-computing', title: 'Cloud Networking', description: S[9] },
  ],
  positioning: {
    eyebrow: 'A Trusted Network Partner',
    headlineLead: 'Network management services',
    headlineAccent: 'you can depend on.',
    paragraphs: [S[11], S[12], S[13]],
  },
  stats: [
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
    { value: '25+', label: 'Years of network engineering excellence' },
    { value: '0%', label: 'Of our clients have experienced a serious security breach' },
  ],
  whyUs: {
    eyebrow: 'Why ITSco',
    headlineLead: 'Dedicated network support',
    headlineAccent: 'specialists in your corner.',
    paragraphs: [S[16], S[17], S[23], S[25], S[26]],
    image: {
      src: '/images/hero/local/raleigh3.jpg',
      alt: 'Raleigh, North Carolina at dusk',
    },
  },
  security: {
    eyebrow: 'Maximum Uptime',
    headlineLead: 'Proactive defense',
    headlineAccent: 'against cyber threats.',
    paragraphs: [S[29], S[30], S[36], S[37]],
    image: {
      src: '/images/hero/local/raleigh.jpg',
      alt: 'Downtown Raleigh, North Carolina skyline',
    },
  },
  bookingUtm: 'network-support-raleigh-bottom',
}
