// AUTO-GENERATED by scripts/sync-content.mjs. Do not edit by hand —
// re-run the script if the live page content changes.
// Source: https://www.itsco.com/server-monitoring-and-maintenance/
// Generated: 2026-05-20T18:03:05.136Z

export const SOURCE_URL = "https://www.itsco.com/server-monitoring-and-maintenance/"

export const SOURCE_PARAGRAPHS = [
  /* 00 */ "Your servers are the backbone of your IT infrastructure—keeping them secure, optimized, and running smoothly is essential to business success.",
  /* 01 */ "ITSco’s Server Monitoring & Maintenance Services provide 24/7 proactive monitoring, maintenance, and expert troubleshooting to minimize downtime, enhance security, and ensure optimal performance.",
  /* 02 */ "Our team continuously monitors your servers for performance issues, hardware failures, and security threats, ensuring that potential problems are identified and resolved before they affect your business.",
  /* 03 */ "ITSco provides ongoing server updates, patch management, and performance tuning to keep your systems operating efficiently and securely.",
  /* 04 */ "We implement industry best practices for server security, including firewall configurations, intrusion detection, and access controls to protect your business from cyber threats.",
  /* 05 */ "Our server maintenance services include routine backup monitoring, testing, and recovery planning to ensure that your data is protected and recoverable in case of system failure.",
  /* 06 */ "We analyze server performance trends to anticipate future resource needs, optimize server loads, and prevent performance bottlenecks before they occur.",
  /* 07 */ "Our experienced engineers quickly diagnose and resolve server issues, ensuring minimal disruption and long-term stability.",
  /* 08 */ "Without proactive server monitoring and maintenance, businesses face costly downtime, security vulnerabilities, and performance degradation:",
  /* 09 */ "Waiting for something to break often results in higher costs and longer recovery times.",
  /* 10 */ "Unpatched servers and misconfigurations leave your network vulnerable to cyberattacks.",
  /* 11 */ "Poorly maintained servers lead to lagging applications and frustrated users.",
  /* 12 */ "Server failures can bring your business to a halt, causing lost productivity and revenue.",
  /* 13 */ "Without proper capacity planning, businesses struggle to scale IT infrastructure to meet evolving business needs.",
  /* 14 */ "25+ years of IT infrastructure expertise.",
  /* 15 */ "Resolving issues before they impact your business.",
  /* 16 */ "Advanced security measures to protect your servers.",
  /* 17 */ "Ensuring your IT infrastructure is operating efficiently.",
  /* 18 */ "Don’t wait for a server failure to disrupt your business. ITSco’s proactive server monitoring and maintenance services keep your IT environment secure, efficient, and always available.",
] as const
