// Content for /server-monitoring-and-maintenance/
//
// Verbatim copy lives in ./_source.ts (auto-generated by
// scripts/sync-content.mjs). This file maps each slot to source indices.

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Server Monitoring & Maintenance Services',
    description:
      'ITSco server monitoring and maintenance — 24/7 proactive monitoring, patching, and expert troubleshooting that minimizes downtime. Book a free consultation.',
    canonical: 'https://www.itsco.com/server-monitoring-and-maintenance/',
  },
  serviceName: 'Server Monitoring & Maintenance',
  parent: { name: 'Managed IT Services', href: '/managed-it-services/' },
  hero: {
    eyebrow: 'Managed IT · Server Services',
    headlineLead: 'Server monitoring and maintenance',
    headlineAccent: 'that prevents downtime.',
    body: S[0],
    utmSuffix: 'server-monitoring-hero',
  },
  heroImage: {
    src: '/images/hero/services/aleksei-zhivilov-A6M3aowKR6I-unsplash.jpg',
    alt: 'ITSco engineer monitoring server health on multiple displays',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Maximum performance, security, and uptime for',
    headlineAccent: 'critical business systems.',
    paragraphs: [S[1]],
  },
  stats: [
    { value: '25+', label: 'Years of IT infrastructure expertise' },
    { value: '24/7', label: 'Proactive monitoring and incident response' },
    { value: '60%', label: 'Of our clients have been with us for 5+ years' },
  ],
  capabilitiesHeading: {
    eyebrow: 'Comprehensive Server Monitoring & Maintenance',
    headlineLead: 'Everything it takes to keep',
    headlineAccent: 'your servers healthy.',
  },
  capabilities: [
    {
      slug: 'server-monitoring-response',
      title: '24/7 Server Monitoring & Incident Response',
      description: S[2],
    },
    {
      slug: 'server-maintenance-optimization',
      title: 'Regular Maintenance & Performance Optimization',
      description: S[3],
    },
    {
      slug: 'server-security-hardening',
      title: 'Security Hardening & Compliance Support',
      description: S[4],
    },
    {
      slug: 'server-backup-recovery',
      title: 'Backup & Disaster Recovery Management',
      description: S[5],
    },
    {
      slug: 'server-capacity-planning',
      title: 'Capacity Planning & Resource Optimization',
      description: S[6],
    },
    {
      slug: 'server-troubleshooting',
      title: 'Expert Troubleshooting & Root Cause Analysis',
      description: S[7],
    },
  ],
  outcomes: {
    tone: 'risk',
    eyebrow: 'The Risk',
    headlineLead: 'The risks of',
    headlineAccent: 'poor server management.',
    paragraphs: [],
    bullets: [S[9], S[10], S[11], S[12], S[13]],
    image: {
      src: '/images/supporting/services/pexels-mart-production-7088498.jpg',
      alt: 'IT professional inspecting server rack hardware',
    },
  },
  related: {
    heading: 'Explore more managed IT services',
    links: [
      {
        slug: 'managed-network-services',
        label: 'Managed Network Services',
        href: '/managed-network-services/',
        description: 'Proactive monitoring, design, and support across your entire network.',
      },
      {
        slug: 'backup-disaster-recovery',
        label: 'Backup & Disaster Recovery',
        href: '/backup-disaster-recovery/',
        description: 'Automated backups and tested recovery plans that protect against the worst case.',
      },
      {
        slug: 'hardware-software-support',
        label: 'Server Administration & Support',
        href: '/server-admin-and-support-services/',
        description: 'End-to-end server administration backed by certified engineers, 24/7.',
      },
    ],
  },
  bookingUtm: 'server-monitoring-bottom',
}
