// Content for /asset-lifecycle-management/
//
// Verbatim copy lives in ./_source.ts (auto-generated by
// scripts/sync-content.mjs). This file maps each slot to source indices.
// Live URL is /services/managed-it-services/asset-lifecycle-management/ —
// migrated to this flat URL with a 301 in REDIRECTS.js.

import type { ServiceSubContent } from '@/components/ServiceSubPage'
import { SOURCE_PARAGRAPHS as S } from './_source'

export const CONTENT: ServiceSubContent = {
  meta: {
    title: 'Asset Lifecycle Management & IT Asset Disposition | ITSco',
    description:
      'ITSco asset lifecycle management — procurement, deployment, maintenance, and secure, sustainable IT asset disposition. Book a free consultation.',
    canonical: 'https://www.itsco.com/asset-lifecycle-management/',
  },
  serviceName: 'Asset Lifecycle Management',
  hero: {
    eyebrow: 'Managed IT · Asset Management',
    headlineLead: 'Asset lifecycle management,',
    headlineAccent: 'end to end.',
    body: S[0],
    utmSuffix: 'asset-lifecycle-management-hero',
  },
  heroImage: {
    src: '/images/hero/services/hoi-an-and-da-nang-photographer-fiQ4aTDEjcs-unsplash.jpg',
    alt: 'IT hardware inventory ready for deployment and tracking',
  },
  intro: {
    eyebrow: 'The Promise',
    headlineLead: 'Maximize asset value at',
    headlineAccent: 'every stage of the lifecycle.',
    paragraphs: [S[1], S[2]],
  },
  capabilitiesHeading: {
    eyebrow: "Tap Into ITSco's Asset Management Services",
    headlineLead: 'Every stage of the asset journey,',
    headlineAccent: 'managed for you.',
  },
  capabilities: [
    { slug: 'site-assessment', title: 'Site Assessment', description: S[3] },
    {
      slug: 'hardware-maintenance',
      title: 'Hardware Maintenance and Repair',
      description: S[4],
    },
    {
      slug: 'inventory-auditing',
      title: 'Inventory Auditing and Reporting',
      description: S[5],
    },
    {
      slug: 'certified-data-destruction',
      title: 'Certified Data Destruction',
      description: S[6],
    },
    { slug: 'de-installation', title: 'De-Installation Services', description: S[7] },
    { slug: 'relocation-services', title: 'Relocation Services', description: S[8] },
    { slug: 'ewaste-recycling', title: 'E-Waste Recycling', description: S[9] },
  ],
  outcomes: {
    eyebrow: 'Secure & Sustainable',
    headlineLead: 'Protect your data with',
    headlineAccent: 'responsible asset disposition.',
    paragraphs: [S[10], S[11], S[12]],
    image: {
      src: '/images/supporting/services/pexels-thirdman-5582868.jpg',
      alt: 'IT equipment being prepared for secure, sustainable disposition',
    },
  },
  related: {
    heading: 'Explore more managed IT services',
    links: [
      {
        slug: 'managed-network-services',
        label: 'Managed Network Services',
        href: '/managed-network-services/',
        description: 'Proactive monitoring, design, and support across your entire network.',
      },
      {
        slug: 'server-monitoring-and-maintenance',
        label: 'Server Monitoring & Maintenance',
        href: '/server-monitoring-and-maintenance/',
        description: '24/7 monitoring, patching, and tuning that keeps critical servers healthy.',
      },
      {
        slug: 'managed-it-services',
        label: 'Managed IT Services',
        href: '/managed-it-services/',
        description: 'The full ITSco managed IT program — monitoring, helpdesk, security, and more.',
      },
    ],
  },
  bookingUtm: 'asset-lifecycle-management-bottom',
}
