// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../app/about-us/meet-the-team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about-us/meet-the-team">> = Specific
  const handler = {} as typeof import("../../../app/about-us/meet-the-team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/about-us/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about-us">> = Specific
  const handler = {} as typeof import("../../../app/about-us/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/ai-automation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-automation">> = Specific
  const handler = {} as typeof import("../../../app/ai-automation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/ai-governance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-governance">> = Specific
  const handler = {} as typeof import("../../../app/ai-governance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/apex-cyber-security-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apex-cyber-security-services">> = Specific
  const handler = {} as typeof import("../../../app/apex-cyber-security-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/best-remote-support-software-for-small-business/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/best-remote-support-software-for-small-business">> = Specific
  const handler = {} as typeof import("../../../app/blog/best-remote-support-software-for-small-business/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/cloud-migration-challenges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/cloud-migration-challenges">> = Specific
  const handler = {} as typeof import("../../../app/blog/cloud-migration-challenges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/cost-of-it-support-for-small-business/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/cost-of-it-support-for-small-business">> = Specific
  const handler = {} as typeof import("../../../app/blog/cost-of-it-support-for-small-business/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/cyber-security-training-benefits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/cyber-security-training-benefits">> = Specific
  const handler = {} as typeof import("../../../app/blog/cyber-security-training-benefits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/infrastructure-outsource/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/infrastructure-outsource">> = Specific
  const handler = {} as typeof import("../../../app/blog/infrastructure-outsource/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/it-cost-reduction/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/it-cost-reduction">> = Specific
  const handler = {} as typeof import("../../../app/blog/it-cost-reduction/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/network-security-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/network-security-plan">> = Specific
  const handler = {} as typeof import("../../../app/blog/network-security-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/raleigh-industries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/raleigh-industries">> = Specific
  const handler = {} as typeof import("../../../app/blog/raleigh-industries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/staff-augmentation-vs-managed-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/staff-augmentation-vs-managed-services">> = Specific
  const handler = {} as typeof import("../../../app/blog/staff-augmentation-vs-managed-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/types-of-cloud-computing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/types-of-cloud-computing">> = Specific
  const handler = {} as typeof import("../../../app/blog/types-of-cloud-computing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/types-of-network-security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/types-of-network-security">> = Specific
  const handler = {} as typeof import("../../../app/blog/types-of-network-security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/what-is-cyber-vandalism/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/what-is-cyber-vandalism">> = Specific
  const handler = {} as typeof import("../../../app/blog/what-is-cyber-vandalism/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/why-is-network-security-important/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/why-is-network-security-important">> = Specific
  const handler = {} as typeof import("../../../app/blog/why-is-network-security-important/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/burlington-cyber-security-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/burlington-cyber-security-services">> = Specific
  const handler = {} as typeof import("../../../app/burlington-cyber-security-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/cary-cyber-security-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cary-cyber-security-services">> = Specific
  const handler = {} as typeof import("../../../app/cary-cyber-security-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/chapel-hill-cyber-security-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chapel-hill-cyber-security-services">> = Specific
  const handler = {} as typeof import("../../../app/chapel-hill-cyber-security-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/charlotte-cyber-security-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/charlotte-cyber-security-services">> = Specific
  const handler = {} as typeof import("../../../app/charlotte-cyber-security-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/charlotte-it-consulting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/charlotte-it-consulting">> = Specific
  const handler = {} as typeof import("../../../app/charlotte-it-consulting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/charlotte-it-helpdesk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/charlotte-it-helpdesk">> = Specific
  const handler = {} as typeof import("../../../app/charlotte-it-helpdesk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/charlotte-it-network-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/charlotte-it-network-support">> = Specific
  const handler = {} as typeof import("../../../app/charlotte-it-network-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/charlotte-it-outsourcing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/charlotte-it-outsourcing">> = Specific
  const handler = {} as typeof import("../../../app/charlotte-it-outsourcing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/construction-it-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/construction-it-services">> = Specific
  const handler = {} as typeof import("../../../app/construction-it-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contact-us/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact-us">> = Specific
  const handler = {} as typeof import("../../../app/contact-us/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/cybersecurity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cybersecurity">> = Specific
  const handler = {} as typeof import("../../../app/cybersecurity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/demo-cream/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo-cream">> = Specific
  const handler = {} as typeof import("../../../app/demo-cream/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/demo-lite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo-lite">> = Specific
  const handler = {} as typeof import("../../../app/demo-lite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/demo-oat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo-oat">> = Specific
  const handler = {} as typeof import("../../../app/demo-oat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../../app/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/durham-cyber-security-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/durham-cyber-security-services">> = Specific
  const handler = {} as typeof import("../../../app/durham-cyber-security-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/durham-it-consulting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/durham-it-consulting">> = Specific
  const handler = {} as typeof import("../../../app/durham-it-consulting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fayetteville-cyber-security-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fayetteville-cyber-security-services">> = Specific
  const handler = {} as typeof import("../../../app/fayetteville-cyber-security-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/garner-cyber-security-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/garner-cyber-security-services">> = Specific
  const handler = {} as typeof import("../../../app/garner-cyber-security-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/greensboro-it-consulting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/greensboro-it-consulting">> = Specific
  const handler = {} as typeof import("../../../app/greensboro-it-consulting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/healthcare-ai-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/healthcare-ai-services">> = Specific
  const handler = {} as typeof import("../../../app/healthcare-ai-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/healthcare-managed-it-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/healthcare-managed-it-services">> = Specific
  const handler = {} as typeof import("../../../app/healthcare-managed-it-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/hillsborough-cyber-security-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hillsborough-cyber-security-services">> = Specific
  const handler = {} as typeof import("../../../app/hillsborough-cyber-security-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/industries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/industries">> = Specific
  const handler = {} as typeof import("../../../app/industries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/it-company-durham/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/it-company-durham">> = Specific
  const handler = {} as typeof import("../../../app/it-company-durham/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/it-company-in-knightdale/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/it-company-in-knightdale">> = Specific
  const handler = {} as typeof import("../../../app/it-company-in-knightdale/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/it-company-raleigh/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/it-company-raleigh">> = Specific
  const handler = {} as typeof import("../../../app/it-company-raleigh/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/it-support-charlotte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/it-support-charlotte">> = Specific
  const handler = {} as typeof import("../../../app/it-support-charlotte/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/it-support-durham/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/it-support-durham">> = Specific
  const handler = {} as typeof import("../../../app/it-support-durham/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/it-support-garner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/it-support-garner">> = Specific
  const handler = {} as typeof import("../../../app/it-support-garner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/it-support-greensboro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/it-support-greensboro">> = Specific
  const handler = {} as typeof import("../../../app/it-support-greensboro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/it-support-raleigh/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/it-support-raleigh">> = Specific
  const handler = {} as typeof import("../../../app/it-support-raleigh/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/it-support-rocky-mount/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/it-support-rocky-mount">> = Specific
  const handler = {} as typeof import("../../../app/it-support-rocky-mount/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/legal-and-law-firm-it-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal-and-law-firm-it-services">> = Specific
  const handler = {} as typeof import("../../../app/legal-and-law-firm-it-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-apex/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-apex">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-apex/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-burlington/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-burlington">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-burlington/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-cary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-cary">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-cary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-chapel-hill/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-chapel-hill">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-chapel-hill/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-charlotte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-charlotte">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-charlotte/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-concord/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-concord">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-concord/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-durham/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-durham">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-durham/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-fayetteville/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-fayetteville">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-fayetteville/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-gastonia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-gastonia">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-gastonia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-greensboro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-greensboro">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-greensboro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-high-point/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-high-point">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-high-point/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-hillsborough/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-hillsborough">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-hillsborough/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-huntersville/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-huntersville">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-huntersville/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-raleigh/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-raleigh">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-raleigh/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-rocky-mount/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-rocky-mount">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-rocky-mount/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-rtp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-rtp">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-rtp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-wilmington/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-wilmington">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-wilmington/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services-winston-salem/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services-winston-salem">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services-winston-salem/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/managed-it-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/managed-it-services">> = Specific
  const handler = {} as typeof import("../../../app/managed-it-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/marketing-it-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing-it-services">> = Specific
  const handler = {} as typeof import("../../../app/marketing-it-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/maximize-roi-with-managed-it-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maximize-roi-with-managed-it-services">> = Specific
  const handler = {} as typeof import("../../../app/maximize-roi-with-managed-it-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page-a-lite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/page-a-lite">> = Specific
  const handler = {} as typeof import("../../../app/page-a-lite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page-a/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/page-a">> = Specific
  const handler = {} as typeof import("../../../app/page-a/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page-b-lite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/page-b-lite">> = Specific
  const handler = {} as typeof import("../../../app/page-b-lite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page-b/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/page-b">> = Specific
  const handler = {} as typeof import("../../../app/page-b/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page-c-lite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/page-c-lite">> = Specific
  const handler = {} as typeof import("../../../app/page-c-lite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page-c/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/page-c">> = Specific
  const handler = {} as typeof import("../../../app/page-c/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pharma-med-tech-it-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pharma-med-tech-it-services">> = Specific
  const handler = {} as typeof import("../../../app/pharma-med-tech-it-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/process/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/process">> = Specific
  const handler = {} as typeof import("../../../app/process/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/raleigh-cyber-security-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/raleigh-cyber-security-services">> = Specific
  const handler = {} as typeof import("../../../app/raleigh-cyber-security-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/raleigh-it-consulting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/raleigh-it-consulting">> = Specific
  const handler = {} as typeof import("../../../app/raleigh-it-consulting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/raleigh-it-helpdesk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/raleigh-it-helpdesk">> = Specific
  const handler = {} as typeof import("../../../app/raleigh-it-helpdesk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/raleigh-it-network-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/raleigh-it-network-support">> = Specific
  const handler = {} as typeof import("../../../app/raleigh-it-network-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/raleigh-it-outsourcing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/raleigh-it-outsourcing">> = Specific
  const handler = {} as typeof import("../../../app/raleigh-it-outsourcing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/real-estate-it-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/real-estate-it-services">> = Specific
  const handler = {} as typeof import("../../../app/real-estate-it-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources">> = Specific
  const handler = {} as typeof import("../../../app/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/rocky-mount-cyber-security-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rocky-mount-cyber-security-services">> = Specific
  const handler = {} as typeof import("../../../app/rocky-mount-cyber-security-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../../app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/transportation-logistics-it-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/transportation-logistics-it-services">> = Specific
  const handler = {} as typeof import("../../../app/transportation-logistics-it-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/winston-salem-it-consulting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/winston-salem-it-consulting">> = Specific
  const handler = {} as typeof import("../../../app/winston-salem-it-consulting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/winston-salem-tech-it-support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/winston-salem-tech-it-support">> = Specific
  const handler = {} as typeof import("../../../app/winston-salem-tech-it-support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
